module

public import ImprovedExponents.Optimum.Shapes.NumLog

@[expose] public section

/-!
# The saving with the shape `(2, 6)` on `(13, 26.986]`: cells 1 to 33

This file is generated by `python3 -m search.certs`; do not edit it. Each lemma bounds
`shapeSaving 12 5 c` on one cell `[c₁, c₂]` by `F(A(c₁), Γ(c₂))`, with certified rational bounds
on `A(c₁)` and `Γ(c₂)`; the last lemma joins the cells.
-/

namespace ImprovedExponents

open Set

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ (13, 17.2]`. -/
theorem shapeSaving_S26_cell_1 : ∀ c ∈ Ioc (13 : ℝ) 17.2,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Ioc 2
    (le_basePrunedS 4 4 : (16.67216 : ℝ) ≤ basePrunedS 12 13)
    (GamS_le (θ := 0.142629) (gammaXS_le 4 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 17.2 ≤ 0.0336283) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [17.2, 19.5]`. -/
theorem shapeSaving_S26_cell_2 : ∀ c ∈ Icc (17.2 : ℝ) 19.5,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 4 : (22.03537 : ℝ) ≤ basePrunedS 12 17.2)
    (GamS_le (θ := 0.139643) (gammaXS_le 4 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 19.5 ≤ 0.0442458) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [19.5, 21]`. -/
theorem shapeSaving_S26_cell_3 : ∀ c ∈ Icc (19.5 : ℝ) 21,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 4 : (24.95754 : ℝ) ≤ basePrunedS 12 19.5)
    (GamS_le (θ := 0.137951) (gammaXS_le 4 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 21 ≤ 0.0502845) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [21, 22]`. -/
theorem shapeSaving_S26_cell_4 : ∀ c ∈ Icc (21 : ℝ) 22,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 4 : (26.85922 : ℝ) ≤ basePrunedS 12 21)
    (GamS_le (θ := 0.136916) (gammaXS_le 4 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 22 ≤ 0.0539931) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [22, 22.83]`. -/
theorem shapeSaving_S26_cell_5 : ∀ c ∈ Icc (22 : ℝ) 22.83,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 4 : (28.12549 : ℝ) ≤ basePrunedS 12 22)
    (GamS_le (θ := 0.136105) (gammaXS_le 4 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 22.83 ≤ 0.0569016) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [22.83, 23.46]`. -/
theorem shapeSaving_S26_cell_6 : ∀ c ∈ Icc (22.83 : ℝ) 23.46,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (29.17567 : ℝ) ≤ basePrunedS 12 22.83)
    (GamS_le (θ := 0.135516) (gammaXS_le 4 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 23.46 ≤ 0.0590153) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [23.46, 23.96]`. -/
theorem shapeSaving_S26_cell_7 : ∀ c ∈ Icc (23.46 : ℝ) 23.96,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (29.97233 : ℝ) ≤ basePrunedS 12 23.46)
    (GamS_le (θ := 0.135065) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 23.96 ≤ 0.0606394) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [23.96, 24.36]`. -/
theorem shapeSaving_S26_cell_8 : ∀ c ∈ Icc (23.96 : ℝ) 24.36,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (30.60433 : ℝ) ≤ basePrunedS 12 23.96)
    (GamS_le (θ := 0.134713) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 24.36 ≤ 0.061906) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [24.36, 24.69]`. -/
theorem shapeSaving_S26_cell_9 : ∀ c ∈ Icc (24.36 : ℝ) 24.69,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (31.10977 : ℝ) ≤ basePrunedS 12 24.36)
    (GamS_le (θ := 0.134428) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 24.69 ≤ 0.0629298) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [24.69, 24.97]`. -/
theorem shapeSaving_S26_cell_10 : ∀ c ∈ Icc (24.69 : ℝ) 24.97,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (31.52664 : ℝ) ≤ basePrunedS 12 24.69)
    (GamS_le (θ := 0.134191) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 24.97 ≤ 0.0637845) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [24.97, 25.21]`. -/
theorem shapeSaving_S26_cell_11 : ∀ c ∈ Icc (24.97 : ℝ) 25.21,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (31.88029 : ℝ) ≤ basePrunedS 12 24.97)
    (GamS_le (θ := 0.13399) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 25.21 ≤ 0.0645067) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [25.21, 25.41]`. -/
theorem shapeSaving_S26_cell_12 : ∀ c ∈ Icc (25.21 : ℝ) 25.41,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (32.18336 : ℝ) ≤ basePrunedS 12 25.21)
    (GamS_le (θ := 0.133825) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 25.41 ≤ 0.0651016) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [25.41, 25.58]`. -/
theorem shapeSaving_S26_cell_13 : ∀ c ∈ Icc (25.41 : ℝ) 25.58,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (32.43588 : ℝ) ≤ basePrunedS 12 25.41)
    (GamS_le (θ := 0.133687) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 25.58 ≤ 0.0656027) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [25.58, 25.73]`. -/
theorem shapeSaving_S26_cell_14 : ∀ c ∈ Icc (25.58 : ℝ) 25.73,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (32.6505 : ℝ) ≤ basePrunedS 12 25.58)
    (GamS_le (θ := 0.133565) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 25.73 ≤ 0.0660406) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [25.73, 25.87]`. -/
theorem shapeSaving_S26_cell_15 : ∀ c ∈ Icc (25.73 : ℝ) 25.87,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (32.83985 : ℝ) ≤ basePrunedS 12 25.73)
    (GamS_le (θ := 0.133453) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 25.87 ≤ 0.0664468) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [25.87, 25.99]`. -/
theorem shapeSaving_S26_cell_16 : ∀ c ∈ Icc (25.87 : ℝ) 25.99,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (33.01656 : ℝ) ≤ basePrunedS 12 25.87)
    (GamS_le (θ := 0.133357) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 25.99 ≤ 0.0667922) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [25.99, 26.1]`. -/
theorem shapeSaving_S26_cell_17 : ∀ c ∈ Icc (25.99 : ℝ) 26.1,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (33.16801 : ℝ) ≤ basePrunedS 12 25.99)
    (GamS_le (θ := 0.13327) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 26.1 ≤ 0.0671072) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [26.1, 26.2]`. -/
theorem shapeSaving_S26_cell_18 : ∀ c ∈ Icc (26.1 : ℝ) 26.2,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (33.30683 : ℝ) ≤ basePrunedS 12 26.1)
    (GamS_le (θ := 0.133191) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 26.2 ≤ 0.0673919) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [26.2, 26.29]`. -/
theorem shapeSaving_S26_cell_19 : ∀ c ∈ Icc (26.2 : ℝ) 26.29,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (33.43303 : ℝ) ≤ basePrunedS 12 26.2)
    (GamS_le (θ := 0.13312) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 26.29 ≤ 0.0676468) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [26.29, 26.372]`. -/
theorem shapeSaving_S26_cell_20 : ∀ c ∈ Icc (26.29 : ℝ) 26.372,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (33.5466 : ℝ) ≤ basePrunedS 12 26.29)
    (GamS_le (θ := 0.133056) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 26.372 ≤ 0.0678781) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [26.372, 26.446]`. -/
theorem shapeSaving_S26_cell_21 : ∀ c ∈ Icc (26.372 : ℝ) 26.446,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (33.65007 : ℝ) ≤ basePrunedS 12 26.372)
    (GamS_le (θ := 0.132998) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 26.446 ≤ 0.068086) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [26.446, 26.514]`. -/
theorem shapeSaving_S26_cell_22 : ∀ c ∈ Icc (26.446 : ℝ) 26.514,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (33.74344 : ℝ) ≤ basePrunedS 12 26.446)
    (GamS_le (θ := 0.132946) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 26.514 ≤ 0.0682767) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [26.514, 26.576]`. -/
theorem shapeSaving_S26_cell_23 : ∀ c ∈ Icc (26.514 : ℝ) 26.576,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (33.82923 : ℝ) ≤ basePrunedS 12 26.514)
    (GamS_le (θ := 0.132898) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 26.576 ≤ 0.0684497) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [26.576, 26.633]`. -/
theorem shapeSaving_S26_cell_24 : ∀ c ∈ Icc (26.576 : ℝ) 26.633,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (33.90745 : ℝ) ≤ basePrunedS 12 26.576)
    (GamS_le (θ := 0.132854) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 26.633 ≤ 0.0686082) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [26.633, 26.685]`. -/
theorem shapeSaving_S26_cell_25 : ∀ c ∈ Icc (26.633 : ℝ) 26.685,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (33.97937 : ℝ) ≤ basePrunedS 12 26.633)
    (GamS_le (θ := 0.132814) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 26.685 ≤ 0.0687525) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [26.685, 26.733]`. -/
theorem shapeSaving_S26_cell_26 : ∀ c ∈ Icc (26.685 : ℝ) 26.733,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (34.04497 : ℝ) ≤ basePrunedS 12 26.685)
    (GamS_le (θ := 0.132777) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 26.733 ≤ 0.0688853) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [26.733, 26.778]`. -/
theorem shapeSaving_S26_cell_27 : ∀ c ∈ Icc (26.733 : ℝ) 26.778,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (34.10552 : ℝ) ≤ basePrunedS 12 26.733)
    (GamS_le (θ := 0.132743) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 26.778 ≤ 0.0690098) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [26.778, 26.819]`. -/
theorem shapeSaving_S26_cell_28 : ∀ c ∈ Icc (26.778 : ℝ) 26.819,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (34.16229 : ℝ) ≤ basePrunedS 12 26.778)
    (GamS_le (θ := 0.132711) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 26.819 ≤ 0.0691229) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [26.819, 26.857]`. -/
theorem shapeSaving_S26_cell_29 : ∀ c ∈ Icc (26.819 : ℝ) 26.857,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (34.21401 : ℝ) ≤ basePrunedS 12 26.819)
    (GamS_le (θ := 0.132683) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 26.857 ≤ 0.0692274) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [26.857, 26.893]`. -/
theorem shapeSaving_S26_cell_30 : ∀ c ∈ Icc (26.857 : ℝ) 26.893,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (34.26194 : ℝ) ≤ basePrunedS 12 26.857)
    (GamS_le (θ := 0.132655) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 26.893 ≤ 0.0693258) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [26.893, 26.926]`. -/
theorem shapeSaving_S26_cell_31 : ∀ c ∈ Icc (26.893 : ℝ) 26.926,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (34.30735 : ℝ) ≤ basePrunedS 12 26.893)
    (GamS_le (θ := 0.13263) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 26.926 ≤ 0.0694163) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [26.926, 26.957]`. -/
theorem shapeSaving_S26_cell_32 : ∀ c ∈ Icc (26.926 : ℝ) 26.957,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (34.34898 : ℝ) ≤ basePrunedS 12 26.926)
    (GamS_le (θ := 0.132607) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 26.957 ≤ 0.0695014) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c ∈ [26.957, 26.986]`. -/
theorem shapeSaving_S26_cell_33 : ∀ c ∈ Icc (26.957 : ℝ) 26.986,
    shapeSaving 12 5 c < 0.001623 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (34.38808 : ℝ) ≤ basePrunedS 12 26.957)
    (GamS_le (θ := 0.132585) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 26.986 ≤ 0.0695806) hc

/-- `shapeSaving 12 5 c < 0.001623` for `c` in `(13, 26.986]`: cells 1 to 33. -/
theorem shapeSaving_S26_block_1 : ∀ c ∈ Ioc (13 : ℝ) 26.986,
    shapeSaving 12 5 c < 0.001623 := by
  have h := shapeSaving_S26_cell_1
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_2
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_3
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_4
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_5
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_6
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_7
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_8
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_9
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_10
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_11
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_12
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_13
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_14
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_15
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_16
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_17
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_18
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_19
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_20
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_21
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_22
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_23
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_24
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_25
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_26
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_27
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_28
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_29
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_30
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_31
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_32
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S26_cell_33
  exact h

end ImprovedExponents
