module

public import ImprovedExponents.Optimum.Shapes.NumLog

@[expose] public section

/-!
# The saving with the shape `(3, 5)` on `(16, 32.56]`: cells 1 to 38

This file is generated by `python3 -m search.certs`; do not edit it. Each lemma bounds
`shapeSaving 15 8 c` on one cell `[c₁, c₂]` by `F(A(c₁), Γ(c₂))`, with certified rational bounds
on `A(c₁)` and `Γ(c₂)`; the last lemma joins the cells.
-/

namespace ImprovedExponents

open Set

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ (16, 20.8]`. -/
theorem shapeSaving_S35_cell_1 : ∀ c ∈ Ioc (16 : ℝ) 20.8,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Ioc 3
    (le_basePrunedS 4 4 : (22.1807 : ℝ) ≤ basePrunedS 15 16)
    (GamS_le (θ := 0.186529) (gammaXS_le 4 4 3)
      (gammaQS_le (-2) 4 3) : GamS 15 8 20.8 ≤ 0.0342661) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [20.8, 23.5]`. -/
theorem shapeSaving_S35_cell_2 : ∀ c ∈ Icc (20.8 : ℝ) 23.5,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 4 4 : (28.81495 : ℝ) ≤ basePrunedS 15 20.8)
    (GamS_le (θ := 0.182706) (gammaXS_le 4 4 3)
      (gammaQS_le (-2) 4 3) : GamS 15 8 23.5 ≤ 0.044547) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [23.5, 25.3]`. -/
theorem shapeSaving_S35_cell_3 : ∀ c ∈ Icc (23.5 : ℝ) 25.3,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (32.53327 : ℝ) ≤ basePrunedS 15 23.5)
    (GamS_le (θ := 0.180486) (gammaXS_le 5 4 3)
      (gammaQS_le (-2) 4 3) : GamS 15 8 25.3 ≤ 0.0505457) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [25.3, 26.5]`. -/
theorem shapeSaving_S35_cell_4 : ∀ c ∈ Icc (25.3 : ℝ) 26.5,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.00819 : ℝ) ≤ basePrunedS 15 25.3)
    (GamS_le (θ := 0.179125) (gammaXS_le 5 4 3)
      (gammaQS_le (-2) 4 3) : GamS 15 8 26.5 ≤ 0.0542327) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [26.5, 27.47]`. -/
theorem shapeSaving_S35_cell_5 : ∀ c ∈ Icc (26.5 : ℝ) 27.47,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (36.65665 : ℝ) ≤ basePrunedS 15 26.5)
    (GamS_le (θ := 0.178086) (gammaXS_le 5 4 3)
      (gammaQS_le (-2) 4 3) : GamS 15 8 27.47 ≤ 0.0570521) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [27.47, 28.21]`. -/
theorem shapeSaving_S35_cell_6 : ∀ c ∈ Icc (27.47 : ℝ) 28.21,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.98837 : ℝ) ≤ basePrunedS 15 27.47)
    (GamS_le (θ := 0.177328) (gammaXS_le 5 4 3)
      (gammaQS_le (-2) 4 3) : GamS 15 8 28.21 ≤ 0.0591149) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [28.21, 28.79]`. -/
theorem shapeSaving_S35_cell_7 : ∀ c ∈ Icc (28.21 : ℝ) 28.79,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (39.00389 : ℝ) ≤ basePrunedS 15 28.21)
    (GamS_le (θ := 0.176752) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 28.79 ≤ 0.0606812) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [28.79, 29.26]`. -/
theorem shapeSaving_S35_cell_8 : ∀ c ∈ Icc (28.79 : ℝ) 29.26,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (39.79958 : ℝ) ≤ basePrunedS 15 28.79)
    (GamS_le (θ := 0.176297) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 29.26 ≤ 0.0619198) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [29.26, 29.65]`. -/
theorem shapeSaving_S35_cell_9 : ∀ c ∈ Icc (29.26 : ℝ) 29.65,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (40.44421 : ℝ) ≤ basePrunedS 15 29.26)
    (GamS_le (θ := 0.175927) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 29.65 ≤ 0.0629278) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [29.65, 29.98]`. -/
theorem shapeSaving_S35_cell_10 : ∀ c ∈ Icc (29.65 : ℝ) 29.98,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (40.97902 : ℝ) ≤ basePrunedS 15 29.65)
    (GamS_le (θ := 0.17562) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 29.98 ≤ 0.0637668) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [29.98, 30.26]`. -/
theorem shapeSaving_S35_cell_11 : ∀ c ∈ Icc (29.98 : ℝ) 30.26,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (41.43147 : ℝ) ≤ basePrunedS 15 29.98)
    (GamS_le (θ := 0.175362) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 30.26 ≤ 0.064469) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [30.26, 30.5]`. -/
theorem shapeSaving_S35_cell_12 : ∀ c ∈ Icc (30.26 : ℝ) 30.5,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (41.81533 : ℝ) ≤ basePrunedS 15 30.26)
    (GamS_le (θ := 0.175144) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 30.5 ≤ 0.0650641) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [30.5, 30.71]`. -/
theorem shapeSaving_S35_cell_13 : ∀ c ∈ Icc (30.5 : ℝ) 30.71,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (42.14431 : ℝ) ≤ basePrunedS 15 30.5)
    (GamS_le (θ := 0.174956) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 30.71 ≤ 0.06558) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [30.71, 30.89]`. -/
theorem shapeSaving_S35_cell_14 : ∀ c ∈ Icc (30.71 : ℝ) 30.89,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (42.43214 : ℝ) ≤ basePrunedS 15 30.71)
    (GamS_le (θ := 0.174795) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 30.89 ≤ 0.066018) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [30.89, 31.05]`. -/
theorem shapeSaving_S35_cell_15 : ∀ c ∈ Icc (30.89 : ℝ) 31.05,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (42.67884 : ℝ) ≤ basePrunedS 15 30.89)
    (GamS_le (θ := 0.174654) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 31.05 ≤ 0.0664049) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [31.05, 31.2]`. -/
theorem shapeSaving_S35_cell_16 : ∀ c ∈ Icc (31.05 : ℝ) 31.2,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (42.89811 : ℝ) ≤ basePrunedS 15 31.05)
    (GamS_le (θ := 0.174522) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 31.2 ≤ 0.066765) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [31.2, 31.33]`. -/
theorem shapeSaving_S35_cell_17 : ∀ c ∈ Icc (31.2 : ℝ) 31.33,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (43.10366 : ℝ) ≤ basePrunedS 15 31.2)
    (GamS_le (θ := 0.174408) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 31.33 ≤ 0.067075) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [31.33, 31.45]`. -/
theorem shapeSaving_S35_cell_18 : ∀ c ∈ Icc (31.33 : ℝ) 31.45,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (43.2818 : ℝ) ≤ basePrunedS 15 31.33)
    (GamS_le (θ := 0.174304) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 31.45 ≤ 0.06736) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [31.45, 31.55]`. -/
theorem shapeSaving_S35_cell_19 : ∀ c ∈ Icc (31.45 : ℝ) 31.55,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (43.44622 : ℝ) ≤ basePrunedS 15 31.45)
    (GamS_le (θ := 0.174218) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 31.55 ≤ 0.0675964) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [31.55, 31.65]`. -/
theorem shapeSaving_S35_cell_20 : ∀ c ∈ Icc (31.55 : ℝ) 31.65,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (43.58324 : ℝ) ≤ basePrunedS 15 31.55)
    (GamS_le (θ := 0.174132) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 31.65 ≤ 0.0678318) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [31.65, 31.741]`. -/
theorem shapeSaving_S35_cell_21 : ∀ c ∈ Icc (31.65 : ℝ) 31.741,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (43.72025 : ℝ) ≤ basePrunedS 15 31.65)
    (GamS_le (θ := 0.174054) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 31.741 ≤ 0.068045) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [31.741, 31.824]`. -/
theorem shapeSaving_S35_cell_22 : ∀ c ∈ Icc (31.741 : ℝ) 31.824,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (43.84492 : ℝ) ≤ basePrunedS 15 31.741)
    (GamS_le (θ := 0.173983) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 31.824 ≤ 0.0682387) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [31.824, 31.9]`. -/
theorem shapeSaving_S35_cell_23 : ∀ c ∈ Icc (31.824 : ℝ) 31.9,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (43.95864 : ℝ) ≤ basePrunedS 15 31.824)
    (GamS_le (θ := 0.173918) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 31.9 ≤ 0.0684155) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [31.9, 31.97]`. -/
theorem shapeSaving_S35_cell_24 : ∀ c ∈ Icc (31.9 : ℝ) 31.97,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (44.06275 : ℝ) ≤ basePrunedS 15 31.9)
    (GamS_le (θ := 0.173859) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 31.97 ≤ 0.068578) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [31.97, 32.035]`. -/
theorem shapeSaving_S35_cell_25 : ∀ c ∈ Icc (31.97 : ℝ) 32.035,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (44.15865 : ℝ) ≤ basePrunedS 15 31.97)
    (GamS_le (θ := 0.173804) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 32.035 ≤ 0.0687284) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [32.035, 32.095]`. -/
theorem shapeSaving_S35_cell_26 : ∀ c ∈ Icc (32.035 : ℝ) 32.095,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (44.24769 : ℝ) ≤ basePrunedS 15 32.035)
    (GamS_le (θ := 0.173753) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 32.095 ≤ 0.0688667) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [32.095, 32.15]`. -/
theorem shapeSaving_S35_cell_27 : ∀ c ∈ Icc (32.095 : ℝ) 32.15,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (44.32988 : ℝ) ≤ basePrunedS 15 32.095)
    (GamS_le (θ := 0.173707) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 32.15 ≤ 0.0689935) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [32.15, 32.201]`. -/
theorem shapeSaving_S35_cell_28 : ∀ c ∈ Icc (32.15 : ℝ) 32.201,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (44.40523 : ℝ) ≤ basePrunedS 15 32.15)
    (GamS_le (θ := 0.173664) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 32.201 ≤ 0.0691105) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [32.201, 32.249]`. -/
theorem shapeSaving_S35_cell_29 : ∀ c ∈ Icc (32.201 : ℝ) 32.249,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (44.47509 : ℝ) ≤ basePrunedS 15 32.201)
    (GamS_le (θ := 0.173624) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 32.249 ≤ 0.0692207) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [32.249, 32.293]`. -/
theorem shapeSaving_S35_cell_30 : ∀ c ∈ Icc (32.249 : ℝ) 32.293,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (44.54084 : ℝ) ≤ basePrunedS 15 32.249)
    (GamS_le (θ := 0.173587) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 32.293 ≤ 0.0693212) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [32.293, 32.334]`. -/
theorem shapeSaving_S35_cell_31 : ∀ c ∈ Icc (32.293 : ℝ) 32.334,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (44.6011 : ℝ) ≤ basePrunedS 15 32.293)
    (GamS_le (θ := 0.173553) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 32.334 ≤ 0.069415) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [32.334, 32.373]`. -/
theorem shapeSaving_S35_cell_32 : ∀ c ∈ Icc (32.334 : ℝ) 32.373,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (44.65726 : ℝ) ≤ basePrunedS 15 32.334)
    (GamS_le (θ := 0.17352) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 32.373 ≤ 0.0695037) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [32.373, 32.409]`. -/
theorem shapeSaving_S35_cell_33 : ∀ c ∈ Icc (32.373 : ℝ) 32.409,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (44.71068 : ℝ) ≤ basePrunedS 15 32.373)
    (GamS_le (θ := 0.17349) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 32.409 ≤ 0.0695856) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [32.409, 32.443]`. -/
theorem shapeSaving_S35_cell_34 : ∀ c ∈ Icc (32.409 : ℝ) 32.443,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (44.75999 : ℝ) ≤ basePrunedS 15 32.409)
    (GamS_le (θ := 0.173462) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 32.443 ≤ 0.069663) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [32.443, 32.475]`. -/
theorem shapeSaving_S35_cell_35 : ∀ c ∈ Icc (32.443 : ℝ) 32.475,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (44.80656 : ℝ) ≤ basePrunedS 15 32.443)
    (GamS_le (θ := 0.173436) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 32.475 ≤ 0.0697359) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [32.475, 32.505]`. -/
theorem shapeSaving_S35_cell_36 : ∀ c ∈ Icc (32.475 : ℝ) 32.505,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (44.85039 : ℝ) ≤ basePrunedS 15 32.475)
    (GamS_le (θ := 0.173411) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 32.505 ≤ 0.0698039) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [32.505, 32.533]`. -/
theorem shapeSaving_S35_cell_37 : ∀ c ∈ Icc (32.505 : ℝ) 32.533,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (44.89148 : ℝ) ≤ basePrunedS 15 32.505)
    (GamS_le (θ := 0.173388) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 32.533 ≤ 0.0698674) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c ∈ [32.533, 32.56]`. -/
theorem shapeSaving_S35_cell_38 : ∀ c ∈ Icc (32.533 : ℝ) 32.56,
    shapeSaving 15 8 c < 0.001613 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (44.92983 : ℝ) ≤ basePrunedS 15 32.533)
    (GamS_le (θ := 0.173365) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 32.56 ≤ 0.0699282) hc

/-- `shapeSaving 15 8 c < 0.001613` for `c` in `(16, 32.56]`: cells 1 to 38. -/
theorem shapeSaving_S35_block_1 : ∀ c ∈ Ioc (16 : ℝ) 32.56,
    shapeSaving 15 8 c < 0.001613 := by
  have h := shapeSaving_S35_cell_1
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_2
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_3
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_4
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_5
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_6
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_7
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_8
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_9
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_10
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_11
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_12
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_13
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_14
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_15
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_16
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_17
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_18
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_19
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_20
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_21
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_22
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_23
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_24
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_25
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_26
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_27
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_28
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_29
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_30
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_31
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_32
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_33
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_34
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_35
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_36
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_37
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S35_cell_38
  exact h

end ImprovedExponents
