module

public import ImprovedExponents.Optimum.Shapes.NumLog

@[expose] public section

/-!
# The saving with the shape `(5, 5)` on `(26, 51.545]`: cells 1 to 40

This file is generated by `python3 -m search.certs`; do not edit it. Each lemma bounds
`shapeSaving 25 16 c` on one cell `[c₁, c₂]` by `F(A(c₁), Γ(c₂))`, with certified rational bounds
on `A(c₁)` and `Γ(c₂)`; the last lemma joins the cells.
-/

namespace ImprovedExponents

open Set

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ (26, 33.3]`. -/
theorem shapeSaving_S55_cell_1 : ∀ c ∈ Ioc (26 : ℝ) 33.3,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Ioc 4
    (le_basePrunedS 5 5 : (42.35525 : ℝ) ≤ basePrunedS 25 26)
    (GamS_le (θ := 0.238396) (gammaXS_le 5 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 33.3 ≤ 0.0335219) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [33.3, 37.5]`. -/
theorem shapeSaving_S55_cell_2 : ∀ c ∈ Icc (33.3 : ℝ) 37.5,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 5 : (54.23003 : ℝ) ≤ basePrunedS 25 33.3)
    (GamS_le (θ := 0.233935) (gammaXS_le 5 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 37.5 ≤ 0.0429439) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [37.5, 40.2]`. -/
theorem shapeSaving_S55_cell_3 : ∀ c ∈ Icc (37.5 : ℝ) 40.2,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 5 : (61.04992 : ℝ) ≤ basePrunedS 25 37.5)
    (GamS_le (θ := 0.231415) (gammaXS_le 5 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 40.2 ≤ 0.0482917) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [40.2, 42.1]`. -/
theorem shapeSaving_S55_cell_4 : ∀ c ∈ Icc (40.2 : ℝ) 42.1,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 5 : (65.43062 : ℝ) ≤ basePrunedS 25 40.2)
    (GamS_le (θ := 0.229776) (gammaXS_le 5 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 42.1 ≤ 0.0517787) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [42.1, 43.5]`. -/
theorem shapeSaving_S55_cell_5 : ∀ c ∈ Icc (42.1 : ℝ) 43.5,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 5 : (68.51193 : ℝ) ≤ basePrunedS 25 42.1)
    (GamS_le (θ := 0.228631) (gammaXS_le 5 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 43.5 ≤ 0.0542182) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [43.5, 44.6]`. -/
theorem shapeSaving_S55_cell_6 : ∀ c ∈ Icc (43.5 : ℝ) 44.6,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 5 : (70.78169 : ℝ) ≤ basePrunedS 25 43.5)
    (GamS_le (θ := 0.227766) (gammaXS_le 5 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 44.6 ≤ 0.0560639) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [44.6, 45.54]`. -/
theorem shapeSaving_S55_cell_7 : ∀ c ∈ Icc (44.6 : ℝ) 45.54,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 5 : (72.5647 : ℝ) ≤ basePrunedS 25 44.6)
    (GamS_le (θ := 0.22705) (gammaXS_le 5 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 45.54 ≤ 0.0575946) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [45.54, 46.3]`. -/
theorem shapeSaving_S55_cell_8 : ∀ c ∈ Icc (45.54 : ℝ) 46.3,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (74.08812 : ℝ) ≤ basePrunedS 25 45.54)
    (GamS_le (θ := 0.226485) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 46.3 ≤ 0.0588021) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [46.3, 46.93]`. -/
theorem shapeSaving_S55_cell_9 : ∀ c ∈ Icc (46.3 : ℝ) 46.93,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (75.31966 : ℝ) ≤ basePrunedS 25 46.3)
    (GamS_le (θ := 0.226026) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 46.93 ≤ 0.0597835) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [46.93, 47.46]`. -/
theorem shapeSaving_S55_cell_10 : ∀ c ∈ Icc (46.93 : ℝ) 47.46,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (76.34044 : ℝ) ≤ basePrunedS 25 46.93)
    (GamS_le (θ := 0.225647) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 47.46 ≤ 0.0605962) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [47.46, 47.91]`. -/
theorem shapeSaving_S55_cell_11 : ∀ c ∈ Icc (47.46 : ℝ) 47.91,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (77.19912 : ℝ) ≤ basePrunedS 25 47.46)
    (GamS_le (θ := 0.225329) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 47.91 ≤ 0.0612767) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [47.91, 48.29]`. -/
theorem shapeSaving_S55_cell_12 : ∀ c ∈ Icc (47.91 : ℝ) 48.29,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (77.92813 : ℝ) ≤ basePrunedS 25 47.91)
    (GamS_le (θ := 0.225063) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 48.29 ≤ 0.061845) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [48.29, 48.62]`. -/
theorem shapeSaving_S55_cell_13 : ∀ c ∈ Icc (48.29 : ℝ) 48.62,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (78.54371 : ℝ) ≤ basePrunedS 25 48.29)
    (GamS_le (θ := 0.224835) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 48.62 ≤ 0.0623335) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [48.62, 48.91]`. -/
theorem shapeSaving_S55_cell_14 : ∀ c ∈ Icc (48.62 : ℝ) 48.91,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (79.07827 : ℝ) ≤ basePrunedS 25 48.62)
    (GamS_le (θ := 0.224637) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 48.91 ≤ 0.0627598) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [48.91, 49.17]`. -/
theorem shapeSaving_S55_cell_15 : ∀ c ∈ Icc (48.91 : ℝ) 49.17,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (79.54801 : ℝ) ≤ basePrunedS 25 48.91)
    (GamS_le (θ := 0.22446) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 49.17 ≤ 0.0631388) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [49.17, 49.4]`. -/
theorem shapeSaving_S55_cell_16 : ∀ c ∈ Icc (49.17 : ℝ) 49.4,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (79.96914 : ℝ) ≤ basePrunedS 25 49.17)
    (GamS_le (θ := 0.224304) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 49.4 ≤ 0.0634719) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [49.4, 49.6]`. -/
theorem shapeSaving_S55_cell_17 : ∀ c ∈ Icc (49.4 : ℝ) 49.6,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (80.34167 : ℝ) ≤ basePrunedS 25 49.4)
    (GamS_le (θ := 0.22417) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 49.6 ≤ 0.0637601) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [49.6, 49.78]`. -/
theorem shapeSaving_S55_cell_18 : ∀ c ∈ Icc (49.6 : ℝ) 49.78,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (80.6656 : ℝ) ≤ basePrunedS 25 49.6)
    (GamS_le (θ := 0.22405) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 49.78 ≤ 0.0640182) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [49.78, 49.95]`. -/
theorem shapeSaving_S55_cell_19 : ∀ c ∈ Icc (49.78 : ℝ) 49.95,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (80.95712 : ℝ) ≤ basePrunedS 25 49.78)
    (GamS_le (θ := 0.223937) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 49.95 ≤ 0.0642607) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [49.95, 50.1]`. -/
theorem shapeSaving_S55_cell_20 : ∀ c ∈ Icc (49.95 : ℝ) 50.1,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (81.23245 : ℝ) ≤ basePrunedS 25 49.95)
    (GamS_le (θ := 0.223837) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 50.1 ≤ 0.0644738) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [50.1, 50.24]`. -/
theorem shapeSaving_S55_cell_21 : ∀ c ∈ Icc (50.1 : ℝ) 50.24,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (81.47538 : ℝ) ≤ basePrunedS 25 50.1)
    (GamS_le (θ := 0.223745) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 50.24 ≤ 0.0646719) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [50.24, 50.36]`. -/
theorem shapeSaving_S55_cell_22 : ∀ c ∈ Icc (50.24 : ℝ) 50.36,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (81.70211 : ℝ) ≤ basePrunedS 25 50.24)
    (GamS_le (θ := 0.223666) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 50.36 ≤ 0.0648412) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [50.36, 50.47]`. -/
theorem shapeSaving_S55_cell_23 : ∀ c ∈ Icc (50.36 : ℝ) 50.47,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (81.89645 : ℝ) ≤ basePrunedS 25 50.36)
    (GamS_le (θ := 0.223594) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 50.47 ≤ 0.0649959) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [50.47, 50.57]`. -/
theorem shapeSaving_S55_cell_24 : ∀ c ∈ Icc (50.47 : ℝ) 50.57,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (82.07459 : ℝ) ≤ basePrunedS 25 50.47)
    (GamS_le (θ := 0.223529) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 50.57 ≤ 0.0651363) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [50.57, 50.67]`. -/
theorem shapeSaving_S55_cell_25 : ∀ c ∈ Icc (50.57 : ℝ) 50.67,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (82.23653 : ℝ) ≤ basePrunedS 25 50.57)
    (GamS_le (θ := 0.223464) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 50.67 ≤ 0.0652763) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [50.67, 50.763]`. -/
theorem shapeSaving_S55_cell_26 : ∀ c ∈ Icc (50.67 : ℝ) 50.763,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (82.39847 : ℝ) ≤ basePrunedS 25 50.67)
    (GamS_le (θ := 0.223403) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 50.763 ≤ 0.065406) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [50.763, 50.849]`. -/
theorem shapeSaving_S55_cell_27 : ∀ c ∈ Icc (50.763 : ℝ) 50.849,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (82.54908 : ℝ) ≤ basePrunedS 25 50.763)
    (GamS_le (θ := 0.223347) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 50.849 ≤ 0.0655256) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [50.849, 50.928]`. -/
theorem shapeSaving_S55_cell_28 : ∀ c ∈ Icc (50.849 : ℝ) 50.928,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (82.68834 : ℝ) ≤ basePrunedS 25 50.849)
    (GamS_le (θ := 0.223296) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 50.928 ≤ 0.0656355) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [50.928, 51.001]`. -/
theorem shapeSaving_S55_cell_29 : ∀ c ∈ Icc (50.928 : ℝ) 51.001,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (82.81627 : ℝ) ≤ basePrunedS 25 50.928)
    (GamS_le (θ := 0.223249) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.001 ≤ 0.0657368) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.001, 51.069]`. -/
theorem shapeSaving_S55_cell_30 : ∀ c ∈ Icc (51.001 : ℝ) 51.069,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (82.93449 : ℝ) ≤ basePrunedS 25 51.001)
    (GamS_le (θ := 0.223205) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.069 ≤ 0.0658308) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.069, 51.132]`. -/
theorem shapeSaving_S55_cell_31 : ∀ c ∈ Icc (51.069 : ℝ) 51.132,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (83.0446 : ℝ) ≤ basePrunedS 25 51.069)
    (GamS_le (θ := 0.223165) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.132 ≤ 0.0659181) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.132, 51.191]`. -/
theorem shapeSaving_S55_cell_32 : ∀ c ∈ Icc (51.132 : ℝ) 51.191,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (83.14662 : ℝ) ≤ basePrunedS 25 51.132)
    (GamS_le (θ := 0.223127) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.191 ≤ 0.0659995) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.191, 51.246]`. -/
theorem shapeSaving_S55_cell_33 : ∀ c ∈ Icc (51.191 : ℝ) 51.246,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (83.24216 : ℝ) ≤ basePrunedS 25 51.191)
    (GamS_le (θ := 0.223092) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.246 ≤ 0.0660754) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.246, 51.298]`. -/
theorem shapeSaving_S55_cell_34 : ∀ c ∈ Icc (51.246 : ℝ) 51.298,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (83.33122 : ℝ) ≤ basePrunedS 25 51.246)
    (GamS_le (θ := 0.223058) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.298 ≤ 0.0661467) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.298, 51.346]`. -/
theorem shapeSaving_S55_cell_35 : ∀ c ∈ Icc (51.298 : ℝ) 51.346,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (83.41542 : ℝ) ≤ basePrunedS 25 51.298)
    (GamS_le (θ := 0.223027) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.346 ≤ 0.0662129) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.346, 51.391]`. -/
theorem shapeSaving_S55_cell_36 : ∀ c ∈ Icc (51.346 : ℝ) 51.391,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (83.49315 : ℝ) ≤ basePrunedS 25 51.346)
    (GamS_le (θ := 0.222999) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.391 ≤ 0.0662746) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.391, 51.433]`. -/
theorem shapeSaving_S55_cell_37 : ∀ c ∈ Icc (51.391 : ℝ) 51.433,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (83.56601 : ℝ) ≤ basePrunedS 25 51.391)
    (GamS_le (θ := 0.222972) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.433 ≤ 0.0663321) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.433, 51.473]`. -/
theorem shapeSaving_S55_cell_38 : ∀ c ∈ Icc (51.433 : ℝ) 51.473,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (83.63402 : ℝ) ≤ basePrunedS 25 51.433)
    (GamS_le (θ := 0.222946) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.473 ≤ 0.0663869) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.473, 51.51]`. -/
theorem shapeSaving_S55_cell_39 : ∀ c ∈ Icc (51.473 : ℝ) 51.51,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (83.69879 : ℝ) ≤ basePrunedS 25 51.473)
    (GamS_le (θ := 0.222923) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.51 ≤ 0.0664376) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.51, 51.545]`. -/
theorem shapeSaving_S55_cell_40 : ∀ c ∈ Icc (51.51 : ℝ) 51.545,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (83.7587 : ℝ) ≤ basePrunedS 25 51.51)
    (GamS_le (θ := 0.222901) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.545 ≤ 0.0664855) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c` in `(26, 51.545]`: cells 1 to 40. -/
theorem shapeSaving_S55_block_1 : ∀ c ∈ Ioc (26 : ℝ) 51.545,
    shapeSaving 25 16 c < 0.001098 := by
  have h := shapeSaving_S55_cell_1
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_2
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_3
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_4
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_5
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_6
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_7
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_8
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_9
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_10
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_11
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_12
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_13
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_14
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_15
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_16
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_17
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_18
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_19
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_20
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_21
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_22
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_23
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_24
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_25
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_26
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_27
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_28
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_29
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_30
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_31
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_32
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_33
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_34
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_35
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_36
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_37
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_38
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_39
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S55_cell_40
  exact h

end ImprovedExponents
