module

public import ImprovedExponents.Optimum.Shapes.NumLog

@[expose] public section

/-!
# The saving with the shape `(2, 3)` on `[16.1724, 16.7]`: cells 153 to 199

This file is generated by `python3 -m search.certs`; do not edit it. Each lemma bounds
`shapeSaving 6 2 c` on one cell `[c₁, c₂]` by `F(A(c₁), Γ(c₂))`, with certified rational bounds
on `A(c₁)` and `Γ(c₂)`; the last lemma joins the cells.
-/

namespace ImprovedExponents

open Set

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.1724, 16.1789]`. -/
theorem shapeSaving_S23_cell_153 : ∀ c ∈ Icc (16.1724 : ℝ) 16.1789,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.4685 : ℝ) ≤ basePrunedS 6 16.1724)
    (GamS_le (θ := 0.05417) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.1789 ≤ 0.0748308) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.1789, 16.1855]`. -/
theorem shapeSaving_S23_cell_154 : ∀ c ∈ Icc (16.1789 : ℝ) 16.1855,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.47453 : ℝ) ≤ basePrunedS 6 16.1789)
    (GamS_le (θ := 0.054167) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.1855 ≤ 0.0748604) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.1855, 16.1923]`. -/
theorem shapeSaving_S23_cell_155 : ∀ c ∈ Icc (16.1855 : ℝ) 16.1923,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.48066 : ℝ) ≤ basePrunedS 6 16.1855)
    (GamS_le (θ := 0.054163) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.1923 ≤ 0.0748896) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.1923, 16.1991]`. -/
theorem shapeSaving_S23_cell_156 : ∀ c ∈ Icc (16.1923 : ℝ) 16.1991,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.48697 : ℝ) ≤ basePrunedS 6 16.1923)
    (GamS_le (θ := 0.05416) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.1991 ≤ 0.0749203) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.1991, 16.2062]`. -/
theorem shapeSaving_S23_cell_157 : ∀ c ∈ Icc (16.1991 : ℝ) 16.2062,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.49328 : ℝ) ≤ basePrunedS 6 16.1991)
    (GamS_le (θ := 0.054156) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.2062 ≤ 0.074951) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.2062, 16.2132]`. -/
theorem shapeSaving_S23_cell_158 : ∀ c ∈ Icc (16.2062 : ℝ) 16.2132,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.49986 : ℝ) ≤ basePrunedS 6 16.2062)
    (GamS_le (θ := 0.054153) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.2132 ≤ 0.0749826) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.2132, 16.2205]`. -/
theorem shapeSaving_S23_cell_159 : ∀ c ∈ Icc (16.2132 : ℝ) 16.2205,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.50636 : ℝ) ≤ basePrunedS 6 16.2132)
    (GamS_le (θ := 0.054149) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.2205 ≤ 0.0750143) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.2205, 16.2277]`. -/
theorem shapeSaving_S23_cell_160 : ∀ c ∈ Icc (16.2205 : ℝ) 16.2277,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.51313 : ℝ) ≤ basePrunedS 6 16.2205)
    (GamS_le (θ := 0.054146) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.2277 ≤ 0.0750469) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.2277, 16.2351]`. -/
theorem shapeSaving_S23_cell_161 : ∀ c ∈ Icc (16.2277 : ℝ) 16.2351,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.51981 : ℝ) ≤ basePrunedS 6 16.2277)
    (GamS_le (θ := 0.054142) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.2351 ≤ 0.075079) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.2351, 16.2427]`. -/
theorem shapeSaving_S23_cell_162 : ∀ c ∈ Icc (16.2351 : ℝ) 16.2427,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.52667 : ℝ) ≤ basePrunedS 6 16.2351)
    (GamS_le (θ := 0.054138) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.2427 ≤ 0.0751122) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.2427, 16.2502]`. -/
theorem shapeSaving_S23_cell_163 : ∀ c ∈ Icc (16.2427 : ℝ) 16.2502,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.53372 : ℝ) ≤ basePrunedS 6 16.2427)
    (GamS_le (θ := 0.054135) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.2502 ≤ 0.0751463) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.2502, 16.258]`. -/
theorem shapeSaving_S23_cell_164 : ∀ c ∈ Icc (16.2502 : ℝ) 16.258,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.54068 : ℝ) ≤ basePrunedS 6 16.2502)
    (GamS_le (θ := 0.054131) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.258 ≤ 0.0751804) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.258, 16.2659]`. -/
theorem shapeSaving_S23_cell_165 : ∀ c ∈ Icc (16.258 : ℝ) 16.2659,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.54792 : ℝ) ≤ basePrunedS 6 16.258)
    (GamS_le (θ := 0.054127) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.2659 ≤ 0.075215) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.2659, 16.274]`. -/
theorem shapeSaving_S23_cell_166 : ∀ c ∈ Icc (16.2659 : ℝ) 16.274,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.55524 : ℝ) ≤ basePrunedS 6 16.2659)
    (GamS_le (θ := 0.054123) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.274 ≤ 0.0752506) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.274, 16.2822]`. -/
theorem shapeSaving_S23_cell_167 : ∀ c ∈ Icc (16.274 : ℝ) 16.2822,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.56276 : ℝ) ≤ basePrunedS 6 16.274)
    (GamS_le (θ := 0.054119) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.2822 ≤ 0.0752867) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.2822, 16.2906]`. -/
theorem shapeSaving_S23_cell_168 : ∀ c ∈ Icc (16.2822 : ℝ) 16.2906,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.57036 : ℝ) ≤ basePrunedS 6 16.2822)
    (GamS_le (θ := 0.054115) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.2906 ≤ 0.0753238) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.2906, 16.2991]`. -/
theorem shapeSaving_S23_cell_169 : ∀ c ∈ Icc (16.2906 : ℝ) 16.2991,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.57815 : ℝ) ≤ basePrunedS 6 16.2906)
    (GamS_le (θ := 0.054111) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.2991 ≤ 0.0753614) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.2991, 16.308]`. -/
theorem shapeSaving_S23_cell_170 : ∀ c ∈ Icc (16.2991 : ℝ) 16.308,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.58604 : ℝ) ≤ basePrunedS 6 16.2991)
    (GamS_le (θ := 0.054106) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.308 ≤ 0.0753995) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.308, 16.317]`. -/
theorem shapeSaving_S23_cell_171 : ∀ c ∈ Icc (16.308 : ℝ) 16.317,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.59429 : ℝ) ≤ basePrunedS 6 16.308)
    (GamS_le (θ := 0.054102) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.317 ≤ 0.0754396) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.317, 16.3263]`. -/
theorem shapeSaving_S23_cell_172 : ∀ c ∈ Icc (16.317 : ℝ) 16.3263,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.60264 : ℝ) ≤ basePrunedS 6 16.317)
    (GamS_le (θ := 0.054097) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.3263 ≤ 0.0754797) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.3263, 16.3357]`. -/
theorem shapeSaving_S23_cell_173 : ∀ c ∈ Icc (16.3263 : ℝ) 16.3357,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.61127 : ℝ) ≤ basePrunedS 6 16.3263)
    (GamS_le (θ := 0.054093) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.3357 ≤ 0.0755217) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.3357, 16.3454]`. -/
theorem shapeSaving_S23_cell_174 : ∀ c ∈ Icc (16.3357 : ℝ) 16.3454,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.61999 : ℝ) ≤ basePrunedS 6 16.3357)
    (GamS_le (θ := 0.054088) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.3454 ≤ 0.0755638) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.3454, 16.355]`. -/
theorem shapeSaving_S23_cell_175 : ∀ c ∈ Icc (16.3454 : ℝ) 16.355,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.62898 : ℝ) ≤ basePrunedS 6 16.3454)
    (GamS_le (θ := 0.054083) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.355 ≤ 0.0756053) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.355, 16.365]`. -/
theorem shapeSaving_S23_cell_176 : ∀ c ∈ Icc (16.355 : ℝ) 16.365,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.63789 : ℝ) ≤ basePrunedS 6 16.355)
    (GamS_le (θ := 0.054078) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.365 ≤ 0.075649) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.365, 16.375]`. -/
theorem shapeSaving_S23_cell_177 : ∀ c ∈ Icc (16.365 : ℝ) 16.375,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.64716 : ℝ) ≤ basePrunedS 6 16.365)
    (GamS_le (θ := 0.054074) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.375 ≤ 0.0756937) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.375, 16.385]`. -/
theorem shapeSaving_S23_cell_178 : ∀ c ∈ Icc (16.375 : ℝ) 16.385,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.65643 : ℝ) ≤ basePrunedS 6 16.375)
    (GamS_le (θ := 0.054069) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.385 ≤ 0.0757371) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.385, 16.396]`. -/
theorem shapeSaving_S23_cell_179 : ∀ c ∈ Icc (16.385 : ℝ) 16.396,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.66571 : ℝ) ≤ basePrunedS 6 16.385)
    (GamS_le (θ := 0.054063) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.396 ≤ 0.0757841) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.396, 16.407]`. -/
theorem shapeSaving_S23_cell_180 : ∀ c ∈ Icc (16.396 : ℝ) 16.407,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.67591 : ℝ) ≤ basePrunedS 6 16.396)
    (GamS_le (θ := 0.054058) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.407 ≤ 0.0758324) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.407, 16.418]`. -/
theorem shapeSaving_S23_cell_181 : ∀ c ∈ Icc (16.407 : ℝ) 16.418,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.68611 : ℝ) ≤ basePrunedS 6 16.407)
    (GamS_le (θ := 0.054053) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.418 ≤ 0.0758808) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.418, 16.43]`. -/
theorem shapeSaving_S23_cell_182 : ∀ c ∈ Icc (16.418 : ℝ) 16.43,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.69631 : ℝ) ≤ basePrunedS 6 16.418)
    (GamS_le (θ := 0.054047) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.43 ≤ 0.0759327) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.43, 16.442]`. -/
theorem shapeSaving_S23_cell_183 : ∀ c ∈ Icc (16.43 : ℝ) 16.442,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.70744 : ℝ) ≤ basePrunedS 6 16.43)
    (GamS_le (θ := 0.054041) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.442 ≤ 0.0759845) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.442, 16.454]`. -/
theorem shapeSaving_S23_cell_184 : ∀ c ∈ Icc (16.442 : ℝ) 16.454,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.71856 : ℝ) ≤ basePrunedS 6 16.442)
    (GamS_le (θ := 0.054035) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.454 ≤ 0.0760362) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.454, 16.467]`. -/
theorem shapeSaving_S23_cell_185 : ∀ c ∈ Icc (16.454 : ℝ) 16.467,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.72969 : ℝ) ≤ basePrunedS 6 16.454)
    (GamS_le (θ := 0.054029) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.467 ≤ 0.076093) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.467, 16.48]`. -/
theorem shapeSaving_S23_cell_186 : ∀ c ∈ Icc (16.467 : ℝ) 16.48,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.74174 : ℝ) ≤ basePrunedS 6 16.467)
    (GamS_le (θ := 0.054023) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.48 ≤ 0.0761496) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.48, 16.494]`. -/
theorem shapeSaving_S23_cell_187 : ∀ c ∈ Icc (16.48 : ℝ) 16.494,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.7538 : ℝ) ≤ basePrunedS 6 16.48)
    (GamS_le (θ := 0.054016) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.494 ≤ 0.0762098) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.494, 16.508]`. -/
theorem shapeSaving_S23_cell_188 : ∀ c ∈ Icc (16.494 : ℝ) 16.508,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.76678 : ℝ) ≤ basePrunedS 6 16.494)
    (GamS_le (θ := 0.054009) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.508 ≤ 0.0762698) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.508, 16.523]`. -/
theorem shapeSaving_S23_cell_189 : ∀ c ∈ Icc (16.508 : ℝ) 16.523,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.77976 : ℝ) ≤ basePrunedS 6 16.508)
    (GamS_le (θ := 0.054002) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.523 ≤ 0.0763348) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.523, 16.539]`. -/
theorem shapeSaving_S23_cell_190 : ∀ c ∈ Icc (16.523 : ℝ) 16.539,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.79366 : ℝ) ≤ basePrunedS 6 16.523)
    (GamS_le (θ := 0.053994) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.539 ≤ 0.0764033) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.539, 16.555]`. -/
theorem shapeSaving_S23_cell_191 : ∀ c ∈ Icc (16.539 : ℝ) 16.555,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.8085 : ℝ) ≤ basePrunedS 6 16.539)
    (GamS_le (θ := 0.053986) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.555 ≤ 0.0764727) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.555, 16.572]`. -/
theorem shapeSaving_S23_cell_192 : ∀ c ∈ Icc (16.555 : ℝ) 16.572,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.82333 : ℝ) ≤ basePrunedS 6 16.555)
    (GamS_le (θ := 0.053978) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.572 ≤ 0.0765449) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.572, 16.59]`. -/
theorem shapeSaving_S23_cell_193 : ∀ c ∈ Icc (16.572 : ℝ) 16.59,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.83909 : ℝ) ≤ basePrunedS 6 16.572)
    (GamS_le (θ := 0.05397) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.59 ≤ 0.076623) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.59, 16.609]`. -/
theorem shapeSaving_S23_cell_194 : ∀ c ∈ Icc (16.59 : ℝ) 16.609,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.85578 : ℝ) ≤ basePrunedS 6 16.59)
    (GamS_le (θ := 0.053961) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.609 ≤ 0.0767045) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.609, 16.629]`. -/
theorem shapeSaving_S23_cell_195 : ∀ c ∈ Icc (16.609 : ℝ) 16.629,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.87339 : ℝ) ≤ basePrunedS 6 16.609)
    (GamS_le (θ := 0.053951) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.629 ≤ 0.0767894) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.629, 16.65]`. -/
theorem shapeSaving_S23_cell_196 : ∀ c ∈ Icc (16.629 : ℝ) 16.65,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.89193 : ℝ) ≤ basePrunedS 6 16.629)
    (GamS_le (θ := 0.053941) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.65 ≤ 0.076879) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.65, 16.672]`. -/
theorem shapeSaving_S23_cell_197 : ∀ c ∈ Icc (16.65 : ℝ) 16.672,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.91139 : ℝ) ≤ basePrunedS 6 16.65)
    (GamS_le (θ := 0.053931) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.672 ≤ 0.0769734) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.672, 16.695]`. -/
theorem shapeSaving_S23_cell_198 : ∀ c ∈ Icc (16.672 : ℝ) 16.695,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.93178 : ℝ) ≤ basePrunedS 6 16.672)
    (GamS_le (θ := 0.05392) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.695 ≤ 0.0770711) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c ∈ [16.695, 16.7]`. -/
theorem shapeSaving_S23_cell_199 : ∀ c ∈ Icc (16.695 : ℝ) 16.7,
    shapeSaving 6 2 c < 0.001671 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (15.9531 : ℝ) ≤ basePrunedS 6 16.695)
    (GamS_le (θ := 0.053917) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.7 ≤ 0.0770915) hc

/-- `shapeSaving 6 2 c < 0.001671` for `c` in `[16.1724, 16.7]`: cells 153 to 199. -/
theorem shapeSaving_S23_block_4 : ∀ c ∈ Icc (16.1724 : ℝ) 16.7,
    shapeSaving 6 2 c < 0.001671 := by
  have h := shapeSaving_S23_cell_153
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_154
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_155
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_156
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_157
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_158
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_159
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_160
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_161
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_162
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_163
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_164
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_165
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_166
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_167
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_168
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_169
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_170
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_171
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_172
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_173
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_174
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_175
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_176
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_177
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_178
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_179
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_180
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_181
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_182
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_183
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_184
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_185
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_186
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_187
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_188
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_189
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_190
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_191
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_192
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_193
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_194
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_195
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_196
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_197
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_198
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_199
  exact h

end ImprovedExponents
