module

public import ImprovedExponents.Optimum.Shapes.NumLog

@[expose] public section

/-!
# The saving with the shape `(5, 5)` on `[56.867, 600]`: cells 178 to 216

This file is generated by `python3 -m search.certs`; do not edit it. Each lemma bounds
`shapeSaving 25 16 c` on one cell `[c₁, c₂]` by `F(A(c₁), Γ(c₂))`, with certified rational bounds
on `A(c₁)` and `Γ(c₂)`; the last lemma joins the cells.
-/

namespace ImprovedExponents

open Set

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [56.867, 56.918]`. -/
theorem shapeSaving_S55_cell_178 : ∀ c ∈ Icc (56.867 : ℝ) 56.918,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (92.4304 : ℝ) ≤ basePrunedS 25 56.867)
    (GamS_le (θ := 0.219703) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 56.918 ≤ 0.0733688) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [56.918, 56.973]`. -/
theorem shapeSaving_S55_cell_179 : ∀ c ∈ Icc (56.918 : ℝ) 56.973,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (92.51293 : ℝ) ≤ basePrunedS 25 56.918)
    (GamS_le (θ := 0.219673) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 56.973 ≤ 0.0734349) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [56.973, 57.032]`. -/
theorem shapeSaving_S55_cell_180 : ∀ c ∈ Icc (56.973 : ℝ) 57.032,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (92.60194 : ℝ) ≤ basePrunedS 25 56.973)
    (GamS_le (θ := 0.21964) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 57.032 ≤ 0.0735056) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [57.032, 57.095]`. -/
theorem shapeSaving_S55_cell_181 : ∀ c ∈ Icc (57.032 : ℝ) 57.095,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (92.69741 : ℝ) ≤ basePrunedS 25 57.032)
    (GamS_le (θ := 0.219605) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 57.095 ≤ 0.0735811) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [57.095, 57.163]`. -/
theorem shapeSaving_S55_cell_182 : ∀ c ∈ Icc (57.095 : ℝ) 57.163,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (92.79937 : ℝ) ≤ basePrunedS 25 57.095)
    (GamS_le (θ := 0.219567) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 57.163 ≤ 0.0736623) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [57.163, 57.236]`. -/
theorem shapeSaving_S55_cell_183 : ∀ c ∈ Icc (57.163 : ℝ) 57.236,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (92.90941 : ℝ) ≤ basePrunedS 25 57.163)
    (GamS_le (θ := 0.219527) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 57.236 ≤ 0.0737496) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [57.236, 57.314]`. -/
theorem shapeSaving_S55_cell_184 : ∀ c ∈ Icc (57.236 : ℝ) 57.314,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (93.02754 : ℝ) ≤ basePrunedS 25 57.236)
    (GamS_le (θ := 0.219484) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 57.314 ≤ 0.0738427) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [57.314, 57.399]`. -/
theorem shapeSaving_S55_cell_185 : ∀ c ∈ Icc (57.314 : ℝ) 57.399,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (93.15376 : ℝ) ≤ basePrunedS 25 57.314)
    (GamS_le (θ := 0.219437) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 57.399 ≤ 0.0739438) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [57.399, 57.491]`. -/
theorem shapeSaving_S55_cell_186 : ∀ c ∈ Icc (57.399 : ℝ) 57.491,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (93.29131 : ℝ) ≤ basePrunedS 25 57.399)
    (GamS_le (θ := 0.219386) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 57.491 ≤ 0.0740529) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [57.491, 57.59]`. -/
theorem shapeSaving_S55_cell_187 : ∀ c ∈ Icc (57.491 : ℝ) 57.59,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (93.44019 : ℝ) ≤ basePrunedS 25 57.491)
    (GamS_le (θ := 0.219332) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 57.59 ≤ 0.0741704) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [57.59, 57.69]`. -/
theorem shapeSaving_S55_cell_188 : ∀ c ∈ Icc (57.59 : ℝ) 57.69,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (93.60039 : ℝ) ≤ basePrunedS 25 57.59)
    (GamS_le (θ := 0.219277) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 57.69 ≤ 0.0742885) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [57.69, 57.8]`. -/
theorem shapeSaving_S55_cell_189 : ∀ c ∈ Icc (57.69 : ℝ) 57.8,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (93.76221 : ℝ) ≤ basePrunedS 25 57.69)
    (GamS_le (θ := 0.219217) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 57.8 ≤ 0.0744183) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [57.8, 57.92]`. -/
theorem shapeSaving_S55_cell_190 : ∀ c ∈ Icc (57.8 : ℝ) 57.92,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (93.94021 : ℝ) ≤ basePrunedS 25 57.8)
    (GamS_le (θ := 0.219152) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 57.92 ≤ 0.0745597) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [57.92, 58.05]`. -/
theorem shapeSaving_S55_cell_191 : ∀ c ∈ Icc (57.92 : ℝ) 58.05,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (94.13439 : ℝ) ≤ basePrunedS 25 57.92)
    (GamS_le (θ := 0.219081) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 58.05 ≤ 0.0747121) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [58.05, 58.2]`. -/
theorem shapeSaving_S55_cell_192 : ∀ c ∈ Icc (58.05 : ℝ) 58.2,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (94.34475 : ℝ) ≤ basePrunedS 25 58.05)
    (GamS_le (θ := 0.219) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 58.2 ≤ 0.0748877) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [58.2, 58.36]`. -/
theorem shapeSaving_S55_cell_193 : ∀ c ∈ Icc (58.2 : ℝ) 58.36,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (94.58746 : ℝ) ≤ basePrunedS 25 58.2)
    (GamS_le (θ := 0.218913) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 58.36 ≤ 0.075074) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [58.36, 58.54]`. -/
theorem shapeSaving_S55_cell_194 : ∀ c ∈ Icc (58.36 : ℝ) 58.54,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (94.84636 : ℝ) ≤ basePrunedS 25 58.36)
    (GamS_le (θ := 0.218817) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 58.54 ≤ 0.0752833) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [58.54, 58.74]`. -/
theorem shapeSaving_S55_cell_195 : ∀ c ∈ Icc (58.54 : ℝ) 58.74,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (95.13761 : ℝ) ≤ basePrunedS 25 58.54)
    (GamS_le (θ := 0.218709) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 58.74 ≤ 0.0755147) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [58.74, 58.96]`. -/
theorem shapeSaving_S55_cell_196 : ∀ c ∈ Icc (58.74 : ℝ) 58.96,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (95.46122 : ℝ) ≤ basePrunedS 25 58.74)
    (GamS_le (θ := 0.218592) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 58.96 ≤ 0.0757677) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [58.96, 59.21]`. -/
theorem shapeSaving_S55_cell_197 : ∀ c ∈ Icc (58.96 : ℝ) 59.21,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (95.81718 : ℝ) ≤ basePrunedS 25 58.96)
    (GamS_le (θ := 0.21846) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 59.21 ≤ 0.0760542) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [59.21, 59.49]`. -/
theorem shapeSaving_S55_cell_198 : ∀ c ∈ Icc (59.21 : ℝ) 59.49,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (96.22167 : ℝ) ≤ basePrunedS 25 59.21)
    (GamS_le (θ := 0.218312) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 59.49 ≤ 0.0763729) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [59.49, 59.81]`. -/
theorem shapeSaving_S55_cell_199 : ∀ c ∈ Icc (59.49 : ℝ) 59.81,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (96.67469 : ℝ) ≤ basePrunedS 25 59.49)
    (GamS_le (θ := 0.218145) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 59.81 ≤ 0.0767351) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [59.81, 60.17]`. -/
theorem shapeSaving_S55_cell_200 : ∀ c ∈ Icc (59.81 : ℝ) 60.17,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (97.19242 : ℝ) ≤ basePrunedS 25 59.81)
    (GamS_le (θ := 0.217958) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 60.17 ≤ 0.0771394) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [60.17, 60.59]`. -/
theorem shapeSaving_S55_cell_201 : ∀ c ∈ Icc (60.17 : ℝ) 60.59,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (97.77484 : ℝ) ≤ basePrunedS 25 60.17)
    (GamS_le (θ := 0.217741) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 60.59 ≤ 0.0776071) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [60.59, 61.08]`. -/
theorem shapeSaving_S55_cell_202 : ∀ c ∈ Icc (60.59 : ℝ) 61.08,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (98.45431 : ℝ) ≤ basePrunedS 25 60.59)
    (GamS_le (θ := 0.217492) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 61.08 ≤ 0.0781478) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [61.08, 61.66]`. -/
theorem shapeSaving_S55_cell_203 : ∀ c ∈ Icc (61.08 : ℝ) 61.66,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (99.247 : ℝ) ≤ basePrunedS 25 61.08)
    (GamS_le (θ := 0.217199) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 61.66 ≤ 0.0787801) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [61.66, 62.35]`. -/
theorem shapeSaving_S55_cell_204 : ∀ c ∈ Icc (61.66 : ℝ) 62.35,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (100.18524 : ℝ) ≤ basePrunedS 25 61.66)
    (GamS_le (θ := 0.216856) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 62.35 ≤ 0.0795229) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [62.35, 63.18]`. -/
theorem shapeSaving_S55_cell_205 : ∀ c ∈ Icc (62.35 : ℝ) 63.18,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (101.30136 : ℝ) ≤ basePrunedS 25 62.35)
    (GamS_le (θ := 0.21645) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 63.18 ≤ 0.0804024) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [63.18, 64.2]`. -/
theorem shapeSaving_S55_cell_206 : ∀ c ∈ Icc (63.18 : ℝ) 64.2,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (102.64386 : ℝ) ≤ basePrunedS 25 63.18)
    (GamS_le (θ := 0.215961) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 64.2 ≤ 0.0814633) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [64.2, 65.5]`. -/
theorem shapeSaving_S55_cell_207 : ∀ c ∈ Icc (64.2 : ℝ) 65.5,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (104.29355 : ℝ) ≤ basePrunedS 25 64.2)
    (GamS_le (θ := 0.215352) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 65.5 ≤ 0.0827843) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [65.5, 67.1]`. -/
theorem shapeSaving_S55_cell_208 : ∀ c ∈ Icc (65.5 : ℝ) 67.1,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (106.39593 : ℝ) ≤ basePrunedS 25 65.5)
    (GamS_le (θ := 0.214624) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 67.1 ≤ 0.0843647) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [67.1, 69.3]`. -/
theorem shapeSaving_S55_cell_209 : ∀ c ∈ Icc (67.1 : ℝ) 69.3,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (108.98319 : ℝ) ≤ basePrunedS 25 67.1)
    (GamS_le (θ := 0.213659) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 69.3 ≤ 0.0864603) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [69.3, 72.4]`. -/
theorem shapeSaving_S55_cell_210 : ∀ c ∈ Icc (69.3 : ℝ) 72.4,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (112.5402 : ℝ) ≤ basePrunedS 25 69.3)
    (GamS_le (θ := 0.212367) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 72.4 ≤ 0.0892737) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [72.4, 77.1]`. -/
theorem shapeSaving_S55_cell_211 : ∀ c ∈ Icc (72.4 : ℝ) 77.1,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (117.55149 : ℝ) ≤ basePrunedS 25 72.4)
    (GamS_le (θ := 0.21054) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 77.1 ≤ 0.0932577) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [77.1, 85]`. -/
theorem shapeSaving_S55_cell_212 : ∀ c ∈ Icc (77.1 : ℝ) 85,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (125.14751 : ℝ) ≤ basePrunedS 25 77.1)
    (GamS_le (θ := 0.207776) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 85 ≤ 0.0993034) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [85, 100]`. -/
theorem shapeSaving_S55_cell_213 : ∀ c ∈ Icc (85 : ℝ) 100,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (137.91115 : ℝ) ≤ basePrunedS 25 85)
    (GamS_le (θ := 0.203349) (gammaXS_le 7 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 100 ≤ 0.1090339) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [100, 141]`. -/
theorem shapeSaving_S55_cell_214 : ∀ c ∈ Icc (100 : ℝ) 141,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 7 5 : (162.13442 : ℝ) ≤ basePrunedS 25 100)
    (GamS_le (θ := 0.194652) (gammaXS_le 7 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 141 ≤ 0.1283223) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [141, 420]`. -/
theorem shapeSaving_S55_cell_215 : ∀ c ∈ Icc (141 : ℝ) 420,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 7 5 : (228.2939 : ℝ) ≤ basePrunedS 25 141)
    (GamS_le (θ := 0.171736) (gammaXS_le 9 5 4)
      (gammaQS_le (-3) 5 4) : GamS 25 16 420 ≤ 0.1802756) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [420, 600]`. -/
theorem shapeSaving_S55_cell_216 : ∀ c ∈ Icc (420 : ℝ) 600,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 9 5 : (677.87399 : ℝ) ≤ basePrunedS 25 420)
    (GamS_le (θ := 0.165462) (gammaXS_le 9 5 4)
      (gammaQS_le (-3) 5 4) : GamS 25 16 600 ≤ 0.1948026) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c` in `[56.867, 600]`: cells 178 to 216. -/
theorem shapeSaving_S55_block_5 : ∀ c ∈ Icc (56.867 : ℝ) 600,
    shapeSaving 25 16 c < 0.001098 := by
  have h := shapeSaving_S55_cell_178
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_179
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_180
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_181
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_182
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_183
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_184
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_185
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_186
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_187
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_188
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_189
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_190
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_191
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_192
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_193
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_194
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_195
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_196
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_197
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_198
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_199
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_200
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_201
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_202
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_203
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_204
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_205
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_206
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_207
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_208
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_209
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_210
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_211
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_212
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_213
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_214
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_215
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_216
  exact h

end ImprovedExponents
