module

public import ImprovedExponents.Optimum.Shapes.NumLog

@[expose] public section

/-!
# The saving with the shape `(2, 4)` on `[20.852, 200]`: cells 184 to 232

This file is generated by `python3 -m search.certs`; do not edit it. Each lemma bounds
`shapeSaving 8 3 c` on one cell `[c₁, c₂]` by `F(A(c₁), Γ(c₂))`, with certified rational bounds
on `A(c₁)` and `Γ(c₂)`; the last lemma joins the cells.
-/

namespace ImprovedExponents

open Set

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [20.852, 20.864]`. -/
theorem shapeSaving_S24_cell_184 : ∀ c ∈ Icc (20.852 : ℝ) 20.864,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.64707 : ℝ) ≤ basePrunedS 8 20.852)
    (GamS_le (θ := 0.08902) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.864 ≤ 0.0775937) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [20.864, 20.876]`. -/
theorem shapeSaving_S24_cell_185 : ∀ c ∈ Icc (20.864 : ℝ) 20.876,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.65984 : ℝ) ≤ basePrunedS 8 20.864)
    (GamS_le (θ := 0.089012) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.876 ≤ 0.0776352) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [20.876, 20.889]`. -/
theorem shapeSaving_S24_cell_186 : ∀ c ∈ Icc (20.876 : ℝ) 20.889,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.67261 : ℝ) ≤ basePrunedS 8 20.876)
    (GamS_le (θ := 0.089003) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.889 ≤ 0.0776798) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [20.889, 20.903]`. -/
theorem shapeSaving_S24_cell_187 : ∀ c ∈ Icc (20.889 : ℝ) 20.903,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.68645 : ℝ) ≤ basePrunedS 8 20.889)
    (GamS_le (θ := 0.088994) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.903 ≤ 0.0777284) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [20.903, 20.917]`. -/
theorem shapeSaving_S24_cell_188 : ∀ c ∈ Icc (20.903 : ℝ) 20.917,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.70135 : ℝ) ≤ basePrunedS 8 20.903)
    (GamS_le (θ := 0.088985) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.917 ≤ 0.077777) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [20.917, 20.932]`. -/
theorem shapeSaving_S24_cell_189 : ∀ c ∈ Icc (20.917 : ℝ) 20.932,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.71625 : ℝ) ≤ basePrunedS 8 20.917)
    (GamS_le (θ := 0.088975) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.932 ≤ 0.0778294) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [20.932, 20.948]`. -/
theorem shapeSaving_S24_cell_190 : ∀ c ∈ Icc (20.932 : ℝ) 20.948,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.73221 : ℝ) ≤ basePrunedS 8 20.932)
    (GamS_le (θ := 0.088965) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.948 ≤ 0.0778843) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [20.948, 20.965]`. -/
theorem shapeSaving_S24_cell_191 : ∀ c ∈ Icc (20.948 : ℝ) 20.965,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.74924 : ℝ) ≤ basePrunedS 8 20.948)
    (GamS_le (θ := 0.088954) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.965 ≤ 0.077943) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [20.965, 20.983]`. -/
theorem shapeSaving_S24_cell_192 : ∀ c ∈ Icc (20.965 : ℝ) 20.983,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.76733 : ℝ) ≤ basePrunedS 8 20.965)
    (GamS_le (θ := 0.088943) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.983 ≤ 0.0780056) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [20.983, 21.002]`. -/
theorem shapeSaving_S24_cell_193 : ∀ c ∈ Icc (20.983 : ℝ) 21.002,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.78648 : ℝ) ≤ basePrunedS 8 20.983)
    (GamS_le (θ := 0.08893) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 21.002 ≤ 0.0780704) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [21.002, 21.022]`. -/
theorem shapeSaving_S24_cell_194 : ∀ c ∈ Icc (21.002 : ℝ) 21.022,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.8067 : ℝ) ≤ basePrunedS 8 21.002)
    (GamS_le (θ := 0.088917) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 21.022 ≤ 0.0781395) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [21.022, 21.043]`. -/
theorem shapeSaving_S24_cell_195 : ∀ c ∈ Icc (21.022 : ℝ) 21.043,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.82798 : ℝ) ≤ basePrunedS 8 21.022)
    (GamS_le (θ := 0.088904) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 21.043 ≤ 0.0782118) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [21.043, 21.066]`. -/
theorem shapeSaving_S24_cell_196 : ∀ c ∈ Icc (21.043 : ℝ) 21.066,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.85033 : ℝ) ≤ basePrunedS 8 21.043)
    (GamS_le (θ := 0.088889) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 21.066 ≤ 0.0782905) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [21.066, 21.09]`. -/
theorem shapeSaving_S24_cell_197 : ∀ c ∈ Icc (21.066 : ℝ) 21.09,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.8748 : ℝ) ≤ basePrunedS 8 21.066)
    (GamS_le (θ := 0.088874) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 21.09 ≤ 0.0783731) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [21.09, 21.116]`. -/
theorem shapeSaving_S24_cell_198 : ∀ c ∈ Icc (21.09 : ℝ) 21.116,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.90034 : ℝ) ≤ basePrunedS 8 21.09)
    (GamS_le (θ := 0.088857) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 21.116 ≤ 0.0784617) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [21.116, 21.143]`. -/
theorem shapeSaving_S24_cell_199 : ∀ c ∈ Icc (21.116 : ℝ) 21.143,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.928 : ℝ) ≤ basePrunedS 8 21.116)
    (GamS_le (θ := 0.08884) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 21.143 ≤ 0.0785541) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [21.143, 21.172]`. -/
theorem shapeSaving_S24_cell_200 : ∀ c ∈ Icc (21.143 : ℝ) 21.172,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.95673 : ℝ) ≤ basePrunedS 8 21.143)
    (GamS_le (θ := 0.088821) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 21.172 ≤ 0.078653) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [21.172, 21.203]`. -/
theorem shapeSaving_S24_cell_201 : ∀ c ∈ Icc (21.172 : ℝ) 21.203,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.98758 : ℝ) ≤ basePrunedS 8 21.172)
    (GamS_le (θ := 0.088802) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 21.203 ≤ 0.0787587) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [21.203, 21.237]`. -/
theorem shapeSaving_S24_cell_202 : ∀ c ∈ Icc (21.203 : ℝ) 21.237,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (23.02056 : ℝ) ≤ basePrunedS 8 21.203)
    (GamS_le (θ := 0.08878) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 21.237 ≤ 0.0788738) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [21.237, 21.273]`. -/
theorem shapeSaving_S24_cell_203 : ∀ c ∈ Icc (21.237 : ℝ) 21.273,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (23.05674 : ℝ) ≤ basePrunedS 8 21.237)
    (GamS_le (θ := 0.088757) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 21.273 ≤ 0.0789956) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [21.273, 21.312]`. -/
theorem shapeSaving_S24_cell_204 : ∀ c ∈ Icc (21.273 : ℝ) 21.312,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (23.09503 : ℝ) ≤ basePrunedS 8 21.273)
    (GamS_le (θ := 0.088733) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 21.312 ≤ 0.0791281) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [21.312, 21.354]`. -/
theorem shapeSaving_S24_cell_205 : ∀ c ∈ Icc (21.312 : ℝ) 21.354,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (23.13652 : ℝ) ≤ basePrunedS 8 21.312)
    (GamS_le (θ := 0.088706) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 21.354 ≤ 0.0792692) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [21.354, 21.4]`. -/
theorem shapeSaving_S24_cell_206 : ∀ c ∈ Icc (21.354 : ℝ) 21.4,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (23.1812 : ℝ) ≤ basePrunedS 8 21.354)
    (GamS_le (θ := 0.088677) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 21.4 ≤ 0.0794238) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [21.4, 21.45]`. -/
theorem shapeSaving_S24_cell_207 : ∀ c ∈ Icc (21.4 : ℝ) 21.45,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (23.23013 : ℝ) ≤ basePrunedS 8 21.4)
    (GamS_le (θ := 0.088646) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 21.45 ≤ 0.0795917) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [21.45, 21.504]`. -/
theorem shapeSaving_S24_cell_208 : ∀ c ∈ Icc (21.45 : ℝ) 21.504,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (23.28331 : ℝ) ≤ basePrunedS 8 21.45)
    (GamS_le (θ := 0.088612) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 21.504 ≤ 0.0797719) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [21.504, 21.563]`. -/
theorem shapeSaving_S24_cell_209 : ∀ c ∈ Icc (21.504 : ℝ) 21.563,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (23.34074 : ℝ) ≤ basePrunedS 8 21.504)
    (GamS_le (θ := 0.088576) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 21.563 ≤ 0.0799691) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [21.563, 21.628]`. -/
theorem shapeSaving_S24_cell_210 : ∀ c ∈ Icc (21.563 : ℝ) 21.628,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (23.40348 : ℝ) ≤ basePrunedS 8 21.563)
    (GamS_le (θ := 0.088535) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 21.628 ≤ 0.080184) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [21.628, 21.7]`. -/
theorem shapeSaving_S24_cell_211 : ∀ c ∈ Icc (21.628 : ℝ) 21.7,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (23.47261 : ℝ) ≤ basePrunedS 8 21.628)
    (GamS_le (θ := 0.088491) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 21.7 ≤ 0.0804223) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [21.7, 21.779]`. -/
theorem shapeSaving_S24_cell_212 : ∀ c ∈ Icc (21.7 : ℝ) 21.779,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (23.54917 : ℝ) ≤ basePrunedS 8 21.7)
    (GamS_le (θ := 0.088442) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 21.779 ≤ 0.0806815) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [21.779, 21.868]`. -/
theorem shapeSaving_S24_cell_213 : ∀ c ∈ Icc (21.779 : ℝ) 21.868,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (23.63317 : ℝ) ≤ basePrunedS 8 21.779)
    (GamS_le (θ := 0.088388) (gammaXS_le 4 3 2)
      (gammaQS_le (-4) 3 2) : GamS 8 3 21.868 ≤ 0.080973) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [21.868, 21.967]`. -/
theorem shapeSaving_S24_cell_214 : ∀ c ∈ Icc (21.868 : ℝ) 21.967,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (23.72779 : ℝ) ≤ basePrunedS 8 21.868)
    (GamS_le (θ := 0.088328) (gammaXS_le 4 3 2)
      (gammaQS_le (-4) 3 2) : GamS 8 3 21.967 ≤ 0.0812951) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [21.967, 22.07]`. -/
theorem shapeSaving_S24_cell_215 : ∀ c ∈ Icc (21.967 : ℝ) 22.07,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (23.83303 : ℝ) ≤ basePrunedS 8 21.967)
    (GamS_le (θ := 0.088266) (gammaXS_le 4 3 2)
      (gammaQS_le (-4) 3 2) : GamS 8 3 22.07 ≤ 0.0816282) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [22.07, 22.19]`. -/
theorem shapeSaving_S24_cell_216 : ∀ c ∈ Icc (22.07 : ℝ) 22.19,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (23.94252 : ℝ) ≤ basePrunedS 8 22.07)
    (GamS_le (θ := 0.088194) (gammaXS_le 4 3 2)
      (gammaQS_le (-4) 3 2) : GamS 8 3 22.19 ≤ 0.0820133) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [22.19, 22.33]`. -/
theorem shapeSaving_S24_cell_217 : ∀ c ∈ Icc (22.19 : ℝ) 22.33,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (24.07006 : ℝ) ≤ basePrunedS 8 22.19)
    (GamS_le (θ := 0.088111) (gammaXS_le 4 3 2)
      (gammaQS_le (-4) 3 2) : GamS 8 3 22.33 ≤ 0.0824595) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [22.33, 22.49]`. -/
theorem shapeSaving_S24_cell_218 : ∀ c ∈ Icc (22.33 : ℝ) 22.49,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (24.21884 : ℝ) ≤ basePrunedS 8 22.33)
    (GamS_le (θ := 0.088016) (gammaXS_le 4 3 2)
      (gammaQS_le (-4) 3 2) : GamS 8 3 22.49 ≤ 0.082964) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [22.49, 22.68]`. -/
theorem shapeSaving_S24_cell_219 : ∀ c ∈ Icc (22.49 : ℝ) 22.68,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (24.38884 : ℝ) ≤ basePrunedS 8 22.49)
    (GamS_le (θ := 0.087906) (gammaXS_le 4 3 2)
      (gammaQS_le (-4) 3 2) : GamS 8 3 22.68 ≤ 0.0835582) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [22.68, 22.9]`. -/
theorem shapeSaving_S24_cell_220 : ∀ c ∈ Icc (22.68 : ℝ) 22.9,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (24.59069 : ℝ) ≤ basePrunedS 8 22.68)
    (GamS_le (θ := 0.087779) (gammaXS_le 4 3 2)
      (gammaQS_le (-4) 3 2) : GamS 8 3 22.9 ≤ 0.084237) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [22.9, 23.16]`. -/
theorem shapeSaving_S24_cell_221 : ∀ c ∈ Icc (22.9 : ℝ) 23.16,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (24.82437 : ℝ) ≤ basePrunedS 8 22.9)
    (GamS_le (θ := 0.087632) (gammaXS_le 4 3 2)
      (gammaQS_le (-4) 3 2) : GamS 8 3 23.16 ≤ 0.085029) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [23.16, 23.48]`. -/
theorem shapeSaving_S24_cell_222 : ∀ c ∈ Icc (23.16 : ℝ) 23.48,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (25.10047 : ℝ) ≤ basePrunedS 8 23.16)
    (GamS_le (θ := 0.087453) (gammaXS_le 4 3 2)
      (gammaQS_le (-4) 3 2) : GamS 8 3 23.48 ≤ 0.0859865) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [23.48, 23.88]`. -/
theorem shapeSaving_S24_cell_223 : ∀ c ∈ Icc (23.48 : ℝ) 23.88,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (25.44019 : ℝ) ≤ basePrunedS 8 23.48)
    (GamS_le (θ := 0.087235) (gammaXS_le 5 3 2)
      (gammaQS_le (-4) 3 2) : GamS 8 3 23.88 ≤ 0.0871603) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [23.88, 24.39]`. -/
theorem shapeSaving_S24_cell_224 : ∀ c ∈ Icc (23.88 : ℝ) 24.39,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (25.86471 : ℝ) ≤ basePrunedS 8 23.88)
    (GamS_le (θ := 0.086963) (gammaXS_le 5 3 2)
      (gammaQS_le (-4) 3 2) : GamS 8 3 24.39 ≤ 0.0886184) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [24.39, 25.05]`. -/
theorem shapeSaving_S24_cell_225 : ∀ c ∈ Icc (24.39 : ℝ) 25.05,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (26.40576 : ℝ) ≤ basePrunedS 8 24.39)
    (GamS_le (θ := 0.086623) (gammaXS_le 5 3 2)
      (gammaQS_le (-4) 3 2) : GamS 8 3 25.05 ≤ 0.0904471) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [25.05, 25.96]`. -/
theorem shapeSaving_S24_cell_226 : ∀ c ∈ Icc (25.05 : ℝ) 25.96,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (27.1056 : ℝ) ≤ basePrunedS 8 25.05)
    (GamS_le (θ := 0.086174) (gammaXS_le 5 3 2)
      (gammaQS_le (-4) 3 2) : GamS 8 3 25.96 ≤ 0.092867) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [25.96, 27.2]`. -/
theorem shapeSaving_S24_cell_227 : ∀ c ∈ Icc (25.96 : ℝ) 27.2,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.06995 : ℝ) ≤ basePrunedS 8 25.96)
    (GamS_le (θ := 0.085595) (gammaXS_le 5 3 2)
      (gammaQS_le (-4) 3 2) : GamS 8 3 27.2 ≤ 0.0959894) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [27.2, 29.2]`. -/
theorem shapeSaving_S24_cell_228 : ∀ c ∈ Icc (27.2 : ℝ) 29.2,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.38298 : ℝ) ≤ basePrunedS 8 27.2)
    (GamS_le (θ := 0.084733) (gammaXS_le 5 3 2)
      (gammaQS_le (-4) 3 2) : GamS 8 3 29.2 ≤ 0.100651) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [29.2, 32.7]`. -/
theorem shapeSaving_S24_cell_229 : ∀ c ∈ Icc (29.2 : ℝ) 32.7,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (31.49854 : ℝ) ≤ basePrunedS 8 29.2)
    (GamS_le (θ := 0.083399) (gammaXS_le 5 3 2)
      (gammaQS_le (-4) 3 2) : GamS 8 3 32.7 ≤ 0.1078811) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [32.7, 40.2]`. -/
theorem shapeSaving_S24_cell_230 : ∀ c ∈ Icc (32.7 : ℝ) 40.2,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (35.19511 : ℝ) ≤ basePrunedS 8 32.7)
    (GamS_le (θ := 0.081092) (gammaXS_le 5 3 2)
      (gammaQS_le (-4) 3 2) : GamS 8 3 40.2 ≤ 0.12046) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [40.2, 65]`. -/
theorem shapeSaving_S24_cell_231 : ∀ c ∈ Icc (40.2 : ℝ) 65,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (43.09771 : ℝ) ≤ basePrunedS 8 40.2)
    (GamS_le (θ := 0.076258) (gammaXS_le 6 3 2)
      (gammaQS_le (-4) 3 2) : GamS 8 3 65 ≤ 0.1470984) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c ∈ [65, 200]`. -/
theorem shapeSaving_S24_cell_232 : ∀ c ∈ Icc (65 : ℝ) 200,
    shapeSaving 8 3 c < 0.001875 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 6 3 : (69.12545 : ℝ) ≤ basePrunedS 8 65)
    (GamS_le (θ := 0.067132) (gammaXS_le 8 3 2)
      (gammaQS_le (-4) 3 2) : GamS 8 3 200 ≤ 0.1984964) hc

/-- `shapeSaving 8 3 c < 0.001875` for `c` in `[20.852, 200]`: cells 184 to 232. -/
theorem shapeSaving_S24_block_5 : ∀ c ∈ Icc (20.852 : ℝ) 200,
    shapeSaving 8 3 c < 0.001875 := by
  have h := shapeSaving_S24_cell_184
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_185
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_186
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_187
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_188
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_189
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_190
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_191
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_192
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_193
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_194
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_195
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_196
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_197
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_198
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_199
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_200
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_201
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_202
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_203
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_204
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_205
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_206
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_207
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_208
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_209
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_210
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_211
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_212
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_213
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_214
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_215
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_216
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_217
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_218
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_219
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_220
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_221
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_222
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_223
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_224
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_225
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_226
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_227
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_228
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_229
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_230
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_231
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_232
  exact h

end ImprovedExponents
