module

public import ImprovedExponents.Optimum.Shapes.Cells_S45_1
public import ImprovedExponents.Optimum.Shapes.Cells_S45_2
public import ImprovedExponents.Optimum.Shapes.Cells_S45_3
public import ImprovedExponents.Optimum.Shapes.Cells_S45_4
public import ImprovedExponents.Optimum.Shapes.Cells_S45_5

@[expose] public section

/-!
# The saving with the shape `(4, 5)` on `(21, 500]`

This file is generated by `python3 -m search.certs`; do not edit it. It joins the
237 cells of the files `Cells_S45_1.lean` to `Cells_S45_5.lean` into three ranges:

* `shapeSaving_S45_lt_below`: `shapeSaving 20 12 c < 0.001323` for `21 < c ≤ 42.7`;
* `shapeSaving_S45_lt_window`: `shapeSaving 20 12 c < 0.001325` for `42.7 ≤ c ≤ 45.4`;
* `shapeSaving_S45_lt_above`: `shapeSaving 20 12 c < 0.001323` for `45.4 ≤ c ≤ 500`.

For a shape it also has the tail `shapeSaving_S45_lt_tail` (`c ≥ 500`) and the witness
`shapeSaving_S45_witness` at `c = 44`.
-/

namespace ImprovedExponents

open Set

/-- `shapeSaving 20 12 c < 0.001323` for `c` in `(21, 42.7]`. -/
theorem shapeSaving_S45_lt_below : ∀ c ∈ Ioc (21 : ℝ) 42.7,
    shapeSaving 20 12 c < 0.001323 := by
  have h := shapeSaving_S45_block_1
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S45_block_2
  exact h

/-- `shapeSaving 20 12 c < 0.001325` for `c` in `[42.7, 45.4]`. -/
theorem shapeSaving_S45_lt_window : ∀ c ∈ Icc (42.7 : ℝ) 45.4,
    shapeSaving 20 12 c < 0.001325 :=
  shapeSaving_S45_block_3

/-- `shapeSaving 20 12 c < 0.001323` for `c` in `[45.4, 500]`. -/
theorem shapeSaving_S45_lt_above : ∀ c ∈ Icc (45.4 : ℝ) 500,
    shapeSaving 20 12 c < 0.001323 := by
  have h := shapeSaving_S45_block_4
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_block_5
  exact h

/-- The tail: `shapeSaving 20 12 c < 0.001323` for `c ≥ 500`, because `Γ(c) < 2/3`. -/
theorem shapeSaving_S45_lt_tail {c : ℝ} (hc : 500 ≤ c) :
    shapeSaving 20 12 c < 0.001323 :=
  shapeSaving_lt_of_le 4 (le_basePrunedS 9 4 :
    (751.04199 : ℝ) ≤ basePrunedS 20 500) hc

/-- The witness: `0.001323 < shapeSaving 20 12 c` at `c = 44`. -/
theorem shapeSaving_S45_witness : (0.001323 : ℝ) < shapeSaving 20 12 44 :=
  lt_savingS 4 (basePrunedS_pos (by norm_num) (by norm_num))
    (basePrunedS_le 5 4 : basePrunedS 20 44 ≤ 66.79462)
    (le_GamS (θ := 0.202269) (le_gammaXS 5 4 4)
      (le_gammaQS (-2) 4 4) : (0.0713507 : ℝ) ≤ GamS 20 12 44)

end ImprovedExponents
