module

public import ImprovedExponents.Optimum.Shapes.NumLog

@[expose] public section

/-!
# The saving with the shape `(2, 5)` on `[23.4, 24.0482]`: cells 91 to 135

This file is generated by `python3 -m search.certs`; do not edit it. Each lemma bounds
`shapeSaving 10 4 c` on one cell `[c₁, c₂]` by `F(A(c₁), Γ(c₂))`, with certified rational bounds
on `A(c₁)` and `Γ(c₂)`; the last lemma joins the cells.
-/

namespace ImprovedExponents

open Set

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.4, 23.426]`. -/
theorem shapeSaving_S25_cell_91 : ∀ c ∈ Icc (23.4 : ℝ) 23.426,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (27.85448 : ℝ) ≤ basePrunedS 10 23.4)
    (GamS_le (θ := 0.1143) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.426 ≤ 0.0717021) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.426, 23.451]`. -/
theorem shapeSaving_S25_cell_92 : ∀ c ∈ Icc (23.426 : ℝ) 23.451,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (27.88498 : ℝ) ≤ basePrunedS 10 23.426)
    (GamS_le (θ := 0.114281) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.451 ≤ 0.0717811) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.451, 23.475]`. -/
theorem shapeSaving_S25_cell_93 : ∀ c ∈ Icc (23.451 : ℝ) 23.475,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (27.9143 : ℝ) ≤ basePrunedS 10 23.451)
    (GamS_le (θ := 0.114263) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.475 ≤ 0.0718566) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.475, 23.498]`. -/
theorem shapeSaving_S25_cell_94 : ∀ c ∈ Icc (23.475 : ℝ) 23.498,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (27.94246 : ℝ) ≤ basePrunedS 10 23.475)
    (GamS_le (θ := 0.114246) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.498 ≤ 0.0719292) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.498, 23.52]`. -/
theorem shapeSaving_S25_cell_95 : ∀ c ∈ Icc (23.498 : ℝ) 23.52,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (27.96944 : ℝ) ≤ basePrunedS 10 23.498)
    (GamS_le (θ := 0.114229) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.52 ≤ 0.0719987) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.52, 23.541]`. -/
theorem shapeSaving_S25_cell_96 : ∀ c ∈ Icc (23.52 : ℝ) 23.541,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (27.99524 : ℝ) ≤ basePrunedS 10 23.52)
    (GamS_le (θ := 0.114214) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.541 ≤ 0.0720645) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.541, 23.562]`. -/
theorem shapeSaving_S25_cell_97 : ∀ c ∈ Icc (23.541 : ℝ) 23.562,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.01988 : ℝ) ≤ basePrunedS 10 23.541)
    (GamS_le (θ := 0.114198) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.562 ≤ 0.0721302) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.562, 23.582]`. -/
theorem shapeSaving_S25_cell_98 : ∀ c ∈ Icc (23.562 : ℝ) 23.582,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.04451 : ℝ) ≤ basePrunedS 10 23.562)
    (GamS_le (θ := 0.114183) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.582 ≤ 0.0721928) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.582, 23.601]`. -/
theorem shapeSaving_S25_cell_99 : ∀ c ∈ Icc (23.582 : ℝ) 23.601,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.06797 : ℝ) ≤ basePrunedS 10 23.582)
    (GamS_le (θ := 0.114169) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.601 ≤ 0.0722524) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.601, 23.619]`. -/
theorem shapeSaving_S25_cell_100 : ∀ c ∈ Icc (23.601 : ℝ) 23.619,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.09026 : ℝ) ≤ basePrunedS 10 23.601)
    (GamS_le (θ := 0.114155) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.619 ≤ 0.0723083) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.619, 23.637]`. -/
theorem shapeSaving_S25_cell_101 : ∀ c ∈ Icc (23.619 : ℝ) 23.637,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.11137 : ℝ) ≤ basePrunedS 10 23.619)
    (GamS_le (θ := 0.114142) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.637 ≤ 0.0723648) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.637, 23.654]`. -/
theorem shapeSaving_S25_cell_102 : ∀ c ∈ Icc (23.637 : ℝ) 23.654,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.13248 : ℝ) ≤ basePrunedS 10 23.637)
    (GamS_le (θ := 0.114129) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.654 ≤ 0.0724176) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.654, 23.671]`. -/
theorem shapeSaving_S25_cell_103 : ∀ c ∈ Icc (23.654 : ℝ) 23.671,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.15242 : ℝ) ≤ basePrunedS 10 23.654)
    (GamS_le (θ := 0.114117) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.671 ≤ 0.072471) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.671, 23.687]`. -/
theorem shapeSaving_S25_cell_104 : ∀ c ∈ Icc (23.671 : ℝ) 23.687,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.17236 : ℝ) ≤ basePrunedS 10 23.671)
    (GamS_le (θ := 0.114105) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.687 ≤ 0.0725207) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.687, 23.703]`. -/
theorem shapeSaving_S25_cell_105 : ∀ c ∈ Icc (23.687 : ℝ) 23.703,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.19113 : ℝ) ≤ basePrunedS 10 23.687)
    (GamS_le (θ := 0.114093) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.703 ≤ 0.0725704) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.703, 23.718]`. -/
theorem shapeSaving_S25_cell_106 : ∀ c ∈ Icc (23.703 : ℝ) 23.718,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.20989 : ℝ) ≤ basePrunedS 10 23.703)
    (GamS_le (θ := 0.114082) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.718 ≤ 0.0726171) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.718, 23.733]`. -/
theorem shapeSaving_S25_cell_107 : ∀ c ∈ Icc (23.718 : ℝ) 23.733,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.22748 : ℝ) ≤ basePrunedS 10 23.718)
    (GamS_le (θ := 0.114071) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.733 ≤ 0.0726638) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.733, 23.748]`. -/
theorem shapeSaving_S25_cell_108 : ∀ c ∈ Icc (23.733 : ℝ) 23.748,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.24508 : ℝ) ≤ basePrunedS 10 23.733)
    (GamS_le (θ := 0.114059) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.748 ≤ 0.0727102) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.748, 23.762]`. -/
theorem shapeSaving_S25_cell_109 : ∀ c ∈ Icc (23.748 : ℝ) 23.762,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.26267 : ℝ) ≤ basePrunedS 10 23.748)
    (GamS_le (θ := 0.114049) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.762 ≤ 0.0727534) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.762, 23.776]`. -/
theorem shapeSaving_S25_cell_110 : ∀ c ∈ Icc (23.762 : ℝ) 23.776,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.27909 : ℝ) ≤ basePrunedS 10 23.762)
    (GamS_le (θ := 0.114039) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.776 ≤ 0.072797) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.776, 23.79]`. -/
theorem shapeSaving_S25_cell_111 : ∀ c ∈ Icc (23.776 : ℝ) 23.79,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.29551 : ℝ) ≤ basePrunedS 10 23.776)
    (GamS_le (θ := 0.114028) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.79 ≤ 0.07284) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.79, 23.803]`. -/
theorem shapeSaving_S25_cell_112 : ∀ c ∈ Icc (23.79 : ℝ) 23.803,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.31192 : ℝ) ≤ basePrunedS 10 23.79)
    (GamS_le (θ := 0.114019) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.803 ≤ 0.0728805) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.803, 23.816]`. -/
theorem shapeSaving_S25_cell_113 : ∀ c ∈ Icc (23.803 : ℝ) 23.816,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.32717 : ℝ) ≤ basePrunedS 10 23.803)
    (GamS_le (θ := 0.114009) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.816 ≤ 0.0729204) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.816, 23.829]`. -/
theorem shapeSaving_S25_cell_114 : ∀ c ∈ Icc (23.816 : ℝ) 23.829,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.34242 : ℝ) ≤ basePrunedS 10 23.816)
    (GamS_le (θ := 0.114) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.829 ≤ 0.0729609) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.829, 23.841]`. -/
theorem shapeSaving_S25_cell_115 : ∀ c ∈ Icc (23.829 : ℝ) 23.841,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.35766 : ℝ) ≤ basePrunedS 10 23.829)
    (GamS_le (θ := 0.113991) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.841 ≤ 0.0729979) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.841, 23.853]`. -/
theorem shapeSaving_S25_cell_116 : ∀ c ∈ Icc (23.841 : ℝ) 23.853,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.37173 : ℝ) ≤ basePrunedS 10 23.841)
    (GamS_le (θ := 0.113982) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.853 ≤ 0.0730347) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.853, 23.865]`. -/
theorem shapeSaving_S25_cell_117 : ∀ c ∈ Icc (23.853 : ℝ) 23.865,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.38581 : ℝ) ≤ basePrunedS 10 23.853)
    (GamS_le (θ := 0.113973) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.865 ≤ 0.0730716) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.865, 23.877]`. -/
theorem shapeSaving_S25_cell_118 : ∀ c ∈ Icc (23.865 : ℝ) 23.877,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.39988 : ℝ) ≤ basePrunedS 10 23.865)
    (GamS_le (θ := 0.113964) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.877 ≤ 0.0731085) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.877, 23.888]`. -/
theorem shapeSaving_S25_cell_119 : ∀ c ∈ Icc (23.877 : ℝ) 23.888,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.41395 : ℝ) ≤ basePrunedS 10 23.877)
    (GamS_le (θ := 0.113956) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.888 ≤ 0.0731424) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.888, 23.899]`. -/
theorem shapeSaving_S25_cell_120 : ∀ c ∈ Icc (23.888 : ℝ) 23.899,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.42685 : ℝ) ≤ basePrunedS 10 23.888)
    (GamS_le (θ := 0.113948) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.899 ≤ 0.0731763) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.899, 23.91]`. -/
theorem shapeSaving_S25_cell_121 : ∀ c ∈ Icc (23.899 : ℝ) 23.91,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.43975 : ℝ) ≤ basePrunedS 10 23.899)
    (GamS_le (θ := 0.11394) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.91 ≤ 0.0732101) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.91, 23.921]`. -/
theorem shapeSaving_S25_cell_122 : ∀ c ∈ Icc (23.91 : ℝ) 23.921,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.45265 : ℝ) ≤ basePrunedS 10 23.91)
    (GamS_le (θ := 0.113932) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.921 ≤ 0.073244) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.921, 23.932]`. -/
theorem shapeSaving_S25_cell_123 : ∀ c ∈ Icc (23.921 : ℝ) 23.932,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.46555 : ℝ) ≤ basePrunedS 10 23.921)
    (GamS_le (θ := 0.113924) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.932 ≤ 0.0732778) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.932, 23.942]`. -/
theorem shapeSaving_S25_cell_124 : ∀ c ∈ Icc (23.932 : ℝ) 23.942,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.47845 : ℝ) ≤ basePrunedS 10 23.932)
    (GamS_le (θ := 0.113917) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.942 ≤ 0.0733087) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.942, 23.952]`. -/
theorem shapeSaving_S25_cell_125 : ∀ c ∈ Icc (23.942 : ℝ) 23.952,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.49017 : ℝ) ≤ basePrunedS 10 23.942)
    (GamS_le (θ := 0.113909) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.952 ≤ 0.0733389) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.952, 23.962]`. -/
theorem shapeSaving_S25_cell_126 : ∀ c ∈ Icc (23.952 : ℝ) 23.962,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.5019 : ℝ) ≤ basePrunedS 10 23.952)
    (GamS_le (θ := 0.113902) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.962 ≤ 0.0733698) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.962, 23.972]`. -/
theorem shapeSaving_S25_cell_127 : ∀ c ∈ Icc (23.962 : ℝ) 23.972,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.51363 : ℝ) ≤ basePrunedS 10 23.962)
    (GamS_le (θ := 0.113895) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.972 ≤ 0.0734006) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.972, 23.982]`. -/
theorem shapeSaving_S25_cell_128 : ∀ c ∈ Icc (23.972 : ℝ) 23.982,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.52535 : ℝ) ≤ basePrunedS 10 23.972)
    (GamS_le (θ := 0.113887) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.982 ≤ 0.0734307) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.982, 23.992]`. -/
theorem shapeSaving_S25_cell_129 : ∀ c ∈ Icc (23.982 : ℝ) 23.992,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.53708 : ℝ) ≤ basePrunedS 10 23.982)
    (GamS_le (θ := 0.11388) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 23.992 ≤ 0.0734616) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [23.992, 24.001]`. -/
theorem shapeSaving_S25_cell_130 : ∀ c ∈ Icc (23.992 : ℝ) 24.001,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.5488 : ℝ) ≤ basePrunedS 10 23.992)
    (GamS_le (θ := 0.113873) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.001 ≤ 0.073489) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.001, 24.01]`. -/
theorem shapeSaving_S25_cell_131 : ∀ c ∈ Icc (24.001 : ℝ) 24.01,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.55936 : ℝ) ≤ basePrunedS 10 24.001)
    (GamS_le (θ := 0.113867) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.01 ≤ 0.0735167) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.01, 24.0197]`. -/
theorem shapeSaving_S25_cell_132 : ∀ c ∈ Icc (24.01 : ℝ) 24.0197,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.56991 : ℝ) ≤ basePrunedS 10 24.01)
    (GamS_le (θ := 0.11386) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.0197 ≤ 0.0735464) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.0197, 24.0293]`. -/
theorem shapeSaving_S25_cell_133 : ∀ c ∈ Icc (24.0197 : ℝ) 24.0293,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.58128 : ℝ) ≤ basePrunedS 10 24.0197)
    (GamS_le (θ := 0.113853) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.0293 ≤ 0.0735757) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.0293, 24.0388]`. -/
theorem shapeSaving_S25_cell_134 : ∀ c ∈ Icc (24.0293 : ℝ) 24.0388,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.59254 : ℝ) ≤ basePrunedS 10 24.0293)
    (GamS_le (θ := 0.113846) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.0388 ≤ 0.0736046) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.0388, 24.0482]`. -/
theorem shapeSaving_S25_cell_135 : ∀ c ∈ Icc (24.0388 : ℝ) 24.0482,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.60368 : ℝ) ≤ basePrunedS 10 24.0388)
    (GamS_le (θ := 0.113839) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.0482 ≤ 0.0736332) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c` in `[23.4, 24.0482]`: cells 91 to 135. -/
theorem shapeSaving_S25_block_3 : ∀ c ∈ Icc (23.4 : ℝ) 24.0482,
    shapeSaving 10 4 c < 0.001778 := by
  have h := shapeSaving_S25_cell_91
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_92
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_93
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_94
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_95
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_96
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_97
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_98
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_99
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_100
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_101
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_102
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_103
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_104
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_105
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_106
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_107
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_108
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_109
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_110
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_111
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_112
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_113
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_114
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_115
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_116
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_117
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_118
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_119
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_120
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_121
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_122
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_123
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_124
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_125
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_126
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_127
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_128
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_129
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_130
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_131
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_132
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_133
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_134
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_135
  exact h

end ImprovedExponents
