module

public import ImprovedExponents.Optimum.Shapes.NumLog

@[expose] public section

/-!
# The saving with the shape `(5, 5)` on `[51.545, 52.1]`: cells 41 to 80

This file is generated by `python3 -m search.certs`; do not edit it. Each lemma bounds
`shapeSaving 25 16 c` on one cell `[c₁, c₂]` by `F(A(c₁), Γ(c₂))`, with certified rational bounds
on `A(c₁)` and `Γ(c₂)`; the last lemma joins the cells.
-/

namespace ImprovedExponents

open Set

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.545, 51.578]`. -/
theorem shapeSaving_S55_cell_41 : ∀ c ∈ Icc (51.545 : ℝ) 51.578,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (83.81538 : ℝ) ≤ basePrunedS 25 51.545)
    (GamS_le (θ := 0.22288) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.578 ≤ 0.0665306) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.578, 51.609]`. -/
theorem shapeSaving_S55_cell_42 : ∀ c ∈ Icc (51.578 : ℝ) 51.609,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (83.86881 : ℝ) ≤ basePrunedS 25 51.578)
    (GamS_le (θ := 0.22286) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.609 ≤ 0.0665728) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.609, 51.638]`. -/
theorem shapeSaving_S55_cell_43 : ∀ c ∈ Icc (51.609 : ℝ) 51.638,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (83.91901 : ℝ) ≤ basePrunedS 25 51.609)
    (GamS_le (θ := 0.222841) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.638 ≤ 0.0666125) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.638, 51.666]`. -/
theorem shapeSaving_S55_cell_44 : ∀ c ∈ Icc (51.638 : ℝ) 51.666,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (83.96597 : ℝ) ≤ basePrunedS 25 51.638)
    (GamS_le (θ := 0.222824) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.666 ≤ 0.0666506) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.666, 51.692]`. -/
theorem shapeSaving_S55_cell_45 : ∀ c ∈ Icc (51.666 : ℝ) 51.692,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.0113 : ℝ) ≤ basePrunedS 25 51.666)
    (GamS_le (θ := 0.222807) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.692 ≤ 0.0666858) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.692, 51.717]`. -/
theorem shapeSaving_S55_cell_46 : ∀ c ∈ Icc (51.692 : ℝ) 51.717,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.0534 : ℝ) ≤ basePrunedS 25 51.692)
    (GamS_le (θ := 0.222791) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.717 ≤ 0.0667199) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.717, 51.74]`. -/
theorem shapeSaving_S55_cell_47 : ∀ c ∈ Icc (51.717 : ℝ) 51.74,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.09388 : ℝ) ≤ basePrunedS 25 51.717)
    (GamS_le (θ := 0.222777) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.74 ≤ 0.0667513) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.74, 51.762]`. -/
theorem shapeSaving_S55_cell_48 : ∀ c ∈ Icc (51.74 : ℝ) 51.762,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.13112 : ℝ) ≤ basePrunedS 25 51.74)
    (GamS_le (θ := 0.222763) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.762 ≤ 0.0667812) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.762, 51.783]`. -/
theorem shapeSaving_S55_cell_49 : ∀ c ∈ Icc (51.762 : ℝ) 51.783,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.16675 : ℝ) ≤ basePrunedS 25 51.762)
    (GamS_le (θ := 0.22275) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.783 ≤ 0.0668098) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.783, 51.803]`. -/
theorem shapeSaving_S55_cell_50 : ∀ c ∈ Icc (51.783 : ℝ) 51.803,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.20075 : ℝ) ≤ basePrunedS 25 51.783)
    (GamS_le (θ := 0.222737) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.803 ≤ 0.0668368) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.803, 51.822]`. -/
theorem shapeSaving_S55_cell_51 : ∀ c ∈ Icc (51.803 : ℝ) 51.822,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.23313 : ℝ) ≤ basePrunedS 25 51.803)
    (GamS_le (θ := 0.222725) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.822 ≤ 0.0668626) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.822, 51.84]`. -/
theorem shapeSaving_S55_cell_52 : ∀ c ∈ Icc (51.822 : ℝ) 51.84,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.2639 : ℝ) ≤ basePrunedS 25 51.822)
    (GamS_le (θ := 0.222714) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.84 ≤ 0.0668872) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.84, 51.857]`. -/
theorem shapeSaving_S55_cell_53 : ∀ c ∈ Icc (51.84 : ℝ) 51.857,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.29304 : ℝ) ≤ basePrunedS 25 51.84)
    (GamS_le (θ := 0.222703) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.857 ≤ 0.0669102) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.857, 51.873]`. -/
theorem shapeSaving_S55_cell_54 : ∀ c ∈ Icc (51.857 : ℝ) 51.873,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.32057 : ℝ) ≤ basePrunedS 25 51.857)
    (GamS_le (θ := 0.222693) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.873 ≤ 0.0669319) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.873, 51.888]`. -/
theorem shapeSaving_S55_cell_55 : ∀ c ∈ Icc (51.873 : ℝ) 51.888,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.34648 : ℝ) ≤ basePrunedS 25 51.873)
    (GamS_le (θ := 0.222683) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.888 ≤ 0.066952) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.888, 51.902]`. -/
theorem shapeSaving_S55_cell_56 : ∀ c ∈ Icc (51.888 : ℝ) 51.902,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.37076 : ℝ) ≤ basePrunedS 25 51.888)
    (GamS_le (θ := 0.222675) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.902 ≤ 0.0669713) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.902, 51.915]`. -/
theorem shapeSaving_S55_cell_57 : ∀ c ∈ Icc (51.902 : ℝ) 51.915,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.39343 : ℝ) ≤ basePrunedS 25 51.902)
    (GamS_le (θ := 0.222666) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.915 ≤ 0.0669886) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.915, 51.928]`. -/
theorem shapeSaving_S55_cell_58 : ∀ c ∈ Icc (51.915 : ℝ) 51.928,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.41448 : ℝ) ≤ basePrunedS 25 51.915)
    (GamS_le (θ := 0.222658) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.928 ≤ 0.0670063) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.928, 51.94]`. -/
theorem shapeSaving_S55_cell_59 : ∀ c ∈ Icc (51.928 : ℝ) 51.94,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.43553 : ℝ) ≤ basePrunedS 25 51.928)
    (GamS_le (θ := 0.222651) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.94 ≤ 0.0670227) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.94, 51.952]`. -/
theorem shapeSaving_S55_cell_60 : ∀ c ∈ Icc (51.94 : ℝ) 51.952,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.45496 : ℝ) ≤ basePrunedS 25 51.94)
    (GamS_le (θ := 0.222643) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.952 ≤ 0.0670388) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.952, 51.963]`. -/
theorem shapeSaving_S55_cell_61 : ∀ c ∈ Icc (51.952 : ℝ) 51.963,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.47439 : ℝ) ≤ basePrunedS 25 51.952)
    (GamS_le (θ := 0.222636) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.963 ≤ 0.0670536) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.963, 51.973]`. -/
theorem shapeSaving_S55_cell_62 : ∀ c ∈ Icc (51.963 : ℝ) 51.973,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.4922 : ℝ) ≤ basePrunedS 25 51.963)
    (GamS_le (θ := 0.22263) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.973 ≤ 0.0670672) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.973, 51.983]`. -/
theorem shapeSaving_S55_cell_63 : ∀ c ∈ Icc (51.973 : ℝ) 51.983,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.50839 : ℝ) ≤ basePrunedS 25 51.973)
    (GamS_le (θ := 0.222624) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.983 ≤ 0.0670809) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.983, 51.993]`. -/
theorem shapeSaving_S55_cell_64 : ∀ c ∈ Icc (51.983 : ℝ) 51.993,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.52458 : ℝ) ≤ basePrunedS 25 51.983)
    (GamS_le (θ := 0.222617) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 51.993 ≤ 0.0670941) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [51.993, 52.0025]`. -/
theorem shapeSaving_S55_cell_65 : ∀ c ∈ Icc (51.993 : ℝ) 52.0025,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.54077 : ℝ) ≤ basePrunedS 25 51.993)
    (GamS_le (θ := 0.222611) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 52.0025 ≤ 0.067107) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [52.0025, 52.0114]`. -/
theorem shapeSaving_S55_cell_66 : ∀ c ∈ Icc (52.0025 : ℝ) 52.0114,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.55616 : ℝ) ≤ basePrunedS 25 52.0025)
    (GamS_le (θ := 0.222606) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 52.0114 ≤ 0.0671192) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [52.0114, 52.02]`. -/
theorem shapeSaving_S55_cell_67 : ∀ c ∈ Icc (52.0114 : ℝ) 52.02,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.57057 : ℝ) ≤ basePrunedS 25 52.0114)
    (GamS_le (θ := 0.2226) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 52.02 ≤ 0.0671306) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [52.02, 52.0282]`. -/
theorem shapeSaving_S55_cell_68 : ∀ c ∈ Icc (52.02 : ℝ) 52.0282,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.58449 : ℝ) ≤ basePrunedS 25 52.02)
    (GamS_le (θ := 0.222595) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 52.0282 ≤ 0.0671417) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [52.0282, 52.036]`. -/
theorem shapeSaving_S55_cell_69 : ∀ c ∈ Icc (52.0282 : ℝ) 52.036,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.59777 : ℝ) ≤ basePrunedS 25 52.0282)
    (GamS_le (θ := 0.22259) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 52.036 ≤ 0.0671522) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [52.036, 52.0432]`. -/
theorem shapeSaving_S55_cell_70 : ∀ c ∈ Icc (52.036 : ℝ) 52.0432,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.6104 : ℝ) ≤ basePrunedS 25 52.036)
    (GamS_le (θ := 0.222586) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 52.0432 ≤ 0.0671621) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [52.0432, 52.0503]`. -/
theorem shapeSaving_S55_cell_71 : ∀ c ∈ Icc (52.0432 : ℝ) 52.0503,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.62206 : ℝ) ≤ basePrunedS 25 52.0432)
    (GamS_le (θ := 0.222581) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 52.0503 ≤ 0.0671715) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [52.0503, 52.057]`. -/
theorem shapeSaving_S55_cell_72 : ∀ c ∈ Icc (52.0503 : ℝ) 52.057,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.63355 : ℝ) ≤ basePrunedS 25 52.0503)
    (GamS_le (θ := 0.222577) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 52.057 ≤ 0.0671806) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [52.057, 52.0633]`. -/
theorem shapeSaving_S55_cell_73 : ∀ c ∈ Icc (52.057 : ℝ) 52.0633,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.6444 : ℝ) ≤ basePrunedS 25 52.057)
    (GamS_le (θ := 0.222573) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 52.0633 ≤ 0.0671891) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [52.0633, 52.0694]`. -/
theorem shapeSaving_S55_cell_74 : ∀ c ∈ Icc (52.0633 : ℝ) 52.0694,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.6546 : ℝ) ≤ basePrunedS 25 52.0633)
    (GamS_le (θ := 0.222569) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 52.0694 ≤ 0.0671973) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [52.0694, 52.0751]`. -/
theorem shapeSaving_S55_cell_75 : ∀ c ∈ Icc (52.0694 : ℝ) 52.0751,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.66448 : ℝ) ≤ basePrunedS 25 52.0694)
    (GamS_le (θ := 0.222566) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 52.0751 ≤ 0.0672052) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [52.0751, 52.0806]`. -/
theorem shapeSaving_S55_cell_76 : ∀ c ∈ Icc (52.0751 : ℝ) 52.0806,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.67371 : ℝ) ≤ basePrunedS 25 52.0751)
    (GamS_le (θ := 0.222562) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 52.0806 ≤ 0.0672124) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [52.0806, 52.0858]`. -/
theorem shapeSaving_S55_cell_77 : ∀ c ∈ Icc (52.0806 : ℝ) 52.0858,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.68261 : ℝ) ≤ basePrunedS 25 52.0806)
    (GamS_le (θ := 0.222559) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 52.0858 ≤ 0.0672195) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [52.0858, 52.0907]`. -/
theorem shapeSaving_S55_cell_78 : ∀ c ∈ Icc (52.0858 : ℝ) 52.0907,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.69103 : ℝ) ≤ basePrunedS 25 52.0858)
    (GamS_le (θ := 0.222556) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 52.0907 ≤ 0.0672261) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [52.0907, 52.0954]`. -/
theorem shapeSaving_S55_cell_79 : ∀ c ∈ Icc (52.0907 : ℝ) 52.0954,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.69896 : ℝ) ≤ basePrunedS 25 52.0907)
    (GamS_le (θ := 0.222553) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 52.0954 ≤ 0.0672324) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c ∈ [52.0954, 52.1]`. -/
theorem shapeSaving_S55_cell_80 : ∀ c ∈ Icc (52.0954 : ℝ) 52.1,
    shapeSaving 25 16 c < 0.001098 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 5 : (84.70657 : ℝ) ≤ basePrunedS 25 52.0954)
    (GamS_le (θ := 0.22255) (gammaXS_le 6 5 4)
      (gammaQS_le (-2) 5 4) : GamS 25 16 52.1 ≤ 0.0672386) hc

/-- `shapeSaving 25 16 c < 0.001098` for `c` in `[51.545, 52.1]`: cells 41 to 80. -/
theorem shapeSaving_S55_block_2 : ∀ c ∈ Icc (51.545 : ℝ) 52.1,
    shapeSaving 25 16 c < 0.001098 := by
  have h := shapeSaving_S55_cell_41
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_42
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_43
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_44
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_45
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_46
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_47
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_48
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_49
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_50
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_51
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_52
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_53
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_54
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_55
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_56
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_57
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_58
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_59
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_60
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_61
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_62
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_63
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_64
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_65
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_66
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_67
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_68
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_69
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_70
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_71
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_72
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_73
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_74
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_75
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_76
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_77
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_78
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_79
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S55_cell_80
  exact h

end ImprovedExponents
