module

public import ImprovedExponents.Optimum.Shapes.Cells_S24_1
public import ImprovedExponents.Optimum.Shapes.Cells_S24_2
public import ImprovedExponents.Optimum.Shapes.Cells_S24_3
public import ImprovedExponents.Optimum.Shapes.Cells_S24_4
public import ImprovedExponents.Optimum.Shapes.Cells_S24_5

@[expose] public section

/-!
# The saving with the shape `(2, 4)` on `(9, 200]`

This file is generated by `python3 -m search.certs`; do not edit it. It joins the
232 cells of the files `Cells_S24_1.lean` to `Cells_S24_5.lean` into three ranges:

* `shapeSaving_S24_lt_below`: `shapeSaving 8 3 c < 0.001875` for `9 < c ≤ 19.6`;
* `shapeSaving_S24_lt_window`: `shapeSaving 8 3 c < 0.001877` for `19.6 ≤ c ≤ 20.6`;
* `shapeSaving_S24_lt_above`: `shapeSaving 8 3 c < 0.001875` for `20.6 ≤ c ≤ 200`.

For a shape it also has the tail `shapeSaving_S24_lt_tail` (`c ≥ 200`) and the witness
`shapeSaving_S24_witness` at `c = 20.1`.
-/

namespace ImprovedExponents

open Set

/-- `shapeSaving 8 3 c < 0.001875` for `c` in `(9, 19.6]`. -/
theorem shapeSaving_S24_lt_below : ∀ c ∈ Ioc (9 : ℝ) 19.6,
    shapeSaving 8 3 c < 0.001875 := by
  have h := shapeSaving_S24_block_1
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S24_block_2
  exact h

/-- `shapeSaving 8 3 c < 0.001877` for `c` in `[19.6, 20.6]`. -/
theorem shapeSaving_S24_lt_window : ∀ c ∈ Icc (19.6 : ℝ) 20.6,
    shapeSaving 8 3 c < 0.001877 :=
  shapeSaving_S24_block_3

/-- `shapeSaving 8 3 c < 0.001875` for `c` in `[20.6, 200]`. -/
theorem shapeSaving_S24_lt_above : ∀ c ∈ Icc (20.6 : ℝ) 200,
    shapeSaving 8 3 c < 0.001875 := by
  have h := shapeSaving_S24_block_4
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_block_5
  exact h

/-- The tail: `shapeSaving 8 3 c < 0.001875` for `c ≥ 200`, because `Γ(c) < 2/3`. -/
theorem shapeSaving_S24_lt_tail {c : ℝ} (hc : 200 ≤ c) :
    shapeSaving 8 3 c < 0.001875 :=
  shapeSaving_lt_of_le 2 (le_basePrunedS 8 3 :
    (210.05233 : ℝ) ≤ basePrunedS 8 200) hc

/-- The witness: `0.001875 < shapeSaving 8 3 c` at `c = 20.1`. -/
theorem shapeSaving_S24_witness : (0.001875 : ℝ) < shapeSaving 8 3 20.1 :=
  lt_savingS 2 (basePrunedS_pos (by norm_num) (by norm_num))
    (basePrunedS_le 4 3 : basePrunedS 8 20.1 ≤ 21.84638)
    (le_GamS (θ := 0.089528) (le_gammaXS 4 3 2)
      (le_gammaQS (-3) 3 2) : (0.0748706 : ℝ) ≤ GamS 8 3 20.1)

end ImprovedExponents
