module

public import ImprovedExponents.Optimum.Shapes.NumLog

@[expose] public section

/-!
# The saving with the shape `(4, 5)` on `[42.7, 45.4]`: cells 93 to 145

This file is generated by `python3 -m search.certs`; do not edit it. Each lemma bounds
`shapeSaving 20 12 c` on one cell `[c₁, c₂]` by `F(A(c₁), Γ(c₂))`, with certified rational bounds
on `A(c₁)` and `Γ(c₂)`; the last lemma joins the cells.
-/

namespace ImprovedExponents

open Set

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [42.7, 42.765]`. -/
theorem shapeSaving_S45_cell_93 : ∀ c ∈ Icc (42.7 : ℝ) 42.765,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (64.83221 : ℝ) ≤ basePrunedS 20 42.7)
    (GamS_le (θ := 0.203136) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 42.765 ≤ 0.0693221) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [42.765, 42.828]`. -/
theorem shapeSaving_S45_cell_94 : ∀ c ∈ Icc (42.765 : ℝ) 42.828,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (64.93034 : ℝ) ≤ basePrunedS 20 42.765)
    (GamS_le (θ := 0.203091) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 42.828 ≤ 0.0694275) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [42.828, 42.889]`. -/
theorem shapeSaving_S45_cell_95 : ∀ c ∈ Icc (42.828 : ℝ) 42.889,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (65.02545 : ℝ) ≤ basePrunedS 20 42.828)
    (GamS_le (θ := 0.203048) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 42.889 ≤ 0.0695295) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [42.889, 42.948]`. -/
theorem shapeSaving_S45_cell_96 : ∀ c ∈ Icc (42.889 : ℝ) 42.948,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (65.11754 : ℝ) ≤ basePrunedS 20 42.889)
    (GamS_le (θ := 0.203006) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 42.948 ≤ 0.0696278) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [42.948, 43.005]`. -/
theorem shapeSaving_S45_cell_97 : ∀ c ∈ Icc (42.948 : ℝ) 43.005,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (65.20661 : ℝ) ≤ basePrunedS 20 42.948)
    (GamS_le (θ := 0.202965) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 43.005 ≤ 0.0697224) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [43.005, 43.061]`. -/
theorem shapeSaving_S45_cell_98 : ∀ c ∈ Icc (43.005 : ℝ) 43.061,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (65.29266 : ℝ) ≤ basePrunedS 20 43.005)
    (GamS_le (θ := 0.202925) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 43.061 ≤ 0.0698156) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [43.061, 43.115]`. -/
theorem shapeSaving_S45_cell_99 : ∀ c ∈ Icc (43.061 : ℝ) 43.115,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (65.3772 : ℝ) ≤ basePrunedS 20 43.061)
    (GamS_le (θ := 0.202887) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 43.115 ≤ 0.0699048) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [43.115, 43.168]`. -/
theorem shapeSaving_S45_cell_100 : ∀ c ∈ Icc (43.115 : ℝ) 43.168,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (65.45872 : ℝ) ≤ basePrunedS 20 43.115)
    (GamS_le (θ := 0.20285) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 43.168 ≤ 0.0699927) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [43.168, 43.22]`. -/
theorem shapeSaving_S45_cell_101 : ∀ c ∈ Icc (43.168 : ℝ) 43.22,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (65.53873 : ℝ) ≤ basePrunedS 20 43.168)
    (GamS_le (θ := 0.202813) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 43.22 ≤ 0.0700785) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [43.22, 43.271]`. -/
theorem shapeSaving_S45_cell_102 : ∀ c ∈ Icc (43.22 : ℝ) 43.271,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (65.61722 : ℝ) ≤ basePrunedS 20 43.22)
    (GamS_le (θ := 0.202777) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 43.271 ≤ 0.0701626) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [43.271, 43.32]`. -/
theorem shapeSaving_S45_cell_103 : ∀ c ∈ Icc (43.271 : ℝ) 43.32,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (65.69421 : ℝ) ≤ basePrunedS 20 43.271)
    (GamS_le (θ := 0.202743) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 43.32 ≤ 0.0702435) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [43.32, 43.369]`. -/
theorem shapeSaving_S45_cell_104 : ∀ c ∈ Icc (43.32 : ℝ) 43.369,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (65.76818 : ℝ) ≤ basePrunedS 20 43.32)
    (GamS_le (θ := 0.202708) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 43.369 ≤ 0.0703239) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [43.369, 43.417]`. -/
theorem shapeSaving_S45_cell_105 : ∀ c ∈ Icc (43.369 : ℝ) 43.417,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (65.84215 : ℝ) ≤ basePrunedS 20 43.369)
    (GamS_le (θ := 0.202675) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 43.417 ≤ 0.0704029) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [43.417, 43.464]`. -/
theorem shapeSaving_S45_cell_106 : ∀ c ∈ Icc (43.417 : ℝ) 43.464,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (65.9146 : ℝ) ≤ basePrunedS 20 43.417)
    (GamS_le (θ := 0.202642) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 43.464 ≤ 0.07048) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [43.464, 43.51]`. -/
theorem shapeSaving_S45_cell_107 : ∀ c ∈ Icc (43.464 : ℝ) 43.51,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (65.98555 : ℝ) ≤ basePrunedS 20 43.464)
    (GamS_le (θ := 0.20261) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 43.51 ≤ 0.0705554) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [43.51, 43.556]`. -/
theorem shapeSaving_S45_cell_108 : ∀ c ∈ Icc (43.51 : ℝ) 43.556,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (66.05499 : ℝ) ≤ basePrunedS 20 43.51)
    (GamS_le (θ := 0.202578) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 43.556 ≤ 0.0706307) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [43.556, 43.601]`. -/
theorem shapeSaving_S45_cell_109 : ∀ c ∈ Icc (43.556 : ℝ) 43.601,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (66.12442 : ℝ) ≤ basePrunedS 20 43.556)
    (GamS_le (θ := 0.202546) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 43.601 ≤ 0.0707039) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [43.601, 43.646]`. -/
theorem shapeSaving_S45_cell_110 : ∀ c ∈ Icc (43.601 : ℝ) 43.646,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (66.19235 : ℝ) ≤ basePrunedS 20 43.601)
    (GamS_le (θ := 0.202515) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 43.646 ≤ 0.0707774) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [43.646, 43.69]`. -/
theorem shapeSaving_S45_cell_111 : ∀ c ∈ Icc (43.646 : ℝ) 43.69,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (66.26028 : ℝ) ≤ basePrunedS 20 43.646)
    (GamS_le (θ := 0.202484) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 43.69 ≤ 0.0708489) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [43.69, 43.734]`. -/
theorem shapeSaving_S45_cell_112 : ∀ c ∈ Icc (43.69 : ℝ) 43.734,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (66.32669 : ℝ) ≤ basePrunedS 20 43.69)
    (GamS_le (θ := 0.202454) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 43.734 ≤ 0.0709207) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [43.734, 43.778]`. -/
theorem shapeSaving_S45_cell_113 : ∀ c ∈ Icc (43.734 : ℝ) 43.778,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (66.39311 : ℝ) ≤ basePrunedS 20 43.734)
    (GamS_le (θ := 0.202423) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 43.778 ≤ 0.070992) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [43.778, 43.821]`. -/
theorem shapeSaving_S45_cell_114 : ∀ c ∈ Icc (43.778 : ℝ) 43.821,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (66.45952 : ℝ) ≤ basePrunedS 20 43.778)
    (GamS_le (θ := 0.202393) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 43.821 ≤ 0.0710618) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [43.821, 43.864]`. -/
theorem shapeSaving_S45_cell_115 : ∀ c ∈ Icc (43.821 : ℝ) 43.864,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (66.52443 : ℝ) ≤ basePrunedS 20 43.821)
    (GamS_le (θ := 0.202364) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 43.864 ≤ 0.0711316) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [43.864, 43.907]`. -/
theorem shapeSaving_S45_cell_116 : ∀ c ∈ Icc (43.864 : ℝ) 43.907,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (66.58933 : ℝ) ≤ basePrunedS 20 43.864)
    (GamS_le (θ := 0.202334) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 43.907 ≤ 0.0712011) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [43.907, 43.95]`. -/
theorem shapeSaving_S45_cell_117 : ∀ c ∈ Icc (43.907 : ℝ) 43.95,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (66.65424 : ℝ) ≤ basePrunedS 20 43.907)
    (GamS_le (θ := 0.202304) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 43.95 ≤ 0.0712705) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [43.95, 43.993]`. -/
theorem shapeSaving_S45_cell_118 : ∀ c ∈ Icc (43.95 : ℝ) 43.993,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (66.71914 : ℝ) ≤ basePrunedS 20 43.95)
    (GamS_le (θ := 0.202275) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 43.993 ≤ 0.0713401) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [43.993, 44.036]`. -/
theorem shapeSaving_S45_cell_119 : ∀ c ∈ Icc (43.993 : ℝ) 44.036,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (66.78404 : ℝ) ≤ basePrunedS 20 43.993)
    (GamS_le (θ := 0.202245) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 44.036 ≤ 0.0714093) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [44.036, 44.079]`. -/
theorem shapeSaving_S45_cell_120 : ∀ c ∈ Icc (44.036 : ℝ) 44.079,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (66.84894 : ℝ) ≤ basePrunedS 20 44.036)
    (GamS_le (θ := 0.202216) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 44.079 ≤ 0.0714787) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [44.079, 44.122]`. -/
theorem shapeSaving_S45_cell_121 : ∀ c ∈ Icc (44.079 : ℝ) 44.122,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (66.91385 : ℝ) ≤ basePrunedS 20 44.079)
    (GamS_le (θ := 0.202186) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 44.122 ≤ 0.0715476) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [44.122, 44.166]`. -/
theorem shapeSaving_S45_cell_122 : ∀ c ∈ Icc (44.122 : ℝ) 44.166,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (66.97875 : ℝ) ≤ basePrunedS 20 44.122)
    (GamS_le (θ := 0.202156) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 44.166 ≤ 0.0716184) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [44.166, 44.21]`. -/
theorem shapeSaving_S45_cell_123 : ∀ c ∈ Icc (44.166 : ℝ) 44.21,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (67.04516 : ℝ) ≤ basePrunedS 20 44.166)
    (GamS_le (θ := 0.202126) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 44.21 ≤ 0.071689) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [44.21, 44.254]`. -/
theorem shapeSaving_S45_cell_124 : ∀ c ∈ Icc (44.21 : ℝ) 44.254,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (67.11157 : ℝ) ≤ basePrunedS 20 44.21)
    (GamS_le (θ := 0.202096) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 44.254 ≤ 0.0717595) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [44.254, 44.299]`. -/
theorem shapeSaving_S45_cell_125 : ∀ c ∈ Icc (44.254 : ℝ) 44.299,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (67.17798 : ℝ) ≤ basePrunedS 20 44.254)
    (GamS_le (θ := 0.202065) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 44.299 ≤ 0.0718313) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [44.299, 44.344]`. -/
theorem shapeSaving_S45_cell_126 : ∀ c ∈ Icc (44.299 : ℝ) 44.344,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (67.24589 : ℝ) ≤ basePrunedS 20 44.299)
    (GamS_le (θ := 0.202034) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 44.344 ≤ 0.0719032) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [44.344, 44.39]`. -/
theorem shapeSaving_S45_cell_127 : ∀ c ∈ Icc (44.344 : ℝ) 44.39,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (67.31381 : ℝ) ≤ basePrunedS 20 44.344)
    (GamS_le (θ := 0.202003) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 44.39 ≤ 0.0719766) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [44.39, 44.436]`. -/
theorem shapeSaving_S45_cell_128 : ∀ c ∈ Icc (44.39 : ℝ) 44.436,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (67.38324 : ℝ) ≤ basePrunedS 20 44.39)
    (GamS_le (θ := 0.201972) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 44.436 ≤ 0.07205) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [44.436, 44.483]`. -/
theorem shapeSaving_S45_cell_129 : ∀ c ∈ Icc (44.436 : ℝ) 44.483,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (67.45266 : ℝ) ≤ basePrunedS 20 44.436)
    (GamS_le (θ := 0.20194) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 44.483 ≤ 0.0721247) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [44.483, 44.531]`. -/
theorem shapeSaving_S45_cell_130 : ∀ c ∈ Icc (44.483 : ℝ) 44.531,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (67.5236 : ℝ) ≤ basePrunedS 20 44.483)
    (GamS_le (θ := 0.201907) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 44.531 ≤ 0.072201) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [44.531, 44.579]`. -/
theorem shapeSaving_S45_cell_131 : ∀ c ∈ Icc (44.531 : ℝ) 44.579,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (67.59604 : ℝ) ≤ basePrunedS 20 44.531)
    (GamS_le (θ := 0.201875) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 44.579 ≤ 0.0722771) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [44.579, 44.628]`. -/
theorem shapeSaving_S45_cell_132 : ∀ c ∈ Icc (44.579 : ℝ) 44.628,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (67.66848 : ℝ) ≤ basePrunedS 20 44.579)
    (GamS_le (θ := 0.201842) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 44.628 ≤ 0.0723548) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [44.628, 44.678]`. -/
theorem shapeSaving_S45_cell_133 : ∀ c ∈ Icc (44.628 : ℝ) 44.678,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (67.74243 : ℝ) ≤ basePrunedS 20 44.628)
    (GamS_le (θ := 0.201808) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 44.678 ≤ 0.0724338) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [44.678, 44.729]`. -/
theorem shapeSaving_S45_cell_134 : ∀ c ∈ Icc (44.678 : ℝ) 44.729,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (67.81789 : ℝ) ≤ basePrunedS 20 44.678)
    (GamS_le (θ := 0.201774) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 44.729 ≤ 0.0725145) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [44.729, 44.782]`. -/
theorem shapeSaving_S45_cell_135 : ∀ c ∈ Icc (44.729 : ℝ) 44.782,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (67.89486 : ℝ) ≤ basePrunedS 20 44.729)
    (GamS_le (θ := 0.201738) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 44.782 ≤ 0.0725979) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [44.782, 44.836]`. -/
theorem shapeSaving_S45_cell_136 : ∀ c ∈ Icc (44.782 : ℝ) 44.836,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (67.97485 : ℝ) ≤ basePrunedS 20 44.782)
    (GamS_le (θ := 0.201702) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 44.836 ≤ 0.0726831) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [44.836, 44.891]`. -/
theorem shapeSaving_S45_cell_137 : ∀ c ∈ Icc (44.836 : ℝ) 44.891,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (68.05634 : ℝ) ≤ basePrunedS 20 44.836)
    (GamS_le (θ := 0.201665) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 44.891 ≤ 0.0727695) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [44.891, 44.948]`. -/
theorem shapeSaving_S45_cell_138 : ∀ c ∈ Icc (44.891 : ℝ) 44.948,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (68.13934 : ℝ) ≤ basePrunedS 20 44.891)
    (GamS_le (θ := 0.201627) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 44.948 ≤ 0.072859) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [44.948, 45.006]`. -/
theorem shapeSaving_S45_cell_139 : ∀ c ∈ Icc (44.948 : ℝ) 45.006,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (68.22536 : ℝ) ≤ basePrunedS 20 44.948)
    (GamS_le (θ := 0.201588) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 45.006 ≤ 0.0729498) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [45.006, 45.066]`. -/
theorem shapeSaving_S45_cell_140 : ∀ c ∈ Icc (45.006 : ℝ) 45.066,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (68.31289 : ℝ) ≤ basePrunedS 20 45.006)
    (GamS_le (θ := 0.201548) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 45.066 ≤ 0.0730437) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [45.066, 45.128]`. -/
theorem shapeSaving_S45_cell_141 : ∀ c ∈ Icc (45.066 : ℝ) 45.128,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (68.40344 : ℝ) ≤ basePrunedS 20 45.066)
    (GamS_le (θ := 0.201507) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 45.128 ≤ 0.0731406) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [45.128, 45.192]`. -/
theorem shapeSaving_S45_cell_142 : ∀ c ∈ Icc (45.128 : ℝ) 45.192,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (68.497 : ℝ) ≤ basePrunedS 20 45.128)
    (GamS_le (θ := 0.201464) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 45.192 ≤ 0.0732402) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [45.192, 45.259]`. -/
theorem shapeSaving_S45_cell_143 : ∀ c ∈ Icc (45.192 : ℝ) 45.259,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 5 4 : (68.59358 : ℝ) ≤ basePrunedS 20 45.192)
    (GamS_le (θ := 0.20142) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 45.259 ≤ 0.0733446) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [45.259, 45.328]`. -/
theorem shapeSaving_S45_cell_144 : ∀ c ∈ Icc (45.259 : ℝ) 45.328,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 4 : (68.69469 : ℝ) ≤ basePrunedS 20 45.259)
    (GamS_le (θ := 0.201374) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 45.328 ≤ 0.0734516) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c ∈ [45.328, 45.4]`. -/
theorem shapeSaving_S45_cell_145 : ∀ c ∈ Icc (45.328 : ℝ) 45.4,
    shapeSaving 20 12 c < 0.001325 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 4
    (le_basePrunedS 6 4 : (68.79881 : ℝ) ≤ basePrunedS 20 45.328)
    (GamS_le (θ := 0.201327) (gammaXS_le 5 4 4)
      (gammaQS_le (-2) 4 4) : GamS 20 12 45.4 ≤ 0.0735634) hc

/-- `shapeSaving 20 12 c < 0.001325` for `c` in `[42.7, 45.4]`: cells 93 to 145. -/
theorem shapeSaving_S45_block_3 : ∀ c ∈ Icc (42.7 : ℝ) 45.4,
    shapeSaving 20 12 c < 0.001325 := by
  have h := shapeSaving_S45_cell_93
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_94
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_95
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_96
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_97
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_98
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_99
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_100
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_101
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_102
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_103
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_104
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_105
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_106
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_107
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_108
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_109
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_110
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_111
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_112
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_113
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_114
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_115
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_116
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_117
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_118
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_119
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_120
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_121
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_122
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_123
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_124
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_125
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_126
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_127
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_128
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_129
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_130
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_131
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_132
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_133
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_134
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_135
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_136
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_137
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_138
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_139
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_140
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_141
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_142
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_143
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_144
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S45_cell_145
  exact h

end ImprovedExponents
