module

public import ImprovedExponents.Optimum.Shapes.NumLog

@[expose] public section

/-!
# The saving with the shape `(2, 3)` on `[16.975, 200]`: cells 232 to 264

This file is generated by `python3 -m search.certs`; do not edit it. Each lemma bounds
`shapeSaving 6 2 c` on one cell `[c₁, c₂]` by `F(A(c₁), Γ(c₂))`, with certified rational bounds
on `A(c₁)` and `Γ(c₂)`; the last lemma joins the cells.
-/

namespace ImprovedExponents

open Set

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [16.975, 16.996]`. -/
theorem shapeSaving_S23_cell_232 : ∀ c ∈ Icc (16.975 : ℝ) 16.996,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (16.21252 : ℝ) ≤ basePrunedS 6 16.975)
    (GamS_le (θ := 0.053779) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 16.996 ≤ 0.078335) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [16.996, 17.019]`. -/
theorem shapeSaving_S23_cell_233 : ∀ c ∈ Icc (16.996 : ℝ) 17.019,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (16.23197 : ℝ) ≤ basePrunedS 6 16.996)
    (GamS_le (θ := 0.053768) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 17.019 ≤ 0.0784297) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [17.019, 17.043]`. -/
theorem shapeSaving_S23_cell_234 : ∀ c ∈ Icc (17.019 : ℝ) 17.043,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (16.25327 : ℝ) ≤ basePrunedS 6 17.019)
    (GamS_le (θ := 0.053757) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 17.043 ≤ 0.0785291) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [17.043, 17.069]`. -/
theorem shapeSaving_S23_cell_235 : ∀ c ∈ Icc (17.043 : ℝ) 17.069,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (16.2755 : ℝ) ≤ basePrunedS 6 17.043)
    (GamS_le (θ := 0.053745) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 17.069 ≤ 0.0786364) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [17.069, 17.098]`. -/
theorem shapeSaving_S23_cell_236 : ∀ c ∈ Icc (17.069 : ℝ) 17.098,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (16.29957 : ℝ) ≤ basePrunedS 6 17.069)
    (GamS_le (θ := 0.053732) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 17.098 ≤ 0.0787564) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [17.098, 17.129]`. -/
theorem shapeSaving_S23_cell_237 : ∀ c ∈ Icc (17.098 : ℝ) 17.129,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (16.32643 : ℝ) ≤ basePrunedS 6 17.098)
    (GamS_le (θ := 0.053717) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 17.129 ≤ 0.0788829) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [17.129, 17.163]`. -/
theorem shapeSaving_S23_cell_238 : ∀ c ∈ Icc (17.129 : ℝ) 17.163,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (16.35514 : ℝ) ≤ basePrunedS 6 17.129)
    (GamS_le (θ := 0.053702) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 17.163 ≤ 0.0790228) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [17.163, 17.2]`. -/
theorem shapeSaving_S23_cell_239 : ∀ c ∈ Icc (17.163 : ℝ) 17.2,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (16.38662 : ℝ) ≤ basePrunedS 6 17.163)
    (GamS_le (θ := 0.053685) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 17.2 ≤ 0.0791739) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [17.2, 17.241]`. -/
theorem shapeSaving_S23_cell_240 : ∀ c ∈ Icc (17.2 : ℝ) 17.241,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (16.42087 : ℝ) ≤ basePrunedS 6 17.2)
    (GamS_le (θ := 0.053666) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 17.241 ≤ 0.0793405) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [17.241, 17.286]`. -/
theorem shapeSaving_S23_cell_241 : ∀ c ∈ Icc (17.241 : ℝ) 17.286,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (16.45883 : ℝ) ≤ basePrunedS 6 17.241)
    (GamS_le (θ := 0.053646) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 17.286 ≤ 0.0795238) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [17.286, 17.336]`. -/
theorem shapeSaving_S23_cell_242 : ∀ c ∈ Icc (17.286 : ℝ) 17.336,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (16.50049 : ℝ) ≤ basePrunedS 6 17.286)
    (GamS_le (θ := 0.053623) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 17.336 ≤ 0.0797258) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [17.336, 17.391]`. -/
theorem shapeSaving_S23_cell_243 : ∀ c ∈ Icc (17.336 : ℝ) 17.391,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (16.54677 : ℝ) ≤ basePrunedS 6 17.336)
    (GamS_le (θ := 0.053599) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 17.391 ≤ 0.0799483) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [17.391, 17.453]`. -/
theorem shapeSaving_S23_cell_244 : ∀ c ∈ Icc (17.391 : ℝ) 17.453,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (16.59767 : ℝ) ≤ basePrunedS 6 17.391)
    (GamS_le (θ := 0.053571) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 17.453 ≤ 0.0801967) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [17.453, 17.522]`. -/
theorem shapeSaving_S23_cell_245 : ∀ c ∈ Icc (17.453 : ℝ) 17.522,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (16.65505 : ℝ) ≤ basePrunedS 6 17.453)
    (GamS_le (θ := 0.05354) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 17.522 ≤ 0.0804717) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [17.522, 17.6]`. -/
theorem shapeSaving_S23_cell_246 : ∀ c ∈ Icc (17.522 : ℝ) 17.6,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (16.7189 : ℝ) ≤ basePrunedS 6 17.522)
    (GamS_le (θ := 0.053506) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 17.6 ≤ 0.0807821) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [17.6, 17.688]`. -/
theorem shapeSaving_S23_cell_247 : ∀ c ∈ Icc (17.6 : ℝ) 17.688,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (16.79106 : ℝ) ≤ basePrunedS 6 17.6)
    (GamS_le (θ := 0.053467) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 17.688 ≤ 0.0811288) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [17.688, 17.78]`. -/
theorem shapeSaving_S23_cell_248 : ∀ c ∈ Icc (17.688 : ℝ) 17.78,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (16.87247 : ℝ) ≤ basePrunedS 6 17.688)
    (GamS_le (θ := 0.053427) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 17.78 ≤ 0.0814895) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [17.78, 17.89]`. -/
theorem shapeSaving_S23_cell_249 : ∀ c ∈ Icc (17.78 : ℝ) 17.89,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (16.95756 : ℝ) ≤ basePrunedS 6 17.78)
    (GamS_le (θ := 0.053379) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 17.89 ≤ 0.0819166) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [17.89, 18.02]`. -/
theorem shapeSaving_S23_cell_250 : ∀ c ∈ Icc (17.89 : ℝ) 18.02,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (17.05928 : ℝ) ≤ basePrunedS 6 17.89)
    (GamS_le (θ := 0.053323) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 18.02 ≤ 0.0824181) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [18.02, 18.17]`. -/
theorem shapeSaving_S23_cell_251 : ∀ c ∈ Icc (18.02 : ℝ) 18.17,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (17.17947 : ℝ) ≤ basePrunedS 6 18.02)
    (GamS_le (θ := 0.05326) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 18.17 ≤ 0.0829904) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [18.17, 18.35]`. -/
theorem shapeSaving_S23_cell_252 : ∀ c ∈ Icc (18.17 : ℝ) 18.35,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (17.31811 : ℝ) ≤ basePrunedS 6 18.17)
    (GamS_le (θ := 0.053184) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 18.35 ≤ 0.0836677) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [18.35, 18.56]`. -/
theorem shapeSaving_S23_cell_253 : ∀ c ∈ Icc (18.35 : ℝ) 18.56,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (17.48444 : ℝ) ≤ basePrunedS 6 18.35)
    (GamS_le (θ := 0.053097) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 18.56 ≤ 0.0844486) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [18.56, 18.82]`. -/
theorem shapeSaving_S23_cell_254 : ∀ c ∈ Icc (18.56 : ℝ) 18.82,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (17.67843 : ℝ) ≤ basePrunedS 6 18.56)
    (GamS_le (θ := 0.052992) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 18.82 ≤ 0.085398) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [18.82, 19.15]`. -/
theorem shapeSaving_S23_cell_255 : ∀ c ∈ Icc (18.82 : ℝ) 19.15,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (17.9185 : ℝ) ≤ basePrunedS 6 18.82)
    (GamS_le (θ := 0.052861) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 19.15 ≤ 0.0865787) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [19.15, 19.57]`. -/
theorem shapeSaving_S23_cell_256 : ∀ c ∈ Icc (19.15 : ℝ) 19.57,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (18.22307 : ℝ) ≤ basePrunedS 6 19.15)
    (GamS_le (θ := 0.052698) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 19.57 ≤ 0.0880418) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [19.57, 20.12]`. -/
theorem shapeSaving_S23_cell_257 : ∀ c ∈ Icc (19.57 : ℝ) 20.12,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (18.61048 : ℝ) ≤ basePrunedS 6 19.57)
    (GamS_le (θ := 0.052492) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 20.12 ≤ 0.0898964) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [20.12, 20.88]`. -/
theorem shapeSaving_S23_cell_258 : ∀ c ∈ Icc (20.12 : ℝ) 20.88,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (19.11743 : ℝ) ≤ basePrunedS 6 20.12)
    (GamS_le (θ := 0.05222) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 20.88 ≤ 0.0923521) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [20.88, 21.9]`. -/
theorem shapeSaving_S23_cell_259 : ∀ c ∈ Icc (20.88 : ℝ) 21.9,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (19.81731 : ℝ) ≤ basePrunedS 6 20.88)
    (GamS_le (θ := 0.051875) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 21.9 ≤ 0.0954678) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [21.9, 23.6]`. -/
theorem shapeSaving_S23_cell_260 : ∀ c ∈ Icc (21.9 : ℝ) 23.6,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 4 3 : (20.75553 : ℝ) ≤ basePrunedS 6 21.9)
    (GamS_le (θ := 0.051345) (gammaXS_le 4 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 23.6 ≤ 0.1002572) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [23.6, 26.6]`. -/
theorem shapeSaving_S23_cell_261 : ∀ c ∈ Icc (23.6 : ℝ) 26.6,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 5 3 : (22.31675 : ℝ) ≤ basePrunedS 6 23.6)
    (GamS_le (θ := 0.050525) (gammaXS_le 5 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 26.6 ≤ 0.1076996) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [26.6, 33.3]`. -/
theorem shapeSaving_S23_cell_262 : ∀ c ∈ Icc (26.6 : ℝ) 33.3,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 5 3 : (25.06545 : ℝ) ≤ basePrunedS 6 26.6)
    (GamS_le (θ := 0.049068) (gammaXS_le 5 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 33.3 ≤ 0.120982) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [33.3, 58]`. -/
theorem shapeSaving_S23_cell_263 : ∀ c ∈ Icc (33.3 : ℝ) 58,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 5 3 : (31.1821 : ℝ) ≤ basePrunedS 6 33.3)
    (GamS_le (θ := 0.045863) (gammaXS_le 6 3 1)
      (gammaQS_le (-4) 3 1) : GamS 6 2 58 ≤ 0.1505274) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c ∈ [58, 200]`. -/
theorem shapeSaving_S23_cell_264 : ∀ c ∈ Icc (58 : ℝ) 200,
    shapeSaving 6 2 c < 0.001669 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 1
    (le_basePrunedS 6 3 : (53.59102 : ℝ) ≤ basePrunedS 6 58)
    (GamS_le (θ := 0.040171) (gammaXS_le 8 3 1)
      (gammaQS_le (-5) 3 1) : GamS 6 2 200 ≤ 0.2041162) hc

/-- `shapeSaving 6 2 c < 0.001669` for `c` in `[16.975, 200]`: cells 232 to 264. -/
theorem shapeSaving_S23_block_6 : ∀ c ∈ Icc (16.975 : ℝ) 200,
    shapeSaving 6 2 c < 0.001669 := by
  have h := shapeSaving_S23_cell_232
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_233
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_234
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_235
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_236
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_237
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_238
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_239
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_240
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_241
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_242
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_243
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_244
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_245
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_246
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_247
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_248
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_249
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_250
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_251
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_252
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_253
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_254
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_255
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_256
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_257
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_258
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_259
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_260
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_261
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_262
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_263
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_cell_264
  exact h

end ImprovedExponents
