module

public import ImprovedExponents.Optimum.Shapes.Cells_S23_1
public import ImprovedExponents.Optimum.Shapes.Cells_S23_2
public import ImprovedExponents.Optimum.Shapes.Cells_S23_3
public import ImprovedExponents.Optimum.Shapes.Cells_S23_4
public import ImprovedExponents.Optimum.Shapes.Cells_S23_5
public import ImprovedExponents.Optimum.Shapes.Cells_S23_6

@[expose] public section

/-!
# The saving with the shape `(2, 3)` on `(7, 200]`

This file is generated by `python3 -m search.certs`; do not edit it. It joins the
264 cells of the files `Cells_S23_1.lean` to `Cells_S23_6.lean` into three ranges:

* `shapeSaving_S23_lt_below`: `shapeSaving 6 2 c < 0.001669` for `7 < c ≤ 15.4`;
* `shapeSaving_S23_lt_window`: `shapeSaving 6 2 c < 0.001671` for `15.4 ≤ c ≤ 16.7`;
* `shapeSaving_S23_lt_above`: `shapeSaving 6 2 c < 0.001669` for `16.7 ≤ c ≤ 200`.

For a shape it also has the tail `shapeSaving_S23_lt_tail` (`c ≥ 200`) and the witness
`shapeSaving_S23_witness` at `c = 16`.
-/

namespace ImprovedExponents

open Set

/-- `shapeSaving 6 2 c < 0.001669` for `c` in `(7, 15.4]`. -/
theorem shapeSaving_S23_lt_below : ∀ c ∈ Ioc (7 : ℝ) 15.4,
    shapeSaving 6 2 c < 0.001669 :=
  shapeSaving_S23_block_1

/-- `shapeSaving 6 2 c < 0.001671` for `c` in `[15.4, 16.7]`. -/
theorem shapeSaving_S23_lt_window : ∀ c ∈ Icc (15.4 : ℝ) 16.7,
    shapeSaving 6 2 c < 0.001671 := by
  have h := shapeSaving_S23_block_2
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_block_3
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_block_4
  exact h

/-- `shapeSaving 6 2 c < 0.001669` for `c` in `[16.7, 200]`. -/
theorem shapeSaving_S23_lt_above : ∀ c ∈ Icc (16.7 : ℝ) 200,
    shapeSaving 6 2 c < 0.001669 := by
  have h := shapeSaving_S23_block_5
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S23_block_6
  exact h

/-- The tail: `shapeSaving 6 2 c < 0.001669` for `c ≥ 200`, because `Γ(c) < 2/3`. -/
theorem shapeSaving_S23_lt_tail {c : ℝ} (hc : 200 ≤ c) :
    shapeSaving 6 2 c < 0.001669 :=
  shapeSaving_lt_of_le 1 (le_basePrunedS 8 3 :
    (181.42793 : ℝ) ≤ basePrunedS 6 200) hc

/-- The witness: `0.001669 < shapeSaving 6 2 c` at `c = 16`. -/
theorem shapeSaving_S23_witness : (0.001669 : ℝ) < shapeSaving 6 2 16 :=
  lt_savingS 1 (basePrunedS_pos (by norm_num) (by norm_num))
    (basePrunedS_le 4 3 : basePrunedS 6 16 ≤ 15.30854)
    (le_GamS (θ := 0.054258) (le_gammaXS 4 3 1)
      (le_gammaQS (-4) 3 1) : (0.0740296 : ℝ) ≤ GamS 6 2 16)

end ImprovedExponents
