module

public import ImprovedExponents.Optimum.Shapes.NumLog

@[expose] public section

/-!
# The saving with the shape `(2, 5)` on `[24.455, 25.2]`: cells 182 to 227

This file is generated by `python3 -m search.certs`; do not edit it. Each lemma bounds
`shapeSaving 10 4 c` on one cell `[c₁, c₂]` by `F(A(c₁), Γ(c₂))`, with certified rational bounds
on `A(c₁)` and `Γ(c₂)`; the last lemma joins the cells.
-/

namespace ImprovedExponents

open Set

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.455, 24.464]`. -/
theorem shapeSaving_S25_cell_182 : ∀ c ∈ Icc (24.455 : ℝ) 24.464,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.09161 : ℝ) ≤ basePrunedS 10 24.455)
    (GamS_le (θ := 0.11354) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.464 ≤ 0.0748868) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.464, 24.473]`. -/
theorem shapeSaving_S25_cell_183 : ∀ c ∈ Icc (24.464 : ℝ) 24.473,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.10216 : ℝ) ≤ basePrunedS 10 24.464)
    (GamS_le (θ := 0.113533) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.473 ≤ 0.0749135) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.473, 24.483]`. -/
theorem shapeSaving_S25_cell_184 : ∀ c ∈ Icc (24.473 : ℝ) 24.483,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.11271 : ℝ) ≤ basePrunedS 10 24.473)
    (GamS_le (θ := 0.113526) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.483 ≤ 0.074943) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.483, 24.493]`. -/
theorem shapeSaving_S25_cell_185 : ∀ c ∈ Icc (24.483 : ℝ) 24.493,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.12443 : ℝ) ≤ basePrunedS 10 24.483)
    (GamS_le (θ := 0.113519) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.493 ≤ 0.0749729) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.493, 24.503]`. -/
theorem shapeSaving_S25_cell_186 : ∀ c ∈ Icc (24.493 : ℝ) 24.503,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.13615 : ℝ) ≤ basePrunedS 10 24.493)
    (GamS_le (θ := 0.113512) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.503 ≤ 0.0750027) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.503, 24.513]`. -/
theorem shapeSaving_S25_cell_187 : ∀ c ∈ Icc (24.503 : ℝ) 24.513,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.14788 : ℝ) ≤ basePrunedS 10 24.503)
    (GamS_le (θ := 0.113505) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.513 ≤ 0.0750325) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.513, 24.523]`. -/
theorem shapeSaving_S25_cell_188 : ∀ c ∈ Icc (24.513 : ℝ) 24.523,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.1596 : ℝ) ≤ basePrunedS 10 24.513)
    (GamS_le (θ := 0.113498) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.523 ≤ 0.0750623) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.523, 24.533]`. -/
theorem shapeSaving_S25_cell_189 : ∀ c ∈ Icc (24.523 : ℝ) 24.533,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.17132 : ℝ) ≤ basePrunedS 10 24.523)
    (GamS_le (θ := 0.113491) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.533 ≤ 0.075092) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.533, 24.544]`. -/
theorem shapeSaving_S25_cell_190 : ∀ c ∈ Icc (24.533 : ℝ) 24.544,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.18304 : ℝ) ≤ basePrunedS 10 24.533)
    (GamS_le (θ := 0.113483) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.544 ≤ 0.0751245) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.544, 24.555]`. -/
theorem shapeSaving_S25_cell_191 : ∀ c ∈ Icc (24.544 : ℝ) 24.555,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.19593 : ℝ) ≤ basePrunedS 10 24.544)
    (GamS_le (θ := 0.113475) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.555 ≤ 0.075157) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.555, 24.566]`. -/
theorem shapeSaving_S25_cell_192 : ∀ c ∈ Icc (24.555 : ℝ) 24.566,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.20883 : ℝ) ≤ basePrunedS 10 24.555)
    (GamS_le (θ := 0.113467) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.566 ≤ 0.0751901) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.566, 24.577]`. -/
theorem shapeSaving_S25_cell_193 : ∀ c ∈ Icc (24.566 : ℝ) 24.577,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.22172 : ℝ) ≤ basePrunedS 10 24.566)
    (GamS_le (θ := 0.11346) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.577 ≤ 0.0752226) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.577, 24.588]`. -/
theorem shapeSaving_S25_cell_194 : ∀ c ∈ Icc (24.577 : ℝ) 24.588,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.23461 : ℝ) ≤ basePrunedS 10 24.577)
    (GamS_le (θ := 0.113452) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.588 ≤ 0.075255) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.588, 24.6]`. -/
theorem shapeSaving_S25_cell_195 : ∀ c ∈ Icc (24.588 : ℝ) 24.6,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.2475 : ℝ) ≤ basePrunedS 10 24.588)
    (GamS_le (θ := 0.113443) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.6 ≤ 0.0752907) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.6, 24.612]`. -/
theorem shapeSaving_S25_cell_196 : ∀ c ∈ Icc (24.6 : ℝ) 24.612,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.26157 : ℝ) ≤ basePrunedS 10 24.6)
    (GamS_le (θ := 0.113435) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.612 ≤ 0.075326) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.612, 24.624]`. -/
theorem shapeSaving_S25_cell_197 : ∀ c ∈ Icc (24.612 : ℝ) 24.624,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.27563 : ℝ) ≤ basePrunedS 10 24.612)
    (GamS_le (θ := 0.113427) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.624 ≤ 0.0753618) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.624, 24.636]`. -/
theorem shapeSaving_S25_cell_198 : ∀ c ∈ Icc (24.624 : ℝ) 24.636,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.2897 : ℝ) ≤ basePrunedS 10 24.624)
    (GamS_le (θ := 0.113418) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.636 ≤ 0.0753968) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.636, 24.649]`. -/
theorem shapeSaving_S25_cell_199 : ∀ c ∈ Icc (24.636 : ℝ) 24.649,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.30376 : ℝ) ≤ basePrunedS 10 24.636)
    (GamS_le (θ := 0.113409) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.649 ≤ 0.0754353) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.649, 24.662]`. -/
theorem shapeSaving_S25_cell_200 : ∀ c ∈ Icc (24.649 : ℝ) 24.662,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.319 : ℝ) ≤ basePrunedS 10 24.649)
    (GamS_le (θ := 0.1134) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.662 ≤ 0.0754737) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.662, 24.675]`. -/
theorem shapeSaving_S25_cell_201 : ∀ c ∈ Icc (24.662 : ℝ) 24.675,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.33423 : ℝ) ≤ basePrunedS 10 24.662)
    (GamS_le (θ := 0.113391) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.675 ≤ 0.0755121) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.675, 24.689]`. -/
theorem shapeSaving_S25_cell_202 : ∀ c ∈ Icc (24.675 : ℝ) 24.689,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.34947 : ℝ) ≤ basePrunedS 10 24.675)
    (GamS_le (θ := 0.113381) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.689 ≤ 0.0755533) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.689, 24.703]`. -/
theorem shapeSaving_S25_cell_203 : ∀ c ∈ Icc (24.689 : ℝ) 24.703,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.36588 : ℝ) ≤ basePrunedS 10 24.689)
    (GamS_le (θ := 0.113371) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.703 ≤ 0.0755943) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.703, 24.717]`. -/
theorem shapeSaving_S25_cell_204 : ∀ c ∈ Icc (24.703 : ℝ) 24.717,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.38228 : ℝ) ≤ basePrunedS 10 24.703)
    (GamS_le (θ := 0.113361) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.717 ≤ 0.0756354) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.717, 24.732]`. -/
theorem shapeSaving_S25_cell_205 : ∀ c ∈ Icc (24.717 : ℝ) 24.732,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.39869 : ℝ) ≤ basePrunedS 10 24.717)
    (GamS_le (θ := 0.113351) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.732 ≤ 0.0756798) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.732, 24.747]`. -/
theorem shapeSaving_S25_cell_206 : ∀ c ∈ Icc (24.732 : ℝ) 24.747,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.41627 : ℝ) ≤ basePrunedS 10 24.732)
    (GamS_le (θ := 0.11334) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.747 ≤ 0.0757235) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.747, 24.762]`. -/
theorem shapeSaving_S25_cell_207 : ∀ c ∈ Icc (24.747 : ℝ) 24.762,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.43385 : ℝ) ≤ basePrunedS 10 24.747)
    (GamS_le (θ := 0.11333) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.762 ≤ 0.0757679) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.762, 24.778]`. -/
theorem shapeSaving_S25_cell_208 : ∀ c ∈ Icc (24.762 : ℝ) 24.778,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.45143 : ℝ) ≤ basePrunedS 10 24.762)
    (GamS_le (θ := 0.113318) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.778 ≤ 0.0758148) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.778, 24.794]`. -/
theorem shapeSaving_S25_cell_209 : ∀ c ∈ Icc (24.778 : ℝ) 24.794,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.47018 : ℝ) ≤ basePrunedS 10 24.778)
    (GamS_le (θ := 0.113307) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.794 ≤ 0.0758612) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.794, 24.811]`. -/
theorem shapeSaving_S25_cell_210 : ∀ c ∈ Icc (24.794 : ℝ) 24.811,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.48893 : ℝ) ≤ basePrunedS 10 24.794)
    (GamS_le (θ := 0.113295) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.811 ≤ 0.0759112) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.811, 24.828]`. -/
theorem shapeSaving_S25_cell_211 : ∀ c ∈ Icc (24.811 : ℝ) 24.828,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.50885 : ℝ) ≤ basePrunedS 10 24.811)
    (GamS_le (θ := 0.113284) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.828 ≤ 0.0759611) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.828, 24.846]`. -/
theorem shapeSaving_S25_cell_212 : ∀ c ∈ Icc (24.828 : ℝ) 24.846,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.52877 : ℝ) ≤ basePrunedS 10 24.828)
    (GamS_le (θ := 0.113271) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.846 ≤ 0.0760133) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.846, 24.865]`. -/
theorem shapeSaving_S25_cell_213 : ∀ c ∈ Icc (24.846 : ℝ) 24.865,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.54987 : ℝ) ≤ basePrunedS 10 24.846)
    (GamS_le (θ := 0.113258) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.865 ≤ 0.0760689) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.865, 24.884]`. -/
theorem shapeSaving_S25_cell_214 : ∀ c ∈ Icc (24.865 : ℝ) 24.884,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.57213 : ℝ) ≤ basePrunedS 10 24.865)
    (GamS_le (θ := 0.113245) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.884 ≤ 0.0761245) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.884, 24.904]`. -/
theorem shapeSaving_S25_cell_215 : ∀ c ∈ Icc (24.884 : ℝ) 24.904,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.59439 : ℝ) ≤ basePrunedS 10 24.884)
    (GamS_le (θ := 0.113231) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.904 ≤ 0.0761826) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.904, 24.925]`. -/
theorem shapeSaving_S25_cell_216 : ∀ c ∈ Icc (24.904 : ℝ) 24.925,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.61783 : ℝ) ≤ basePrunedS 10 24.904)
    (GamS_le (θ := 0.113216) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.925 ≤ 0.0762434) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.925, 24.947]`. -/
theorem shapeSaving_S25_cell_217 : ∀ c ∈ Icc (24.925 : ℝ) 24.947,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.64244 : ℝ) ≤ basePrunedS 10 24.925)
    (GamS_le (θ := 0.113201) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.947 ≤ 0.0763075) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.947, 24.969]`. -/
theorem shapeSaving_S25_cell_218 : ∀ c ∈ Icc (24.947 : ℝ) 24.969,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.66822 : ℝ) ≤ basePrunedS 10 24.947)
    (GamS_le (θ := 0.113186) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.969 ≤ 0.0763715) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.969, 24.992]`. -/
theorem shapeSaving_S25_cell_219 : ∀ c ∈ Icc (24.969 : ℝ) 24.992,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.69399 : ℝ) ≤ basePrunedS 10 24.969)
    (GamS_le (θ := 0.11317) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.992 ≤ 0.0764381) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.992, 25.016]`. -/
theorem shapeSaving_S25_cell_220 : ∀ c ∈ Icc (24.992 : ℝ) 25.016,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.72094 : ℝ) ≤ basePrunedS 10 24.992)
    (GamS_le (θ := 0.113153) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 25.016 ≤ 0.0765072) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [25.016, 25.041]`. -/
theorem shapeSaving_S25_cell_221 : ∀ c ∈ Icc (25.016 : ℝ) 25.041,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.74906 : ℝ) ≤ basePrunedS 10 25.016)
    (GamS_le (θ := 0.113136) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 25.041 ≤ 0.0765796) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [25.041, 25.067]`. -/
theorem shapeSaving_S25_cell_222 : ∀ c ∈ Icc (25.041 : ℝ) 25.067,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.77836 : ℝ) ≤ basePrunedS 10 25.041)
    (GamS_le (θ := 0.113118) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 25.067 ≤ 0.0766546) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [25.067, 25.095]`. -/
theorem shapeSaving_S25_cell_223 : ∀ c ∈ Icc (25.067 : ℝ) 25.095,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.80882 : ℝ) ≤ basePrunedS 10 25.067)
    (GamS_le (θ := 0.113099) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 25.095 ≤ 0.0767355) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [25.095, 25.124]`. -/
theorem shapeSaving_S25_cell_224 : ∀ c ∈ Icc (25.095 : ℝ) 25.124,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.84163 : ℝ) ≤ basePrunedS 10 25.095)
    (GamS_le (θ := 0.113079) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 25.124 ≤ 0.0768189) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [25.124, 25.154]`. -/
theorem shapeSaving_S25_cell_225 : ∀ c ∈ Icc (25.124 : ℝ) 25.154,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.8756 : ℝ) ≤ basePrunedS 10 25.124)
    (GamS_le (θ := 0.113058) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 25.154 ≤ 0.0769054) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [25.154, 25.186]`. -/
theorem shapeSaving_S25_cell_226 : ∀ c ∈ Icc (25.154 : ℝ) 25.186,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.91075 : ℝ) ≤ basePrunedS 10 25.154)
    (GamS_le (θ := 0.113037) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 25.186 ≤ 0.0769973) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [25.186, 25.2]`. -/
theorem shapeSaving_S25_cell_227 : ∀ c ∈ Icc (25.186 : ℝ) 25.2,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.94824 : ℝ) ≤ basePrunedS 10 25.186)
    (GamS_le (θ := 0.113027) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 25.2 ≤ 0.0770371) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c` in `[24.455, 25.2]`: cells 182 to 227. -/
theorem shapeSaving_S25_block_5 : ∀ c ∈ Icc (24.455 : ℝ) 25.2,
    shapeSaving 10 4 c < 0.001778 := by
  have h := shapeSaving_S25_cell_182
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_183
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_184
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_185
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_186
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_187
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_188
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_189
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_190
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_191
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_192
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_193
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_194
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_195
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_196
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_197
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_198
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_199
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_200
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_201
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_202
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_203
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_204
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_205
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_206
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_207
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_208
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_209
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_210
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_211
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_212
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_213
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_214
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_215
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_216
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_217
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_218
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_219
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_220
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_221
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_222
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_223
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_224
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_225
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_226
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_227
  exact h

end ImprovedExponents
