module

public import ImprovedExponents.Optimum.Shapes.NumLog

@[expose] public section

/-!
# The saving with the shape `(2, 5)` on `[24.0482, 24.455]`: cells 136 to 181

This file is generated by `python3 -m search.certs`; do not edit it. Each lemma bounds
`shapeSaving 10 4 c` on one cell `[c₁, c₂]` by `F(A(c₁), Γ(c₂))`, with certified rational bounds
on `A(c₁)` and `Γ(c₂)`; the last lemma joins the cells.
-/

namespace ImprovedExponents

open Set

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.0482, 24.0576]`. -/
theorem shapeSaving_S25_cell_136 : ∀ c ∈ Icc (24.0482 : ℝ) 24.0576,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.6147 : ℝ) ≤ basePrunedS 10 24.0482)
    (GamS_le (θ := 0.113832) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.0576 ≤ 0.0736617) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.0576, 24.0669]`. -/
theorem shapeSaving_S25_cell_137 : ∀ c ∈ Icc (24.0576 : ℝ) 24.0669,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.62572 : ℝ) ≤ basePrunedS 10 24.0576)
    (GamS_le (θ := 0.113825) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.0669 ≤ 0.07369) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.0669, 24.076]`. -/
theorem shapeSaving_S25_cell_138 : ∀ c ∈ Icc (24.0669 : ℝ) 24.076,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.63663 : ℝ) ≤ basePrunedS 10 24.0669)
    (GamS_le (θ := 0.113819) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.076 ≤ 0.0737181) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.076, 24.0851]`. -/
theorem shapeSaving_S25_cell_139 : ∀ c ∈ Icc (24.076 : ℝ) 24.0851,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.6473 : ℝ) ≤ basePrunedS 10 24.076)
    (GamS_le (θ := 0.113812) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.0851 ≤ 0.0737455) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.0851, 24.0941]`. -/
theorem shapeSaving_S25_cell_140 : ∀ c ∈ Icc (24.0851 : ℝ) 24.0941,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.65797 : ℝ) ≤ basePrunedS 10 24.0851)
    (GamS_le (θ := 0.113806) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.0941 ≤ 0.0737732) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.0941, 24.1031]`. -/
theorem shapeSaving_S25_cell_141 : ∀ c ∈ Icc (24.0941 : ℝ) 24.1031,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.66852 : ℝ) ≤ basePrunedS 10 24.0941)
    (GamS_le (θ := 0.113799) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.1031 ≤ 0.0738003) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.1031, 24.1119]`. -/
theorem shapeSaving_S25_cell_142 : ∀ c ∈ Icc (24.1031 : ℝ) 24.1119,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.67907 : ℝ) ≤ basePrunedS 10 24.1031)
    (GamS_le (θ := 0.113793) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.1119 ≤ 0.0738273) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.1119, 24.1208]`. -/
theorem shapeSaving_S25_cell_143 : ∀ c ∈ Icc (24.1119 : ℝ) 24.1208,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.68939 : ℝ) ≤ basePrunedS 10 24.1119)
    (GamS_le (θ := 0.113786) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.1208 ≤ 0.073854) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.1208, 24.1296]`. -/
theorem shapeSaving_S25_cell_144 : ∀ c ∈ Icc (24.1208 : ℝ) 24.1296,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.69983 : ℝ) ≤ basePrunedS 10 24.1208)
    (GamS_le (θ := 0.11378) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.1296 ≤ 0.0738809) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.1296, 24.1382]`. -/
theorem shapeSaving_S25_cell_145 : ∀ c ∈ Icc (24.1296 : ℝ) 24.1382,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.71014 : ℝ) ≤ basePrunedS 10 24.1296)
    (GamS_le (θ := 0.113774) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.1382 ≤ 0.0739072) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.1382, 24.147]`. -/
theorem shapeSaving_S25_cell_146 : ∀ c ∈ Icc (24.1382 : ℝ) 24.147,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.72023 : ℝ) ≤ basePrunedS 10 24.1382)
    (GamS_le (θ := 0.113767) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.147 ≤ 0.0739335) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.147, 24.1557]`. -/
theorem shapeSaving_S25_cell_147 : ∀ c ∈ Icc (24.147 : ℝ) 24.1557,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.73054 : ℝ) ≤ basePrunedS 10 24.147)
    (GamS_le (θ := 0.113761) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.1557 ≤ 0.07396) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.1557, 24.1643]`. -/
theorem shapeSaving_S25_cell_148 : ∀ c ∈ Icc (24.1557 : ℝ) 24.1643,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.74074 : ℝ) ≤ basePrunedS 10 24.1557)
    (GamS_le (θ := 0.113755) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.1643 ≤ 0.0739863) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.1643, 24.1728]`. -/
theorem shapeSaving_S25_cell_149 : ∀ c ∈ Icc (24.1643 : ℝ) 24.1728,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.75083 : ℝ) ≤ basePrunedS 10 24.1643)
    (GamS_le (θ := 0.113749) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.1728 ≤ 0.0740121) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.1728, 24.1814]`. -/
theorem shapeSaving_S25_cell_150 : ∀ c ∈ Icc (24.1728 : ℝ) 24.1814,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.76079 : ℝ) ≤ basePrunedS 10 24.1728)
    (GamS_le (θ := 0.113742) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.1814 ≤ 0.0740377) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.1814, 24.19]`. -/
theorem shapeSaving_S25_cell_151 : ∀ c ∈ Icc (24.1814 : ℝ) 24.19,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.77088 : ℝ) ≤ basePrunedS 10 24.1814)
    (GamS_le (θ := 0.113736) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.19 ≤ 0.0740638) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.19, 24.1985]`. -/
theorem shapeSaving_S25_cell_152 : ∀ c ∈ Icc (24.19 : ℝ) 24.1985,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.78096 : ℝ) ≤ basePrunedS 10 24.19)
    (GamS_le (θ := 0.11373) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.1985 ≤ 0.0740896) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.1985, 24.207]`. -/
theorem shapeSaving_S25_cell_153 : ∀ c ∈ Icc (24.1985 : ℝ) 24.207,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.79092 : ℝ) ≤ basePrunedS 10 24.1985)
    (GamS_le (θ := 0.113724) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.207 ≤ 0.0741154) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.207, 24.2154]`. -/
theorem shapeSaving_S25_cell_154 : ∀ c ∈ Icc (24.207 : ℝ) 24.2154,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.80089 : ℝ) ≤ basePrunedS 10 24.207)
    (GamS_le (θ := 0.113718) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.2154 ≤ 0.0741408) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.2154, 24.2238]`. -/
theorem shapeSaving_S25_cell_155 : ∀ c ∈ Icc (24.2154 : ℝ) 24.2238,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.81074 : ℝ) ≤ basePrunedS 10 24.2154)
    (GamS_le (θ := 0.113712) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.2238 ≤ 0.0741662) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.2238, 24.2322]`. -/
theorem shapeSaving_S25_cell_156 : ∀ c ∈ Icc (24.2238 : ℝ) 24.2322,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.82058 : ℝ) ≤ basePrunedS 10 24.2238)
    (GamS_le (θ := 0.113706) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.2322 ≤ 0.0741916) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.2322, 24.2406]`. -/
theorem shapeSaving_S25_cell_157 : ∀ c ∈ Icc (24.2322 : ℝ) 24.2406,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.83043 : ℝ) ≤ basePrunedS 10 24.2322)
    (GamS_le (θ := 0.1137) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.2406 ≤ 0.074217) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.2406, 24.249]`. -/
theorem shapeSaving_S25_cell_158 : ∀ c ∈ Icc (24.2406 : ℝ) 24.249,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.84028 : ℝ) ≤ basePrunedS 10 24.2406)
    (GamS_le (θ := 0.113694) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.249 ≤ 0.0742424) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.249, 24.2574]`. -/
theorem shapeSaving_S25_cell_159 : ∀ c ∈ Icc (24.249 : ℝ) 24.2574,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.85013 : ℝ) ≤ basePrunedS 10 24.249)
    (GamS_le (θ := 0.113688) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.2574 ≤ 0.0742677) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.2574, 24.2658]`. -/
theorem shapeSaving_S25_cell_160 : ∀ c ∈ Icc (24.2574 : ℝ) 24.2658,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.85998 : ℝ) ≤ basePrunedS 10 24.2574)
    (GamS_le (θ := 0.113682) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.2658 ≤ 0.0742931) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.2658, 24.2744]`. -/
theorem shapeSaving_S25_cell_161 : ∀ c ∈ Icc (24.2658 : ℝ) 24.2744,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.86982 : ℝ) ≤ basePrunedS 10 24.2658)
    (GamS_le (θ := 0.113675) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.2744 ≤ 0.0743184) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.2744, 24.283]`. -/
theorem shapeSaving_S25_cell_162 : ∀ c ∈ Icc (24.2744 : ℝ) 24.283,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.87991 : ℝ) ≤ basePrunedS 10 24.2744)
    (GamS_le (θ := 0.113669) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.283 ≤ 0.0743444) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.283, 24.2916]`. -/
theorem shapeSaving_S25_cell_163 : ∀ c ∈ Icc (24.283 : ℝ) 24.2916,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.88999 : ℝ) ≤ basePrunedS 10 24.283)
    (GamS_le (θ := 0.113663) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.2916 ≤ 0.0743704) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.2916, 24.3002]`. -/
theorem shapeSaving_S25_cell_164 : ∀ c ∈ Icc (24.2916 : ℝ) 24.3002,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.90007 : ℝ) ≤ basePrunedS 10 24.2916)
    (GamS_le (θ := 0.113657) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.3002 ≤ 0.0743964) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.3002, 24.3088]`. -/
theorem shapeSaving_S25_cell_165 : ∀ c ∈ Icc (24.3002 : ℝ) 24.3088,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.91015 : ℝ) ≤ basePrunedS 10 24.3002)
    (GamS_le (θ := 0.113651) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.3088 ≤ 0.0744224) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.3088, 24.3176]`. -/
theorem shapeSaving_S25_cell_166 : ∀ c ∈ Icc (24.3088 : ℝ) 24.3176,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.92023 : ℝ) ≤ basePrunedS 10 24.3088)
    (GamS_le (θ := 0.113644) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.3176 ≤ 0.0744483) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.3176, 24.3263]`. -/
theorem shapeSaving_S25_cell_167 : ∀ c ∈ Icc (24.3176 : ℝ) 24.3263,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.93055 : ℝ) ≤ basePrunedS 10 24.3176)
    (GamS_le (θ := 0.113638) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.3263 ≤ 0.0744746) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.3263, 24.335]`. -/
theorem shapeSaving_S25_cell_168 : ∀ c ∈ Icc (24.3263 : ℝ) 24.335,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.94075 : ℝ) ≤ basePrunedS 10 24.3263)
    (GamS_le (θ := 0.113632) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.335 ≤ 0.0745009) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.335, 24.3437]`. -/
theorem shapeSaving_S25_cell_169 : ∀ c ∈ Icc (24.335 : ℝ) 24.3437,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.95095 : ℝ) ≤ basePrunedS 10 24.335)
    (GamS_le (θ := 0.113626) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.3437 ≤ 0.0745272) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.3437, 24.3526]`. -/
theorem shapeSaving_S25_cell_170 : ∀ c ∈ Icc (24.3437 : ℝ) 24.3526,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.96115 : ℝ) ≤ basePrunedS 10 24.3437)
    (GamS_le (θ := 0.113619) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.3526 ≤ 0.0745534) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.3526, 24.3615]`. -/
theorem shapeSaving_S25_cell_171 : ∀ c ∈ Icc (24.3526 : ℝ) 24.3615,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.97158 : ℝ) ≤ basePrunedS 10 24.3526)
    (GamS_le (θ := 0.113613) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.3615 ≤ 0.0745804) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.3615, 24.3704]`. -/
theorem shapeSaving_S25_cell_172 : ∀ c ∈ Icc (24.3615 : ℝ) 24.3704,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.98201 : ℝ) ≤ basePrunedS 10 24.3615)
    (GamS_le (θ := 0.113607) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.3704 ≤ 0.0746073) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.3704, 24.3795]`. -/
theorem shapeSaving_S25_cell_173 : ∀ c ∈ Icc (24.3704 : ℝ) 24.3795,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (28.99244 : ℝ) ≤ basePrunedS 10 24.3704)
    (GamS_le (θ := 0.1136) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.3795 ≤ 0.0746342) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.3795, 24.3885]`. -/
theorem shapeSaving_S25_cell_174 : ∀ c ∈ Icc (24.3795 : ℝ) 24.3885,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.00311 : ℝ) ≤ basePrunedS 10 24.3795)
    (GamS_le (θ := 0.113594) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.3885 ≤ 0.0746615) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.3885, 24.3977]`. -/
theorem shapeSaving_S25_cell_175 : ∀ c ∈ Icc (24.3885 : ℝ) 24.3977,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.01366 : ℝ) ≤ basePrunedS 10 24.3885)
    (GamS_le (θ := 0.113587) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.3977 ≤ 0.0746887) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.3977, 24.4071]`. -/
theorem shapeSaving_S25_cell_176 : ∀ c ∈ Icc (24.3977 : ℝ) 24.4071,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.02445 : ℝ) ≤ basePrunedS 10 24.3977)
    (GamS_le (θ := 0.11358) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.4071 ≤ 0.0747166) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.4071, 24.4164]`. -/
theorem shapeSaving_S25_cell_177 : ∀ c ∈ Icc (24.4071 : ℝ) 24.4164,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.03547 : ℝ) ≤ basePrunedS 10 24.4071)
    (GamS_le (θ := 0.113574) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.4164 ≤ 0.0747448) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.4164, 24.4259]`. -/
theorem shapeSaving_S25_cell_178 : ∀ c ∈ Icc (24.4164 : ℝ) 24.4259,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.04637 : ℝ) ≤ basePrunedS 10 24.4164)
    (GamS_le (θ := 0.113567) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.4259 ≤ 0.074773) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.4259, 24.4355]`. -/
theorem shapeSaving_S25_cell_179 : ∀ c ∈ Icc (24.4259 : ℝ) 24.4355,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.0575 : ℝ) ≤ basePrunedS 10 24.4259)
    (GamS_le (θ := 0.11356) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.4355 ≤ 0.0748016) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.4355, 24.4452]`. -/
theorem shapeSaving_S25_cell_180 : ∀ c ∈ Icc (24.4355 : ℝ) 24.4452,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.06876 : ℝ) ≤ basePrunedS 10 24.4355)
    (GamS_le (θ := 0.113553) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.4452 ≤ 0.0748305) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c ∈ [24.4452, 24.455]`. -/
theorem shapeSaving_S25_cell_181 : ∀ c ∈ Icc (24.4452 : ℝ) 24.455,
    shapeSaving 10 4 c < 0.001778 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 3 : (29.08013 : ℝ) ≤ basePrunedS 10 24.4452)
    (GamS_le (θ := 0.113546) (gammaXS_le 5 3 2)
      (gammaQS_le (-3) 3 2) : GamS 10 4 24.455 ≤ 0.0748597) hc

/-- `shapeSaving 10 4 c < 0.001778` for `c` in `[24.0482, 24.455]`: cells 136 to 181. -/
theorem shapeSaving_S25_block_4 : ∀ c ∈ Icc (24.0482 : ℝ) 24.455,
    shapeSaving 10 4 c < 0.001778 := by
  have h := shapeSaving_S25_cell_136
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_137
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_138
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_139
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_140
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_141
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_142
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_143
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_144
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_145
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_146
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_147
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_148
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_149
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_150
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_151
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_152
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_153
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_154
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_155
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_156
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_157
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_158
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_159
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_160
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_161
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_162
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_163
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_164
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_165
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_166
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_167
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_168
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_169
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_170
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_171
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_172
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_173
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_174
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_175
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_176
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_177
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_178
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_179
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_180
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S25_cell_181
  exact h

end ImprovedExponents
