module

public import ImprovedExponents.Optimum.Shapes.NumLog

@[expose] public section

/-!
# The saving with the shape `(2, 4)` on `[19.6, 20.6]`: cells 80 to 134

This file is generated by `python3 -m search.certs`; do not edit it. Each lemma bounds
`shapeSaving 8 3 c` on one cell `[c₁, c₂]` by `F(A(c₁), Γ(c₂))`, with certified rational bounds
on `A(c₁)` and `Γ(c₂)`; the last lemma joins the cells.
-/

namespace ImprovedExponents

open Set

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [19.6, 19.623]`. -/
theorem shapeSaving_S24_cell_80 : ∀ c ∈ Icc (19.6 : ℝ) 19.623,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.31359 : ℝ) ≤ basePrunedS 8 19.6)
    (GamS_le (θ := 0.089861) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 19.623 ≤ 0.0731007) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [19.623, 19.646]`. -/
theorem shapeSaving_S24_cell_81 : ∀ c ∈ Icc (19.623 : ℝ) 19.646,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.3381 : ℝ) ≤ basePrunedS 8 19.623)
    (GamS_le (θ := 0.089845) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 19.646 ≤ 0.0731876) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [19.646, 19.668]`. -/
theorem shapeSaving_S24_cell_82 : ∀ c ∈ Icc (19.646 : ℝ) 19.668,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.36262 : ℝ) ≤ basePrunedS 8 19.646)
    (GamS_le (θ := 0.089829) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 19.668 ≤ 0.07327) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [19.668, 19.689]`. -/
theorem shapeSaving_S24_cell_83 : ∀ c ∈ Icc (19.668 : ℝ) 19.689,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.38607 : ℝ) ≤ basePrunedS 8 19.668)
    (GamS_le (θ := 0.089814) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 19.689 ≤ 0.0733488) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [19.689, 19.71]`. -/
theorem shapeSaving_S24_cell_84 : ∀ c ∈ Icc (19.689 : ℝ) 19.71,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.40845 : ℝ) ≤ basePrunedS 8 19.689)
    (GamS_le (θ := 0.0898) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 19.71 ≤ 0.0734283) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [19.71, 19.73]`. -/
theorem shapeSaving_S24_cell_85 : ∀ c ∈ Icc (19.71 : ℝ) 19.73,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.43083 : ℝ) ≤ basePrunedS 8 19.71)
    (GamS_le (θ := 0.089785) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 19.73 ≤ 0.0735032) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [19.73, 19.75]`. -/
theorem shapeSaving_S24_cell_86 : ∀ c ∈ Icc (19.73 : ℝ) 19.75,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.45214 : ℝ) ≤ basePrunedS 8 19.73)
    (GamS_le (θ := 0.089771) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 19.75 ≤ 0.0735779) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [19.75, 19.769]`. -/
theorem shapeSaving_S24_cell_87 : ∀ c ∈ Icc (19.75 : ℝ) 19.769,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.47346 : ℝ) ≤ basePrunedS 8 19.75)
    (GamS_le (θ := 0.089758) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 19.769 ≤ 0.0736487) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [19.769, 19.788]`. -/
theorem shapeSaving_S24_cell_88 : ∀ c ∈ Icc (19.769 : ℝ) 19.788,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.49371 : ℝ) ≤ basePrunedS 8 19.769)
    (GamS_le (θ := 0.089745) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 19.788 ≤ 0.0737199) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [19.788, 19.806]`. -/
theorem shapeSaving_S24_cell_89 : ∀ c ∈ Icc (19.788 : ℝ) 19.806,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.51395 : ℝ) ≤ basePrunedS 8 19.788)
    (GamS_le (θ := 0.089732) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 19.806 ≤ 0.0737866) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [19.806, 19.824]`. -/
theorem shapeSaving_S24_cell_90 : ∀ c ∈ Icc (19.806 : ℝ) 19.824,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.53314 : ℝ) ≤ basePrunedS 8 19.806)
    (GamS_le (θ := 0.08972) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 19.824 ≤ 0.0738542) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [19.824, 19.842]`. -/
theorem shapeSaving_S24_cell_91 : ∀ c ∈ Icc (19.824 : ℝ) 19.842,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.55232 : ℝ) ≤ basePrunedS 8 19.824)
    (GamS_le (θ := 0.089707) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 19.842 ≤ 0.0739207) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [19.842, 19.86]`. -/
theorem shapeSaving_S24_cell_92 : ∀ c ∈ Icc (19.842 : ℝ) 19.86,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.5715 : ℝ) ≤ basePrunedS 8 19.842)
    (GamS_le (θ := 0.089695) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 19.86 ≤ 0.0739881) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [19.86, 19.877]`. -/
theorem shapeSaving_S24_cell_93 : ∀ c ∈ Icc (19.86 : ℝ) 19.877,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.59068 : ℝ) ≤ basePrunedS 8 19.86)
    (GamS_le (θ := 0.089683) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 19.877 ≤ 0.074051) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [19.877, 19.894]`. -/
theorem shapeSaving_S24_cell_94 : ∀ c ∈ Icc (19.877 : ℝ) 19.894,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.60879 : ℝ) ≤ basePrunedS 8 19.877)
    (GamS_le (θ := 0.089671) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 19.894 ≤ 0.0741138) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [19.894, 19.911]`. -/
theorem shapeSaving_S24_cell_95 : ∀ c ∈ Icc (19.894 : ℝ) 19.911,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.62691 : ℝ) ≤ basePrunedS 8 19.894)
    (GamS_le (θ := 0.089659) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 19.911 ≤ 0.0741766) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [19.911, 19.928]`. -/
theorem shapeSaving_S24_cell_96 : ∀ c ∈ Icc (19.911 : ℝ) 19.928,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.64502 : ℝ) ≤ basePrunedS 8 19.911)
    (GamS_le (θ := 0.089647) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 19.928 ≤ 0.0742396) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [19.928, 19.944]`. -/
theorem shapeSaving_S24_cell_97 : ∀ c ∈ Icc (19.928 : ℝ) 19.944,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.66313 : ℝ) ≤ basePrunedS 8 19.928)
    (GamS_le (θ := 0.089636) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 19.944 ≤ 0.0742984) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [19.944, 19.96]`. -/
theorem shapeSaving_S24_cell_98 : ∀ c ∈ Icc (19.944 : ℝ) 19.96,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.68018 : ℝ) ≤ basePrunedS 8 19.944)
    (GamS_le (θ := 0.089625) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 19.96 ≤ 0.0743575) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [19.96, 19.976]`. -/
theorem shapeSaving_S24_cell_99 : ∀ c ∈ Icc (19.96 : ℝ) 19.976,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.69723 : ℝ) ≤ basePrunedS 8 19.96)
    (GamS_le (θ := 0.089614) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 19.976 ≤ 0.0744165) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [19.976, 19.992]`. -/
theorem shapeSaving_S24_cell_100 : ∀ c ∈ Icc (19.976 : ℝ) 19.992,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.71427 : ℝ) ≤ basePrunedS 8 19.976)
    (GamS_le (θ := 0.089603) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 19.992 ≤ 0.0744755) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [19.992, 20.008]`. -/
theorem shapeSaving_S24_cell_101 : ∀ c ∈ Icc (19.992 : ℝ) 20.008,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.73132 : ℝ) ≤ basePrunedS 8 19.992)
    (GamS_le (θ := 0.089592) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.008 ≤ 0.0745343) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.008, 20.024]`. -/
theorem shapeSaving_S24_cell_102 : ∀ c ∈ Icc (20.008 : ℝ) 20.024,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.74836 : ℝ) ≤ basePrunedS 8 20.008)
    (GamS_le (θ := 0.089581) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.024 ≤ 0.0745931) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.024, 20.04]`. -/
theorem shapeSaving_S24_cell_103 : ∀ c ∈ Icc (20.024 : ℝ) 20.04,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.76541 : ℝ) ≤ basePrunedS 8 20.024)
    (GamS_le (θ := 0.08957) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.04 ≤ 0.0746519) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.04, 20.056]`. -/
theorem shapeSaving_S24_cell_104 : ∀ c ∈ Icc (20.04 : ℝ) 20.056,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.78246 : ℝ) ≤ basePrunedS 8 20.04)
    (GamS_le (θ := 0.089559) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.056 ≤ 0.0747105) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.056, 20.072]`. -/
theorem shapeSaving_S24_cell_105 : ∀ c ∈ Icc (20.056 : ℝ) 20.072,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.7995 : ℝ) ≤ basePrunedS 8 20.056)
    (GamS_le (θ := 0.089548) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.072 ≤ 0.0747691) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.072, 20.088]`. -/
theorem shapeSaving_S24_cell_106 : ∀ c ∈ Icc (20.072 : ℝ) 20.088,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.81655 : ℝ) ≤ basePrunedS 8 20.072)
    (GamS_le (θ := 0.089537) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.088 ≤ 0.0748276) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.088, 20.104]`. -/
theorem shapeSaving_S24_cell_107 : ∀ c ∈ Icc (20.088 : ℝ) 20.104,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.83359 : ℝ) ≤ basePrunedS 8 20.088)
    (GamS_le (θ := 0.089526) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.104 ≤ 0.074886) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.104, 20.12]`. -/
theorem shapeSaving_S24_cell_108 : ∀ c ∈ Icc (20.104 : ℝ) 20.12,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.85063 : ℝ) ≤ basePrunedS 8 20.104)
    (GamS_le (θ := 0.089515) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.12 ≤ 0.0749444) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.12, 20.136]`. -/
theorem shapeSaving_S24_cell_109 : ∀ c ∈ Icc (20.12 : ℝ) 20.136,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.86768 : ℝ) ≤ basePrunedS 8 20.12)
    (GamS_le (θ := 0.089504) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.136 ≤ 0.0750029) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.136, 20.152]`. -/
theorem shapeSaving_S24_cell_110 : ∀ c ∈ Icc (20.136 : ℝ) 20.152,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.88472 : ℝ) ≤ basePrunedS 8 20.136)
    (GamS_le (θ := 0.089493) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.152 ≤ 0.0750617) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.152, 20.168]`. -/
theorem shapeSaving_S24_cell_111 : ∀ c ∈ Icc (20.152 : ℝ) 20.168,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.90176 : ℝ) ≤ basePrunedS 8 20.152)
    (GamS_le (θ := 0.089483) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.168 ≤ 0.0751199) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.168, 20.184]`. -/
theorem shapeSaving_S24_cell_112 : ∀ c ∈ Icc (20.168 : ℝ) 20.184,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.91881 : ℝ) ≤ basePrunedS 8 20.168)
    (GamS_le (θ := 0.089472) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.184 ≤ 0.0751779) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.184, 20.2]`. -/
theorem shapeSaving_S24_cell_113 : ∀ c ∈ Icc (20.184 : ℝ) 20.2,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.93585 : ℝ) ≤ basePrunedS 8 20.184)
    (GamS_le (θ := 0.089461) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.2 ≤ 0.0752359) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.2, 20.216]`. -/
theorem shapeSaving_S24_cell_114 : ∀ c ∈ Icc (20.2 : ℝ) 20.216,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.95289 : ℝ) ≤ basePrunedS 8 20.2)
    (GamS_le (θ := 0.08945) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.216 ≤ 0.0752938) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.216, 20.232]`. -/
theorem shapeSaving_S24_cell_115 : ∀ c ∈ Icc (20.216 : ℝ) 20.232,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.96993 : ℝ) ≤ basePrunedS 8 20.216)
    (GamS_le (θ := 0.089439) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.232 ≤ 0.0753517) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.232, 20.248]`. -/
theorem shapeSaving_S24_cell_116 : ∀ c ∈ Icc (20.232 : ℝ) 20.248,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (21.98697 : ℝ) ≤ basePrunedS 8 20.232)
    (GamS_le (θ := 0.089428) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.248 ≤ 0.0754094) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.248, 20.265]`. -/
theorem shapeSaving_S24_cell_117 : ∀ c ∈ Icc (20.248 : ℝ) 20.265,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.00401 : ℝ) ≤ basePrunedS 8 20.248)
    (GamS_le (θ := 0.089417) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.265 ≤ 0.0754713) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.265, 20.282]`. -/
theorem shapeSaving_S24_cell_118 : ∀ c ∈ Icc (20.265 : ℝ) 20.282,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.02212 : ℝ) ≤ basePrunedS 8 20.265)
    (GamS_le (θ := 0.089405) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.282 ≤ 0.0755323) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.282, 20.299]`. -/
theorem shapeSaving_S24_cell_119 : ∀ c ∈ Icc (20.282 : ℝ) 20.299,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.04022 : ℝ) ≤ basePrunedS 8 20.282)
    (GamS_le (θ := 0.089394) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.299 ≤ 0.075594) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.299, 20.316]`. -/
theorem shapeSaving_S24_cell_120 : ∀ c ∈ Icc (20.299 : ℝ) 20.316,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.05833 : ℝ) ≤ basePrunedS 8 20.299)
    (GamS_le (θ := 0.089382) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.316 ≤ 0.0756548) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.316, 20.334]`. -/
theorem shapeSaving_S24_cell_121 : ∀ c ∈ Icc (20.316 : ℝ) 20.334,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.07643 : ℝ) ≤ basePrunedS 8 20.316)
    (GamS_le (θ := 0.08937) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.334 ≤ 0.0757197) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.334, 20.352]`. -/
theorem shapeSaving_S24_cell_122 : ∀ c ∈ Icc (20.334 : ℝ) 20.352,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.0956 : ℝ) ≤ basePrunedS 8 20.334)
    (GamS_le (θ := 0.089358) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.352 ≤ 0.0757845) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.352, 20.37]`. -/
theorem shapeSaving_S24_cell_123 : ∀ c ∈ Icc (20.352 : ℝ) 20.37,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.11477 : ℝ) ≤ basePrunedS 8 20.352)
    (GamS_le (θ := 0.089346) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.37 ≤ 0.0758492) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.37, 20.389]`. -/
theorem shapeSaving_S24_cell_124 : ∀ c ∈ Icc (20.37 : ℝ) 20.389,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.13394 : ℝ) ≤ basePrunedS 8 20.37)
    (GamS_le (θ := 0.089333) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.389 ≤ 0.0759171) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.389, 20.408]`. -/
theorem shapeSaving_S24_cell_125 : ∀ c ∈ Icc (20.389 : ℝ) 20.408,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.15417 : ℝ) ≤ basePrunedS 8 20.389)
    (GamS_le (θ := 0.08932) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.408 ≤ 0.0759856) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.408, 20.427]`. -/
theorem shapeSaving_S24_cell_126 : ∀ c ∈ Icc (20.408 : ℝ) 20.427,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.1744 : ℝ) ≤ basePrunedS 8 20.408)
    (GamS_le (θ := 0.089308) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.427 ≤ 0.0760536) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.427, 20.447]`. -/
theorem shapeSaving_S24_cell_127 : ∀ c ∈ Icc (20.427 : ℝ) 20.447,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.19464 : ℝ) ≤ basePrunedS 8 20.427)
    (GamS_le (θ := 0.089294) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.447 ≤ 0.0761245) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.447, 20.467]`. -/
theorem shapeSaving_S24_cell_128 : ∀ c ∈ Icc (20.447 : ℝ) 20.467,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.21593 : ℝ) ≤ basePrunedS 8 20.447)
    (GamS_le (θ := 0.089281) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.467 ≤ 0.0761961) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.467, 20.488]`. -/
theorem shapeSaving_S24_cell_129 : ∀ c ∈ Icc (20.467 : ℝ) 20.488,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.23723 : ℝ) ≤ basePrunedS 8 20.467)
    (GamS_le (θ := 0.089267) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.488 ≤ 0.0762709) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.488, 20.509]`. -/
theorem shapeSaving_S24_cell_130 : ∀ c ∈ Icc (20.488 : ℝ) 20.509,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.25959 : ℝ) ≤ basePrunedS 8 20.488)
    (GamS_le (θ := 0.089253) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.509 ≤ 0.0763456) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.509, 20.531]`. -/
theorem shapeSaving_S24_cell_131 : ∀ c ∈ Icc (20.509 : ℝ) 20.531,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.28195 : ℝ) ≤ basePrunedS 8 20.509)
    (GamS_le (θ := 0.089238) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.531 ≤ 0.0764237) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.531, 20.554]`. -/
theorem shapeSaving_S24_cell_132 : ∀ c ∈ Icc (20.531 : ℝ) 20.554,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.30537 : ℝ) ≤ basePrunedS 8 20.531)
    (GamS_le (θ := 0.089223) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.554 ≤ 0.0765053) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.554, 20.577]`. -/
theorem shapeSaving_S24_cell_133 : ∀ c ∈ Icc (20.554 : ℝ) 20.577,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.32986 : ℝ) ≤ basePrunedS 8 20.554)
    (GamS_le (θ := 0.089208) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.577 ≤ 0.076587) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c ∈ [20.577, 20.6]`. -/
theorem shapeSaving_S24_cell_134 : ∀ c ∈ Icc (20.577 : ℝ) 20.6,
    shapeSaving 8 3 c < 0.001877 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 4 3 : (22.35434 : ℝ) ≤ basePrunedS 8 20.577)
    (GamS_le (θ := 0.089193) (gammaXS_le 4 3 2)
      (gammaQS_le (-3) 3 2) : GamS 8 3 20.6 ≤ 0.0766686) hc

/-- `shapeSaving 8 3 c < 0.001877` for `c` in `[19.6, 20.6]`: cells 80 to 134. -/
theorem shapeSaving_S24_block_3 : ∀ c ∈ Icc (19.6 : ℝ) 20.6,
    shapeSaving 8 3 c < 0.001877 := by
  have h := shapeSaving_S24_cell_80
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_81
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_82
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_83
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_84
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_85
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_86
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_87
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_88
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_89
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_90
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_91
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_92
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_93
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_94
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_95
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_96
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_97
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_98
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_99
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_100
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_101
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_102
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_103
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_104
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_105
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_106
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_107
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_108
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_109
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_110
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_111
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_112
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_113
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_114
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_115
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_116
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_117
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_118
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_119
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_120
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_121
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_122
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_123
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_124
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_125
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_126
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_127
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_128
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_129
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_130
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_131
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_132
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_133
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S24_cell_134
  exact h

end ImprovedExponents
