module

public import ImprovedExponents.Optimum.Shapes.NumLog

@[expose] public section

/-!
# The saving with the shape `(3, 4)` on `[27, 27.738]`: cells 84 to 129

This file is generated by `python3 -m search.certs`; do not edit it. Each lemma bounds
`shapeSaving 12 6 c` on one cell `[c₁, c₂]` by `F(A(c₁), Γ(c₂))`, with certified rational bounds
on `A(c₁)` and `Γ(c₂)`; the last lemma joins the cells.
-/

namespace ImprovedExponents

open Set

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27, 27.029]`. -/
theorem shapeSaving_S34_cell_84 : ∀ c ∈ Icc (27 : ℝ) 27.029,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.44232 : ℝ) ≤ basePrunedS 12 27)
    (GamS_le (θ := 0.150835) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.029 ≤ 0.0721211) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.029, 27.057]`. -/
theorem shapeSaving_S34_cell_85 : ∀ c ∈ Icc (27.029 : ℝ) 27.057,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.4789 : ℝ) ≤ basePrunedS 12 27.029)
    (GamS_le (θ := 0.15081) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.057 ≤ 0.0721982) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.057, 27.084]`. -/
theorem shapeSaving_S34_cell_86 : ∀ c ∈ Icc (27.057 : ℝ) 27.084,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.51421 : ℝ) ≤ basePrunedS 12 27.057)
    (GamS_le (θ := 0.150786) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.084 ≤ 0.0722724) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.084, 27.11]`. -/
theorem shapeSaving_S34_cell_87 : ∀ c ∈ Icc (27.084 : ℝ) 27.11,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.54827 : ℝ) ≤ basePrunedS 12 27.084)
    (GamS_le (θ := 0.150763) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.11 ≤ 0.0723443) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.11, 27.135]`. -/
theorem shapeSaving_S34_cell_88 : ∀ c ∈ Icc (27.11 : ℝ) 27.135,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.58106 : ℝ) ≤ basePrunedS 12 27.11)
    (GamS_le (θ := 0.150742) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.135 ≤ 0.072413) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.135, 27.159]`. -/
theorem shapeSaving_S34_cell_89 : ∀ c ∈ Icc (27.135 : ℝ) 27.159,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.61259 : ℝ) ≤ basePrunedS 12 27.135)
    (GamS_le (θ := 0.150721) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.159 ≤ 0.0724789) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.159, 27.182]`. -/
theorem shapeSaving_S34_cell_90 : ∀ c ∈ Icc (27.159 : ℝ) 27.182,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.64286 : ℝ) ≤ basePrunedS 12 27.159)
    (GamS_le (θ := 0.1507) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.182 ≤ 0.0725419) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.182, 27.204]`. -/
theorem shapeSaving_S34_cell_91 : ∀ c ∈ Icc (27.182 : ℝ) 27.204,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.67187 : ℝ) ≤ basePrunedS 12 27.182)
    (GamS_le (θ := 0.150681) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.204 ≤ 0.0726019) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.204, 27.226]`. -/
theorem shapeSaving_S34_cell_92 : ∀ c ∈ Icc (27.204 : ℝ) 27.226,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.69961 : ℝ) ≤ basePrunedS 12 27.204)
    (GamS_le (θ := 0.150662) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.226 ≤ 0.0726622) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.226, 27.247]`. -/
theorem shapeSaving_S34_cell_93 : ∀ c ∈ Icc (27.226 : ℝ) 27.247,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.72736 : ℝ) ≤ basePrunedS 12 27.226)
    (GamS_le (θ := 0.150644) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.247 ≤ 0.0727197) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.247, 27.267]`. -/
theorem shapeSaving_S34_cell_94 : ∀ c ∈ Icc (27.247 : ℝ) 27.267,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.75384 : ℝ) ≤ basePrunedS 12 27.247)
    (GamS_le (θ := 0.150626) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.267 ≤ 0.072774) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.267, 27.287]`. -/
theorem shapeSaving_S34_cell_95 : ∀ c ∈ Icc (27.267 : ℝ) 27.287,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.77907 : ℝ) ≤ basePrunedS 12 27.267)
    (GamS_le (θ := 0.150609) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.287 ≤ 0.0728288) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.287, 27.306]`. -/
theorem shapeSaving_S34_cell_96 : ∀ c ∈ Icc (27.287 : ℝ) 27.306,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.80429 : ℝ) ≤ basePrunedS 12 27.287)
    (GamS_le (θ := 0.150592) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.306 ≤ 0.0728806) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.306, 27.324]`. -/
theorem shapeSaving_S34_cell_97 : ∀ c ∈ Icc (27.306 : ℝ) 27.324,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.82825 : ℝ) ≤ basePrunedS 12 27.306)
    (GamS_le (θ := 0.150577) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.324 ≤ 0.0729296) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.324, 27.342]`. -/
theorem shapeSaving_S34_cell_98 : ∀ c ∈ Icc (27.324 : ℝ) 27.342,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.85095 : ℝ) ≤ basePrunedS 12 27.324)
    (GamS_le (θ := 0.150561) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.342 ≤ 0.0729784) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.342, 27.359]`. -/
theorem shapeSaving_S34_cell_99 : ∀ c ∈ Icc (27.342 : ℝ) 27.359,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.87365 : ℝ) ≤ basePrunedS 12 27.342)
    (GamS_le (θ := 0.150546) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.359 ≤ 0.0730249) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.359, 27.376]`. -/
theorem shapeSaving_S34_cell_100 : ∀ c ∈ Icc (27.359 : ℝ) 27.376,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.89509 : ℝ) ≤ basePrunedS 12 27.359)
    (GamS_le (θ := 0.150532) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.376 ≤ 0.073071) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.376, 27.392]`. -/
theorem shapeSaving_S34_cell_101 : ∀ c ∈ Icc (27.376 : ℝ) 27.392,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.91653 : ℝ) ≤ basePrunedS 12 27.376)
    (GamS_le (θ := 0.150518) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.392 ≤ 0.0731143) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.392, 27.408]`. -/
theorem shapeSaving_S34_cell_102 : ∀ c ∈ Icc (27.392 : ℝ) 27.408,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.9367 : ℝ) ≤ basePrunedS 12 27.392)
    (GamS_le (θ := 0.150504) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.408 ≤ 0.0731576) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.408, 27.424]`. -/
theorem shapeSaving_S34_cell_103 : ∀ c ∈ Icc (27.408 : ℝ) 27.424,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.95688 : ℝ) ≤ basePrunedS 12 27.408)
    (GamS_le (θ := 0.15049) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.424 ≤ 0.0732008) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.424, 27.439]`. -/
theorem shapeSaving_S34_cell_104 : ∀ c ∈ Icc (27.424 : ℝ) 27.439,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.97706 : ℝ) ≤ basePrunedS 12 27.424)
    (GamS_le (θ := 0.150477) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.439 ≤ 0.0732414) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.439, 27.454]`. -/
theorem shapeSaving_S34_cell_105 : ∀ c ∈ Icc (27.439 : ℝ) 27.454,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.99597 : ℝ) ≤ basePrunedS 12 27.439)
    (GamS_le (θ := 0.150464) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.454 ≤ 0.0732821) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.454, 27.468]`. -/
theorem shapeSaving_S34_cell_106 : ∀ c ∈ Icc (27.454 : ℝ) 27.468,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.01489 : ℝ) ≤ basePrunedS 12 27.454)
    (GamS_le (θ := 0.150452) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.468 ≤ 0.0733198) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.468, 27.482]`. -/
theorem shapeSaving_S34_cell_107 : ∀ c ∈ Icc (27.468 : ℝ) 27.482,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.03254 : ℝ) ≤ basePrunedS 12 27.468)
    (GamS_le (θ := 0.15044) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.482 ≤ 0.0733577) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.482, 27.496]`. -/
theorem shapeSaving_S34_cell_108 : ∀ c ∈ Icc (27.482 : ℝ) 27.496,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.0502 : ℝ) ≤ basePrunedS 12 27.482)
    (GamS_le (θ := 0.150428) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.496 ≤ 0.0733955) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.496, 27.51]`. -/
theorem shapeSaving_S34_cell_109 : ∀ c ∈ Icc (27.496 : ℝ) 27.51,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.06785 : ℝ) ≤ basePrunedS 12 27.496)
    (GamS_le (θ := 0.150416) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.51 ≤ 0.0734333) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.51, 27.523]`. -/
theorem shapeSaving_S34_cell_110 : ∀ c ∈ Icc (27.51 : ℝ) 27.523,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.0855 : ℝ) ≤ basePrunedS 12 27.51)
    (GamS_le (θ := 0.150405) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.523 ≤ 0.0734684) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.523, 27.536]`. -/
theorem shapeSaving_S34_cell_111 : ∀ c ∈ Icc (27.523 : ℝ) 27.536,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.1019 : ℝ) ≤ basePrunedS 12 27.523)
    (GamS_le (θ := 0.150394) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.536 ≤ 0.0735035) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.536, 27.549]`. -/
theorem shapeSaving_S34_cell_112 : ∀ c ∈ Icc (27.536 : ℝ) 27.549,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.11829 : ℝ) ≤ basePrunedS 12 27.536)
    (GamS_le (θ := 0.150383) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.549 ≤ 0.0735386) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.549, 27.561]`. -/
theorem shapeSaving_S34_cell_113 : ∀ c ∈ Icc (27.549 : ℝ) 27.561,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.13468 : ℝ) ≤ basePrunedS 12 27.549)
    (GamS_le (θ := 0.150372) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.561 ≤ 0.0735708) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.561, 27.573]`. -/
theorem shapeSaving_S34_cell_114 : ∀ c ∈ Icc (27.561 : ℝ) 27.573,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.14981 : ℝ) ≤ basePrunedS 12 27.561)
    (GamS_le (θ := 0.150362) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.573 ≤ 0.0736029) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.573, 27.585]`. -/
theorem shapeSaving_S34_cell_115 : ∀ c ∈ Icc (27.573 : ℝ) 27.585,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.16494 : ℝ) ≤ basePrunedS 12 27.573)
    (GamS_le (θ := 0.150352) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.585 ≤ 0.0736353) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.585, 27.597]`. -/
theorem shapeSaving_S34_cell_116 : ∀ c ∈ Icc (27.585 : ℝ) 27.597,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.18007 : ℝ) ≤ basePrunedS 12 27.585)
    (GamS_le (θ := 0.150342) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.597 ≤ 0.0736677) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.597, 27.609]`. -/
theorem shapeSaving_S34_cell_117 : ∀ c ∈ Icc (27.597 : ℝ) 27.609,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.1952 : ℝ) ≤ basePrunedS 12 27.597)
    (GamS_le (θ := 0.150331) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.609 ≤ 0.0736995) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.609, 27.621]`. -/
theorem shapeSaving_S34_cell_118 : ∀ c ∈ Icc (27.609 : ℝ) 27.621,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.21034 : ℝ) ≤ basePrunedS 12 27.609)
    (GamS_le (θ := 0.150321) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.621 ≤ 0.0737319) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.621, 27.632]`. -/
theorem shapeSaving_S34_cell_119 : ∀ c ∈ Icc (27.621 : ℝ) 27.632,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.22547 : ℝ) ≤ basePrunedS 12 27.621)
    (GamS_le (θ := 0.150312) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.632 ≤ 0.0737616) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.632, 27.643]`. -/
theorem shapeSaving_S34_cell_120 : ∀ c ∈ Icc (27.632 : ℝ) 27.643,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.23934 : ℝ) ≤ basePrunedS 12 27.632)
    (GamS_le (θ := 0.150302) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.643 ≤ 0.0737907) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.643, 27.654]`. -/
theorem shapeSaving_S34_cell_121 : ∀ c ∈ Icc (27.643 : ℝ) 27.654,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.25321 : ℝ) ≤ basePrunedS 12 27.643)
    (GamS_le (θ := 0.150293) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.654 ≤ 0.0738204) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.654, 27.665]`. -/
theorem shapeSaving_S34_cell_122 : ∀ c ∈ Icc (27.654 : ℝ) 27.665,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.26708 : ℝ) ≤ basePrunedS 12 27.654)
    (GamS_le (θ := 0.150283) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.665 ≤ 0.07385) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.665, 27.676]`. -/
theorem shapeSaving_S34_cell_123 : ∀ c ∈ Icc (27.665 : ℝ) 27.676,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.28094 : ℝ) ≤ basePrunedS 12 27.665)
    (GamS_le (θ := 0.150274) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.676 ≤ 0.0738791) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.676, 27.687]`. -/
theorem shapeSaving_S34_cell_124 : ∀ c ∈ Icc (27.676 : ℝ) 27.687,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.29481 : ℝ) ≤ basePrunedS 12 27.676)
    (GamS_le (θ := 0.150265) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.687 ≤ 0.0739088) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.687, 27.698]`. -/
theorem shapeSaving_S34_cell_125 : ∀ c ∈ Icc (27.687 : ℝ) 27.698,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.30868 : ℝ) ≤ basePrunedS 12 27.687)
    (GamS_le (θ := 0.150255) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.698 ≤ 0.0739379) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.698, 27.708]`. -/
theorem shapeSaving_S34_cell_126 : ∀ c ∈ Icc (27.698 : ℝ) 27.708,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.32255 : ℝ) ≤ basePrunedS 12 27.698)
    (GamS_le (θ := 0.150247) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.708 ≤ 0.0739648) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.708, 27.718]`. -/
theorem shapeSaving_S34_cell_127 : ∀ c ∈ Icc (27.708 : ℝ) 27.718,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.33516 : ℝ) ≤ basePrunedS 12 27.708)
    (GamS_le (θ := 0.150238) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.718 ≤ 0.0739913) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.718, 27.728]`. -/
theorem shapeSaving_S34_cell_128 : ∀ c ∈ Icc (27.718 : ℝ) 27.728,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.34777 : ℝ) ≤ basePrunedS 12 27.718)
    (GamS_le (θ := 0.15023) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.728 ≤ 0.0740182) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c ∈ [27.728, 27.738]`. -/
theorem shapeSaving_S34_cell_129 : ∀ c ∈ Icc (27.728 : ℝ) 27.738,
    shapeSaving 12 6 c < 0.001869 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (35.36038 : ℝ) ≤ basePrunedS 12 27.728)
    (GamS_le (θ := 0.150221) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 27.738 ≤ 0.0740446) hc

/-- `shapeSaving 12 6 c < 0.001869` for `c` in `[27, 27.738]`: cells 84 to 129. -/
theorem shapeSaving_S34_block_3 : ∀ c ∈ Icc (27 : ℝ) 27.738,
    shapeSaving 12 6 c < 0.001869 := by
  have h := shapeSaving_S34_cell_84
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_85
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_86
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_87
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_88
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_89
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_90
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_91
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_92
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_93
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_94
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_95
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_96
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_97
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_98
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_99
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_100
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_101
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_102
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_103
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_104
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_105
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_106
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_107
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_108
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_109
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_110
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_111
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_112
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_113
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_114
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_115
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_116
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_117
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_118
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_119
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_120
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_121
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_122
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_123
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_124
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_125
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_126
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_127
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_128
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_129
  exact h

end ImprovedExponents
