module

public import ImprovedExponents.Optimum.Shapes.NumLog

@[expose] public section

/-!
# The saving with the shape `(3, 4)` on `(13, 26.729]`: cells 1 to 41

This file is generated by `python3 -m search.certs`; do not edit it. Each lemma bounds
`shapeSaving 12 6 c` on one cell `[c₁, c₂]` by `F(A(c₁), Γ(c₂))`, with certified rational bounds
on `A(c₁)` and `Γ(c₂)`; the last lemma joins the cells.
-/

namespace ImprovedExponents

open Set

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ (13, 17]`. -/
theorem shapeSaving_S34_cell_1 : ∀ c ∈ Ioc (13 : ℝ) 17,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Ioc 3
    (le_basePrunedS 4 4 : (16.67216 : ℝ) ≤ basePrunedS 12 13)
    (GamS_le (θ := 0.162975) (gammaXS_le 4 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 17 ≤ 0.0344798) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [17, 19.3]`. -/
theorem shapeSaving_S34_cell_2 : ∀ c ∈ Icc (17 : ℝ) 19.3,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 4 4 : (21.78085 : ℝ) ≤ basePrunedS 12 17)
    (GamS_le (θ := 0.159414) (gammaXS_le 4 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 19.3 ≤ 0.0454334) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [19.3, 20.8]`. -/
theorem shapeSaving_S34_cell_3 : ∀ c ∈ Icc (19.3 : ℝ) 20.8,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 4 4 : (24.70376 : ℝ) ≤ basePrunedS 12 19.3)
    (GamS_le (θ := 0.157404) (gammaXS_le 4 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 20.8 ≤ 0.0516491) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [20.8, 21.8]`. -/
theorem shapeSaving_S34_cell_4 : ∀ c ∈ Icc (20.8 : ℝ) 21.8,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 4 4 : (26.60583 : ℝ) ≤ basePrunedS 12 20.8)
    (GamS_le (θ := 0.156175) (gammaXS_le 4 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 21.8 ≤ 0.0554614) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [21.8, 22.58]`. -/
theorem shapeSaving_S34_cell_5 : ∀ c ∈ Icc (21.8 : ℝ) 22.58,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 4 4 : (27.87233 : ℝ) ≤ basePrunedS 12 21.8)
    (GamS_le (θ := 0.15527) (gammaXS_le 4 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 22.58 ≤ 0.0582729) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [22.58, 23.18]`. -/
theorem shapeSaving_S34_cell_6 : ∀ c ∈ Icc (22.58 : ℝ) 23.18,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 4 4 : (28.85943 : ℝ) ≤ basePrunedS 12 22.58)
    (GamS_le (θ := 0.154603) (gammaXS_le 4 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 23.18 ≤ 0.0603472) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [23.18, 23.66]`. -/
theorem shapeSaving_S34_cell_7 : ∀ c ∈ Icc (23.18 : ℝ) 23.66,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (29.61831 : ℝ) ≤ basePrunedS 12 23.18)
    (GamS_le (θ := 0.154087) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 23.66 ≤ 0.0619549) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [23.66, 24.04]`. -/
theorem shapeSaving_S34_cell_8 : ∀ c ∈ Icc (23.66 : ℝ) 24.04,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (30.22516 : ℝ) ≤ basePrunedS 12 23.66)
    (GamS_le (θ := 0.153689) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 24.04 ≤ 0.0631968) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [24.04, 24.36]`. -/
theorem shapeSaving_S34_cell_9 : ∀ c ∈ Icc (24.04 : ℝ) 24.36,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (30.70543 : ℝ) ≤ basePrunedS 12 24.04)
    (GamS_le (θ := 0.15336) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 24.36 ≤ 0.0642219) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [24.36, 24.63]`. -/
theorem shapeSaving_S34_cell_10 : ∀ c ∈ Icc (24.36 : ℝ) 24.63,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (31.10977 : ℝ) ≤ basePrunedS 12 24.36)
    (GamS_le (θ := 0.153087) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 24.63 ≤ 0.0650731) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [24.63, 24.86]`. -/
theorem shapeSaving_S34_cell_11 : ∀ c ∈ Icc (24.63 : ℝ) 24.86,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (31.45086 : ℝ) ≤ basePrunedS 12 24.63)
    (GamS_le (θ := 0.152858) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 24.86 ≤ 0.0657882) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [24.86, 25.05]`. -/
theorem shapeSaving_S34_cell_12 : ∀ c ∈ Icc (24.86 : ℝ) 25.05,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (31.74136 : ℝ) ≤ basePrunedS 12 24.86)
    (GamS_le (θ := 0.152672) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 25.05 ≤ 0.0663722) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [25.05, 25.22]`. -/
theorem shapeSaving_S34_cell_13 : ∀ c ∈ Icc (25.05 : ℝ) 25.22,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (31.98131 : ℝ) ≤ basePrunedS 12 25.05)
    (GamS_le (θ := 0.152506) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 25.22 ≤ 0.0668895) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [25.22, 25.37]`. -/
theorem shapeSaving_S34_cell_14 : ∀ c ∈ Icc (25.22 : ℝ) 25.37,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (32.19598 : ℝ) ≤ basePrunedS 12 25.22)
    (GamS_le (θ := 0.152361) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 25.37 ≤ 0.0673422) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [25.37, 25.5]`. -/
theorem shapeSaving_S34_cell_15 : ∀ c ∈ Icc (25.37 : ℝ) 25.5,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (32.38538 : ℝ) ≤ basePrunedS 12 25.37)
    (GamS_le (θ := 0.152237) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 25.5 ≤ 0.0677319) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [25.5, 25.61]`. -/
theorem shapeSaving_S34_cell_16 : ∀ c ∈ Icc (25.5 : ℝ) 25.61,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (32.5495 : ℝ) ≤ basePrunedS 12 25.5)
    (GamS_le (θ := 0.152132) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 25.61 ≤ 0.0680592) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [25.61, 25.71]`. -/
theorem shapeSaving_S34_cell_17 : ∀ c ∈ Icc (25.61 : ℝ) 25.71,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (32.68837 : ℝ) ≤ basePrunedS 12 25.61)
    (GamS_le (θ := 0.152037) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 25.71 ≤ 0.0683551) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [25.71, 25.807]`. -/
theorem shapeSaving_S34_cell_18 : ∀ c ∈ Icc (25.71 : ℝ) 25.807,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (32.8146 : ℝ) ≤ basePrunedS 12 25.71)
    (GamS_le (θ := 0.151946) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 25.807 ≤ 0.068641) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [25.807, 25.894]`. -/
theorem shapeSaving_S34_cell_19 : ∀ c ∈ Icc (25.807 : ℝ) 25.894,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (32.93704 : ℝ) ≤ basePrunedS 12 25.807)
    (GamS_le (θ := 0.151864) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 25.894 ≤ 0.0688957) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [25.894, 25.973]`. -/
theorem shapeSaving_S34_cell_20 : ∀ c ∈ Icc (25.894 : ℝ) 25.973,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (33.04685 : ℝ) ≤ basePrunedS 12 25.894)
    (GamS_le (θ := 0.151791) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 25.973 ≤ 0.0691266) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [25.973, 26.044]`. -/
theorem shapeSaving_S34_cell_21 : ∀ c ∈ Icc (25.973 : ℝ) 26.044,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (33.14655 : ℝ) ≤ basePrunedS 12 25.973)
    (GamS_le (θ := 0.151725) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 26.044 ≤ 0.069333) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [26.044, 26.109]`. -/
theorem shapeSaving_S34_cell_22 : ∀ c ∈ Icc (26.044 : ℝ) 26.109,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (33.23616 : ℝ) ≤ basePrunedS 12 26.044)
    (GamS_le (θ := 0.151665) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 26.109 ≤ 0.0695214) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [26.109, 26.169]`. -/
theorem shapeSaving_S34_cell_23 : ∀ c ∈ Icc (26.109 : ℝ) 26.169,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (33.31819 : ℝ) ≤ basePrunedS 12 26.109)
    (GamS_le (θ := 0.151609) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 26.169 ≤ 0.0696944) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [26.169, 26.224]`. -/
theorem shapeSaving_S34_cell_24 : ∀ c ∈ Icc (26.169 : ℝ) 26.224,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (33.39391 : ℝ) ≤ basePrunedS 12 26.169)
    (GamS_le (θ := 0.151559) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 26.224 ≤ 0.069853) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [26.224, 26.274]`. -/
theorem shapeSaving_S34_cell_25 : ∀ c ∈ Icc (26.224 : ℝ) 26.274,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (33.46331 : ℝ) ≤ basePrunedS 12 26.224)
    (GamS_le (θ := 0.151513) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 26.274 ≤ 0.0699966) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [26.274, 26.32]`. -/
theorem shapeSaving_S34_cell_26 : ∀ c ∈ Icc (26.274 : ℝ) 26.32,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (33.52641 : ℝ) ≤ basePrunedS 12 26.274)
    (GamS_le (θ := 0.151471) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 26.32 ≤ 0.0701284) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [26.32, 26.363]`. -/
theorem shapeSaving_S34_cell_27 : ∀ c ∈ Icc (26.32 : ℝ) 26.363,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (33.58445 : ℝ) ≤ basePrunedS 12 26.32)
    (GamS_le (θ := 0.151431) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 26.363 ≤ 0.0702511) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [26.363, 26.403]`. -/
theorem shapeSaving_S34_cell_28 : ∀ c ∈ Icc (26.363 : ℝ) 26.403,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (33.63871 : ℝ) ≤ basePrunedS 12 26.363)
    (GamS_le (θ := 0.151395) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 26.403 ≤ 0.0703652) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [26.403, 26.44]`. -/
theorem shapeSaving_S34_cell_29 : ∀ c ∈ Icc (26.403 : ℝ) 26.44,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (33.68918 : ℝ) ≤ basePrunedS 12 26.403)
    (GamS_le (θ := 0.151361) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 26.44 ≤ 0.0704703) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [26.44, 26.474]`. -/
theorem shapeSaving_S34_cell_30 : ∀ c ∈ Icc (26.44 : ℝ) 26.474,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (33.73587 : ℝ) ≤ basePrunedS 12 26.44)
    (GamS_le (θ := 0.151331) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 26.474 ≤ 0.0705674) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [26.474, 26.506]`. -/
theorem shapeSaving_S34_cell_31 : ∀ c ∈ Icc (26.474 : ℝ) 26.506,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (33.77876 : ℝ) ≤ basePrunedS 12 26.474)
    (GamS_le (θ := 0.151302) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 26.506 ≤ 0.0706581) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [26.506, 26.535]`. -/
theorem shapeSaving_S34_cell_32 : ∀ c ∈ Icc (26.506 : ℝ) 26.535,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (33.81914 : ℝ) ≤ basePrunedS 12 26.506)
    (GamS_le (θ := 0.151275) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 26.535 ≤ 0.0707398) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [26.535, 26.563]`. -/
theorem shapeSaving_S34_cell_33 : ∀ c ∈ Icc (26.535 : ℝ) 26.563,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (33.85573 : ℝ) ≤ basePrunedS 12 26.535)
    (GamS_le (θ := 0.15125) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 26.563 ≤ 0.0708192) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [26.563, 26.589]`. -/
theorem shapeSaving_S34_cell_34 : ∀ c ∈ Icc (26.563 : ℝ) 26.589,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (33.89105 : ℝ) ≤ basePrunedS 12 26.563)
    (GamS_le (θ := 0.151227) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 26.589 ≤ 0.0708928) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [26.589, 26.613]`. -/
theorem shapeSaving_S34_cell_35 : ∀ c ∈ Icc (26.589 : ℝ) 26.613,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (33.92385 : ℝ) ≤ basePrunedS 12 26.589)
    (GamS_le (θ := 0.151205) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 26.613 ≤ 0.0709603) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [26.613, 26.636]`. -/
theorem shapeSaving_S34_cell_36 : ∀ c ∈ Icc (26.613 : ℝ) 26.636,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (33.95413 : ℝ) ≤ basePrunedS 12 26.613)
    (GamS_le (θ := 0.151184) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 26.636 ≤ 0.071025) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [26.636, 26.657]`. -/
theorem shapeSaving_S34_cell_37 : ∀ c ∈ Icc (26.636 : ℝ) 26.657,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (33.98315 : ℝ) ≤ basePrunedS 12 26.636)
    (GamS_le (θ := 0.151165) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 26.657 ≤ 0.0710843) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [26.657, 26.677]`. -/
theorem shapeSaving_S34_cell_38 : ∀ c ∈ Icc (26.657 : ℝ) 26.677,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.00964 : ℝ) ≤ basePrunedS 12 26.657)
    (GamS_le (θ := 0.151148) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 26.677 ≤ 0.0711407) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [26.677, 26.695]`. -/
theorem shapeSaving_S34_cell_39 : ∀ c ∈ Icc (26.677 : ℝ) 26.695,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.03487 : ℝ) ≤ basePrunedS 12 26.677)
    (GamS_le (θ := 0.151131) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 26.695 ≤ 0.0711909) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [26.695, 26.713]`. -/
theorem shapeSaving_S34_cell_40 : ∀ c ∈ Icc (26.695 : ℝ) 26.713,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.05758 : ℝ) ≤ basePrunedS 12 26.695)
    (GamS_le (θ := 0.151115) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 26.713 ≤ 0.0712414) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [26.713, 26.729]`. -/
theorem shapeSaving_S34_cell_41 : ∀ c ∈ Icc (26.713 : ℝ) 26.729,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (34.08029 : ℝ) ≤ basePrunedS 12 26.713)
    (GamS_le (θ := 0.151101) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 26.729 ≤ 0.0712864) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c` in `(13, 26.729]`: cells 1 to 41. -/
theorem shapeSaving_S34_block_1 : ∀ c ∈ Ioc (13 : ℝ) 26.729,
    shapeSaving 12 6 c < 0.001867 := by
  have h := shapeSaving_S34_cell_1
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_2
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_3
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_4
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_5
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_6
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_7
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_8
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_9
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_10
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_11
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_12
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_13
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_14
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_15
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_16
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_17
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_18
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_19
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_20
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_21
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_22
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_23
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_24
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_25
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_26
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_27
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_28
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_29
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_30
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_31
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_32
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_33
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_34
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_35
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_36
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_37
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_38
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_39
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_40
  replace h := forall_mem_Ioc_of_forall_mem_Icc h shapeSaving_S34_cell_41
  exact h

end ImprovedExponents
