module

public import ImprovedExponents.Optimum.Shapes.NumLog

@[expose] public section

/-!
# The saving with the shape `(3, 5)` on `[34.029, 35.1]`: cells 112 to 146

This file is generated by `python3 -m search.certs`; do not edit it. Each lemma bounds
`shapeSaving 15 8 c` on one cell `[c₁, c₂]` by `F(A(c₁), Γ(c₂))`, with certified rational bounds
on `A(c₁)` and `Γ(c₂)`; the last lemma joins the cells.
-/

namespace ImprovedExponents

open Set

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.029, 34.054]`. -/
theorem shapeSaving_S35_cell_112 : ∀ c ∈ Icc (34.029 : ℝ) 34.054,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (46.97828 : ℝ) ≤ basePrunedS 15 34.029)
    (GamS_le (θ := 0.172169) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.054 ≤ 0.0732074) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.054, 34.079]`. -/
theorem shapeSaving_S35_cell_113 : ∀ c ∈ Icc (34.054 : ℝ) 34.079,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.0125 : ℝ) ≤ basePrunedS 15 34.054)
    (GamS_le (θ := 0.172149) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.079 ≤ 0.0732604) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.079, 34.104]`. -/
theorem shapeSaving_S35_cell_114 : ∀ c ∈ Icc (34.079 : ℝ) 34.104,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.04672 : ℝ) ≤ basePrunedS 15 34.079)
    (GamS_le (θ := 0.17213) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.104 ≤ 0.0733138) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.104, 34.129]`. -/
theorem shapeSaving_S35_cell_115 : ∀ c ∈ Icc (34.104 : ℝ) 34.129,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.08095 : ℝ) ≤ basePrunedS 15 34.104)
    (GamS_le (θ := 0.172111) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.129 ≤ 0.0733671) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.129, 34.154]`. -/
theorem shapeSaving_S35_cell_116 : ∀ c ∈ Icc (34.129 : ℝ) 34.154,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.11517 : ℝ) ≤ basePrunedS 15 34.129)
    (GamS_le (θ := 0.172091) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.154 ≤ 0.0734199) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.154, 34.179]`. -/
theorem shapeSaving_S35_cell_117 : ∀ c ∈ Icc (34.154 : ℝ) 34.179,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.14939 : ℝ) ≤ basePrunedS 15 34.154)
    (GamS_le (θ := 0.172072) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.179 ≤ 0.0734731) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.179, 34.204]`. -/
theorem shapeSaving_S35_cell_118 : ∀ c ∈ Icc (34.179 : ℝ) 34.204,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.18361 : ℝ) ≤ basePrunedS 15 34.179)
    (GamS_le (θ := 0.172053) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.204 ≤ 0.0735262) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.204, 34.229]`. -/
theorem shapeSaving_S35_cell_119 : ∀ c ∈ Icc (34.204 : ℝ) 34.229,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.21783 : ℝ) ≤ basePrunedS 15 34.204)
    (GamS_le (θ := 0.172033) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.229 ≤ 0.0735788) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.229, 34.255]`. -/
theorem shapeSaving_S35_cell_120 : ∀ c ∈ Icc (34.229 : ℝ) 34.255,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.25206 : ℝ) ≤ basePrunedS 15 34.229)
    (GamS_le (θ := 0.172013) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.255 ≤ 0.0736338) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.255, 34.281]`. -/
theorem shapeSaving_S35_cell_121 : ∀ c ∈ Icc (34.255 : ℝ) 34.281,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.28765 : ℝ) ≤ basePrunedS 15 34.255)
    (GamS_le (θ := 0.171993) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.281 ≤ 0.0736888) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.281, 34.307]`. -/
theorem shapeSaving_S35_cell_122 : ∀ c ∈ Icc (34.281 : ℝ) 34.307,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.32324 : ℝ) ≤ basePrunedS 15 34.281)
    (GamS_le (θ := 0.171973) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.307 ≤ 0.0737436) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.307, 34.334]`. -/
theorem shapeSaving_S35_cell_123 : ∀ c ∈ Icc (34.307 : ℝ) 34.334,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.35882 : ℝ) ≤ basePrunedS 15 34.307)
    (GamS_le (θ := 0.171952) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.334 ≤ 0.0738009) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.334, 34.361]`. -/
theorem shapeSaving_S35_cell_124 : ∀ c ∈ Icc (34.334 : ℝ) 34.361,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.39578 : ℝ) ≤ basePrunedS 15 34.334)
    (GamS_le (θ := 0.171932) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.361 ≤ 0.0738577) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.361, 34.388]`. -/
theorem shapeSaving_S35_cell_125 : ∀ c ∈ Icc (34.361 : ℝ) 34.388,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.43274 : ℝ) ≤ basePrunedS 15 34.361)
    (GamS_le (θ := 0.171911) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.388 ≤ 0.0739144) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.388, 34.416]`. -/
theorem shapeSaving_S35_cell_126 : ∀ c ∈ Icc (34.388 : ℝ) 34.416,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.4697 : ℝ) ≤ basePrunedS 15 34.388)
    (GamS_le (θ := 0.17189) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.416 ≤ 0.0739735) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.416, 34.444]`. -/
theorem shapeSaving_S35_cell_127 : ∀ c ∈ Icc (34.416 : ℝ) 34.444,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.50802 : ℝ) ≤ basePrunedS 15 34.416)
    (GamS_le (θ := 0.171868) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.444 ≤ 0.074032) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.444, 34.473]`. -/
theorem shapeSaving_S35_cell_128 : ∀ c ∈ Icc (34.444 : ℝ) 34.473,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.54635 : ℝ) ≤ basePrunedS 15 34.444)
    (GamS_le (θ := 0.171846) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.473 ≤ 0.0740929) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.473, 34.502]`. -/
theorem shapeSaving_S35_cell_129 : ∀ c ∈ Icc (34.473 : ℝ) 34.502,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.58604 : ℝ) ≤ basePrunedS 15 34.473)
    (GamS_le (θ := 0.171824) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.502 ≤ 0.0741537) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.502, 34.532]`. -/
theorem shapeSaving_S35_cell_130 : ∀ c ∈ Icc (34.502 : ℝ) 34.532,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.62574 : ℝ) ≤ basePrunedS 15 34.502)
    (GamS_le (θ := 0.171801) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.532 ≤ 0.0742165) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.532, 34.562]`. -/
theorem shapeSaving_S35_cell_131 : ∀ c ∈ Icc (34.532 : ℝ) 34.562,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.6668 : ℝ) ≤ basePrunedS 15 34.532)
    (GamS_le (θ := 0.171778) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.562 ≤ 0.0742791) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.562, 34.593]`. -/
theorem shapeSaving_S35_cell_132 : ∀ c ∈ Icc (34.562 : ℝ) 34.593,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.70786 : ℝ) ≤ basePrunedS 15 34.562)
    (GamS_le (θ := 0.171755) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.593 ≤ 0.0743441) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.593, 34.625]`. -/
theorem shapeSaving_S35_cell_133 : ∀ c ∈ Icc (34.593 : ℝ) 34.625,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.75029 : ℝ) ≤ basePrunedS 15 34.593)
    (GamS_le (θ := 0.17173) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.625 ≤ 0.0744105) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.625, 34.657]`. -/
theorem shapeSaving_S35_cell_134 : ∀ c ∈ Icc (34.625 : ℝ) 34.657,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.79409 : ℝ) ≤ basePrunedS 15 34.625)
    (GamS_le (θ := 0.171706) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.657 ≤ 0.0744773) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.657, 34.69]`. -/
theorem shapeSaving_S35_cell_135 : ∀ c ∈ Icc (34.657 : ℝ) 34.69,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.83788 : ℝ) ≤ basePrunedS 15 34.657)
    (GamS_le (θ := 0.171681) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.69 ≤ 0.074546) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.69, 34.724]`. -/
theorem shapeSaving_S35_cell_136 : ∀ c ∈ Icc (34.69 : ℝ) 34.724,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.88305 : ℝ) ≤ basePrunedS 15 34.69)
    (GamS_le (θ := 0.171655) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.724 ≤ 0.0746165) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.724, 34.759]`. -/
theorem shapeSaving_S35_cell_137 : ∀ c ∈ Icc (34.724 : ℝ) 34.759,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.92958 : ℝ) ≤ basePrunedS 15 34.724)
    (GamS_le (θ := 0.171629) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.759 ≤ 0.0746894) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.759, 34.795]`. -/
theorem shapeSaving_S35_cell_138 : ∀ c ∈ Icc (34.759 : ℝ) 34.795,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (47.97749 : ℝ) ≤ basePrunedS 15 34.759)
    (GamS_le (θ := 0.171602) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.795 ≤ 0.074764) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.795, 34.832]`. -/
theorem shapeSaving_S35_cell_139 : ∀ c ∈ Icc (34.795 : ℝ) 34.832,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (48.02676 : ℝ) ≤ basePrunedS 15 34.795)
    (GamS_le (θ := 0.171574) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.832 ≤ 0.0748406) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.832, 34.87]`. -/
theorem shapeSaving_S35_cell_140 : ∀ c ∈ Icc (34.832 : ℝ) 34.87,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (48.07739 : ℝ) ≤ basePrunedS 15 34.832)
    (GamS_le (θ := 0.171545) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.87 ≤ 0.0749189) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.87, 34.91]`. -/
theorem shapeSaving_S35_cell_141 : ∀ c ∈ Icc (34.87 : ℝ) 34.91,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (48.1294 : ℝ) ≤ basePrunedS 15 34.87)
    (GamS_le (θ := 0.171515) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.91 ≤ 0.0750015) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.91, 34.951]`. -/
theorem shapeSaving_S35_cell_142 : ∀ c ∈ Icc (34.91 : ℝ) 34.951,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (48.18414 : ℝ) ≤ basePrunedS 15 34.91)
    (GamS_le (θ := 0.171484) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.951 ≤ 0.0750858) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.951, 34.994]`. -/
theorem shapeSaving_S35_cell_143 : ∀ c ∈ Icc (34.951 : ℝ) 34.994,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (48.24025 : ℝ) ≤ basePrunedS 15 34.951)
    (GamS_le (θ := 0.171452) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 34.994 ≤ 0.0751744) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [34.994, 35.038]`. -/
theorem shapeSaving_S35_cell_144 : ∀ c ∈ Icc (34.994 : ℝ) 35.038,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (48.2991 : ℝ) ≤ basePrunedS 15 34.994)
    (GamS_le (θ := 0.171419) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 35.038 ≤ 0.0752647) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [35.038, 35.084]`. -/
theorem shapeSaving_S35_cell_145 : ∀ c ∈ Icc (35.038 : ℝ) 35.084,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (48.35931 : ℝ) ≤ basePrunedS 15 35.038)
    (GamS_le (θ := 0.171385) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 35.084 ≤ 0.0753592) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c ∈ [35.084, 35.1]`. -/
theorem shapeSaving_S35_cell_146 : ∀ c ∈ Icc (35.084 : ℝ) 35.1,
    shapeSaving 15 8 c < 0.001615 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (48.42226 : ℝ) ≤ basePrunedS 15 35.084)
    (GamS_le (θ := 0.171373) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 15 8 35.1 ≤ 0.0753919) hc

/-- `shapeSaving 15 8 c < 0.001615` for `c` in `[34.029, 35.1]`: cells 112 to 146. -/
theorem shapeSaving_S35_block_4 : ∀ c ∈ Icc (34.029 : ℝ) 35.1,
    shapeSaving 15 8 c < 0.001615 := by
  have h := shapeSaving_S35_cell_112
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_113
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_114
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_115
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_116
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_117
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_118
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_119
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_120
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_121
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_122
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_123
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_124
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_125
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_126
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_127
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_128
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_129
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_130
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_131
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_132
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_133
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_134
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_135
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_136
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_137
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_138
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_139
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_140
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_141
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_142
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_143
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_144
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_145
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S35_cell_146
  exact h

end ImprovedExponents
