module

public import ImprovedExponents.Optimum.Shapes.NumLog

@[expose] public section

/-!
# The saving with the shape `(2, 6)` on `[27.4, 28.384]`: cells 68 to 113

This file is generated by `python3 -m search.certs`; do not edit it. Each lemma bounds
`shapeSaving 12 5 c` on one cell `[c₁, c₂]` by `F(A(c₁), Γ(c₂))`, with certified rational bounds
on `A(c₁)` and `Γ(c₂)`; the last lemma joins the cells.
-/

namespace ImprovedExponents

open Set

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.4, 27.437]`. -/
theorem shapeSaving_S26_cell_68 : ∀ c ∈ Icc (27.4 : ℝ) 27.437,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (34.94679 : ℝ) ≤ basePrunedS 12 27.4)
    (GamS_le (θ := 0.132248) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 27.437 ≤ 0.0707983) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.437, 27.472]`. -/
theorem shapeSaving_S26_cell_69 : ∀ c ∈ Icc (27.437 : ℝ) 27.472,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (34.99345 : ℝ) ≤ basePrunedS 12 27.437)
    (GamS_le (θ := 0.132222) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 27.472 ≤ 0.0708916) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.472, 27.506]`. -/
theorem shapeSaving_S26_cell_70 : ∀ c ∈ Icc (27.472 : ℝ) 27.506,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.03759 : ℝ) ≤ basePrunedS 12 27.472)
    (GamS_le (θ := 0.132197) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 27.506 ≤ 0.0709822) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.506, 27.539]`. -/
theorem shapeSaving_S26_cell_71 : ∀ c ∈ Icc (27.506 : ℝ) 27.539,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.08046 : ℝ) ≤ basePrunedS 12 27.506)
    (GamS_le (θ := 0.132173) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 27.539 ≤ 0.0710701) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.539, 27.57]`. -/
theorem shapeSaving_S26_cell_72 : ∀ c ∈ Icc (27.539 : ℝ) 27.57,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.12207 : ℝ) ≤ basePrunedS 12 27.539)
    (GamS_le (θ := 0.13215) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 27.57 ≤ 0.0711523) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.57, 27.6]`. -/
theorem shapeSaving_S26_cell_73 : ∀ c ∈ Icc (27.57 : ℝ) 27.6,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.16116 : ℝ) ≤ basePrunedS 12 27.57)
    (GamS_le (θ := 0.132128) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 27.6 ≤ 0.0712318) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.6, 27.629]`. -/
theorem shapeSaving_S26_cell_74 : ∀ c ∈ Icc (27.6 : ℝ) 27.629,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.19899 : ℝ) ≤ basePrunedS 12 27.6)
    (GamS_le (θ := 0.132107) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 27.629 ≤ 0.0713087) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.629, 27.657]`. -/
theorem shapeSaving_S26_cell_75 : ∀ c ∈ Icc (27.629 : ℝ) 27.657,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.23555 : ℝ) ≤ basePrunedS 12 27.629)
    (GamS_le (θ := 0.132086) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 27.657 ≤ 0.0713829) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.657, 27.684]`. -/
theorem shapeSaving_S26_cell_76 : ∀ c ∈ Icc (27.657 : ℝ) 27.684,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.27086 : ℝ) ≤ basePrunedS 12 27.657)
    (GamS_le (θ := 0.132067) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 27.684 ≤ 0.0714542) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.684, 27.71]`. -/
theorem shapeSaving_S26_cell_77 : ∀ c ∈ Icc (27.684 : ℝ) 27.71,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.3049 : ℝ) ≤ basePrunedS 12 27.684)
    (GamS_le (θ := 0.132048) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 27.71 ≤ 0.0715227) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.71, 27.736]`. -/
theorem shapeSaving_S26_cell_78 : ∀ c ∈ Icc (27.71 : ℝ) 27.736,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.33768 : ℝ) ≤ basePrunedS 12 27.71)
    (GamS_le (θ := 0.132029) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 27.736 ≤ 0.0715912) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.736, 27.761]`. -/
theorem shapeSaving_S26_cell_79 : ∀ c ∈ Icc (27.736 : ℝ) 27.761,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.37046 : ℝ) ≤ basePrunedS 12 27.736)
    (GamS_le (θ := 0.132011) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 27.761 ≤ 0.071657) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.761, 27.785]`. -/
theorem shapeSaving_S26_cell_80 : ∀ c ∈ Icc (27.761 : ℝ) 27.785,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.40198 : ℝ) ≤ basePrunedS 12 27.761)
    (GamS_le (θ := 0.131993) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 27.785 ≤ 0.0717198) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.785, 27.808]`. -/
theorem shapeSaving_S26_cell_81 : ∀ c ∈ Icc (27.785 : ℝ) 27.808,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.43224 : ℝ) ≤ basePrunedS 12 27.785)
    (GamS_le (θ := 0.131977) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 27.808 ≤ 0.0717805) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.808, 27.831]`. -/
theorem shapeSaving_S26_cell_82 : ∀ c ∈ Icc (27.808 : ℝ) 27.831,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.46124 : ℝ) ≤ basePrunedS 12 27.808)
    (GamS_le (θ := 0.13196) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 27.831 ≤ 0.0718406) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.831, 27.853]`. -/
theorem shapeSaving_S26_cell_83 : ∀ c ∈ Icc (27.831 : ℝ) 27.853,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.49024 : ℝ) ≤ basePrunedS 12 27.831)
    (GamS_le (θ := 0.131944) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 27.853 ≤ 0.0718982) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.853, 27.875]`. -/
theorem shapeSaving_S26_cell_84 : ∀ c ∈ Icc (27.853 : ℝ) 27.875,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.51797 : ℝ) ≤ basePrunedS 12 27.853)
    (GamS_le (θ := 0.131928) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 27.875 ≤ 0.0719557) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.875, 27.896]`. -/
theorem shapeSaving_S26_cell_85 : ∀ c ∈ Icc (27.875 : ℝ) 27.896,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.54571 : ℝ) ≤ basePrunedS 12 27.875)
    (GamS_le (θ := 0.131913) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 27.896 ≤ 0.0720107) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.896, 27.917]`. -/
theorem shapeSaving_S26_cell_86 : ∀ c ∈ Icc (27.896 : ℝ) 27.917,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.57219 : ℝ) ≤ basePrunedS 12 27.896)
    (GamS_le (θ := 0.131898) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 27.917 ≤ 0.0720656) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.917, 27.937]`. -/
theorem shapeSaving_S26_cell_87 : ∀ c ∈ Icc (27.917 : ℝ) 27.937,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.59866 : ℝ) ≤ basePrunedS 12 27.917)
    (GamS_le (θ := 0.131883) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 27.937 ≤ 0.0721176) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.937, 27.957]`. -/
theorem shapeSaving_S26_cell_88 : ∀ c ∈ Icc (27.937 : ℝ) 27.957,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.62387 : ℝ) ≤ basePrunedS 12 27.937)
    (GamS_le (θ := 0.131869) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 27.957 ≤ 0.0721698) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.957, 27.977]`. -/
theorem shapeSaving_S26_cell_89 : ∀ c ∈ Icc (27.957 : ℝ) 27.977,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.64909 : ℝ) ≤ basePrunedS 12 27.957)
    (GamS_le (θ := 0.131855) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 27.977 ≤ 0.0722221) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.977, 27.996]`. -/
theorem shapeSaving_S26_cell_90 : ∀ c ∈ Icc (27.977 : ℝ) 27.996,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.6743 : ℝ) ≤ basePrunedS 12 27.977)
    (GamS_le (θ := 0.131841) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 27.996 ≤ 0.0722713) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [27.996, 28.015]`. -/
theorem shapeSaving_S26_cell_91 : ∀ c ∈ Icc (27.996 : ℝ) 28.015,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.69825 : ℝ) ≤ basePrunedS 12 27.996)
    (GamS_le (θ := 0.131827) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 28.015 ≤ 0.0723205) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [28.015, 28.034]`. -/
theorem shapeSaving_S26_cell_92 : ∀ c ∈ Icc (28.015 : ℝ) 28.034,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.7222 : ℝ) ≤ basePrunedS 12 28.015)
    (GamS_le (θ := 0.131814) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 28.034 ≤ 0.0723702) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [28.034, 28.052]`. -/
theorem shapeSaving_S26_cell_93 : ∀ c ∈ Icc (28.034 : ℝ) 28.052,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.74616 : ℝ) ≤ basePrunedS 12 28.034)
    (GamS_le (θ := 0.131801) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 28.052 ≤ 0.0724168) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [28.052, 28.07]`. -/
theorem shapeSaving_S26_cell_94 : ∀ c ∈ Icc (28.052 : ℝ) 28.07,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.76885 : ℝ) ≤ basePrunedS 12 28.052)
    (GamS_le (θ := 0.131788) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 28.07 ≤ 0.0724634) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [28.07, 28.088]`. -/
theorem shapeSaving_S26_cell_95 : ∀ c ∈ Icc (28.07 : ℝ) 28.088,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.79154 : ℝ) ≤ basePrunedS 12 28.07)
    (GamS_le (θ := 0.131775) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 28.088 ≤ 0.0725099) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [28.088, 28.106]`. -/
theorem shapeSaving_S26_cell_96 : ∀ c ∈ Icc (28.088 : ℝ) 28.106,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.81423 : ℝ) ≤ basePrunedS 12 28.088)
    (GamS_le (θ := 0.131762) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 28.106 ≤ 0.0725564) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [28.106, 28.123]`. -/
theorem shapeSaving_S26_cell_97 : ∀ c ∈ Icc (28.106 : ℝ) 28.123,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.83692 : ℝ) ≤ basePrunedS 12 28.106)
    (GamS_le (θ := 0.13175) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 28.123 ≤ 0.0726005) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [28.123, 28.14]`. -/
theorem shapeSaving_S26_cell_98 : ∀ c ∈ Icc (28.123 : ℝ) 28.14,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.85835 : ℝ) ≤ basePrunedS 12 28.123)
    (GamS_le (θ := 0.131738) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 28.14 ≤ 0.0726445) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [28.14, 28.157]`. -/
theorem shapeSaving_S26_cell_99 : ∀ c ∈ Icc (28.14 : ℝ) 28.157,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.87978 : ℝ) ≤ basePrunedS 12 28.14)
    (GamS_le (θ := 0.131726) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 28.157 ≤ 0.0726884) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [28.157, 28.174]`. -/
theorem shapeSaving_S26_cell_100 : ∀ c ∈ Icc (28.157 : ℝ) 28.174,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.90121 : ℝ) ≤ basePrunedS 12 28.157)
    (GamS_le (θ := 0.131714) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 28.174 ≤ 0.0727323) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [28.174, 28.191]`. -/
theorem shapeSaving_S26_cell_101 : ∀ c ∈ Icc (28.174 : ℝ) 28.191,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.92264 : ℝ) ≤ basePrunedS 12 28.174)
    (GamS_le (θ := 0.131702) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 28.191 ≤ 0.0727762) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [28.191, 28.208]`. -/
theorem shapeSaving_S26_cell_102 : ∀ c ∈ Icc (28.191 : ℝ) 28.208,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.94407 : ℝ) ≤ basePrunedS 12 28.191)
    (GamS_le (θ := 0.131689) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 28.208 ≤ 0.0728199) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [28.208, 28.224]`. -/
theorem shapeSaving_S26_cell_103 : ∀ c ∈ Icc (28.208 : ℝ) 28.224,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.96549 : ℝ) ≤ basePrunedS 12 28.208)
    (GamS_le (θ := 0.131678) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 28.224 ≤ 0.0728608) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [28.224, 28.24]`. -/
theorem shapeSaving_S26_cell_104 : ∀ c ∈ Icc (28.224 : ℝ) 28.24,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (35.98566 : ℝ) ≤ basePrunedS 12 28.224)
    (GamS_le (θ := 0.131667) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 28.24 ≤ 0.0729022) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [28.24, 28.256]`. -/
theorem shapeSaving_S26_cell_105 : ∀ c ∈ Icc (28.24 : ℝ) 28.256,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (36.00583 : ℝ) ≤ basePrunedS 12 28.24)
    (GamS_le (θ := 0.131655) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 28.256 ≤ 0.072943) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [28.256, 28.272]`. -/
theorem shapeSaving_S26_cell_106 : ∀ c ∈ Icc (28.256 : ℝ) 28.272,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (36.026 : ℝ) ≤ basePrunedS 12 28.256)
    (GamS_le (θ := 0.131644) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 28.272 ≤ 0.0729842) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [28.272, 28.288]`. -/
theorem shapeSaving_S26_cell_107 : ∀ c ∈ Icc (28.272 : ℝ) 28.288,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (36.04616 : ℝ) ≤ basePrunedS 12 28.272)
    (GamS_le (θ := 0.131633) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 28.288 ≤ 0.0730254) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [28.288, 28.304]`. -/
theorem shapeSaving_S26_cell_108 : ∀ c ∈ Icc (28.288 : ℝ) 28.304,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (36.06633 : ℝ) ≤ basePrunedS 12 28.288)
    (GamS_le (θ := 0.131621) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 28.304 ≤ 0.0730662) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [28.304, 28.32]`. -/
theorem shapeSaving_S26_cell_109 : ∀ c ∈ Icc (28.304 : ℝ) 28.32,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (36.0865 : ℝ) ≤ basePrunedS 12 28.304)
    (GamS_le (θ := 0.13161) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 28.32 ≤ 0.0731072) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [28.32, 28.336]`. -/
theorem shapeSaving_S26_cell_110 : ∀ c ∈ Icc (28.32 : ℝ) 28.336,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (36.10667 : ℝ) ≤ basePrunedS 12 28.32)
    (GamS_le (θ := 0.131599) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 28.336 ≤ 0.0731483) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [28.336, 28.352]`. -/
theorem shapeSaving_S26_cell_111 : ∀ c ∈ Icc (28.336 : ℝ) 28.352,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (36.12683 : ℝ) ≤ basePrunedS 12 28.336)
    (GamS_le (θ := 0.131587) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 28.352 ≤ 0.0731893) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [28.352, 28.368]`. -/
theorem shapeSaving_S26_cell_112 : ∀ c ∈ Icc (28.352 : ℝ) 28.368,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (36.147 : ℝ) ≤ basePrunedS 12 28.352)
    (GamS_le (θ := 0.131576) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 28.368 ≤ 0.0732299) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c ∈ [28.368, 28.384]`. -/
theorem shapeSaving_S26_cell_113 : ∀ c ∈ Icc (28.368 : ℝ) 28.384,
    shapeSaving 12 5 c < 0.001625 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 2
    (le_basePrunedS 5 4 : (36.16717 : ℝ) ≤ basePrunedS 12 28.368)
    (GamS_le (θ := 0.131565) (gammaXS_le 5 4 2)
      (gammaQS_le (-3) 4 2) : GamS 12 5 28.384 ≤ 0.0732709) hc

/-- `shapeSaving 12 5 c < 0.001625` for `c` in `[27.4, 28.384]`: cells 68 to 113. -/
theorem shapeSaving_S26_block_3 : ∀ c ∈ Icc (27.4 : ℝ) 28.384,
    shapeSaving 12 5 c < 0.001625 := by
  have h := shapeSaving_S26_cell_68
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_69
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_70
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_71
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_72
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_73
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_74
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_75
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_76
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_77
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_78
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_79
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_80
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_81
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_82
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_83
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_84
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_85
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_86
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_87
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_88
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_89
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_90
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_91
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_92
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_93
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_94
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_95
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_96
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_97
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_98
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_99
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_100
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_101
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_102
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_103
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_104
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_105
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_106
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_107
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_108
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_109
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_110
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_111
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_112
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S26_cell_113
  exact h

end ImprovedExponents
