module

public import ImprovedExponents.Optimum.Shapes.NumLog

@[expose] public section

/-!
# The saving with the shape `(3, 4)` on `[29, 29.371]`: cells 223 to 260

This file is generated by `python3 -m search.certs`; do not edit it. Each lemma bounds
`shapeSaving 12 6 c` on one cell `[c₁, c₂]` by `F(A(c₁), Γ(c₂))`, with certified rational bounds
on `A(c₁)` and `Γ(c₂)`; the last lemma joins the cells.
-/

namespace ImprovedExponents

open Set

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29, 29.0033]`. -/
theorem shapeSaving_S34_cell_223 : ∀ c ∈ Icc (29 : ℝ) 29.0033,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (36.96361 : ℝ) ≤ basePrunedS 12 29)
    (GamS_le (θ := 0.149179) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.0033 ≤ 0.0773203) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.0033, 29.0068]`. -/
theorem shapeSaving_S34_cell_224 : ∀ c ∈ Icc (29.0033 : ℝ) 29.0068,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (36.96777 : ℝ) ≤ basePrunedS 12 29.0033)
    (GamS_le (θ := 0.149176) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.0068 ≤ 0.077329) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.0068, 29.0105]`. -/
theorem shapeSaving_S34_cell_225 : ∀ c ∈ Icc (29.0068 : ℝ) 29.0105,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (36.97218 : ℝ) ≤ basePrunedS 12 29.0068)
    (GamS_le (θ := 0.149173) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.0105 ≤ 0.0773382) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.0105, 29.0143]`. -/
theorem shapeSaving_S34_cell_226 : ∀ c ∈ Icc (29.0105 : ℝ) 29.0143,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (36.97684 : ℝ) ≤ basePrunedS 12 29.0105)
    (GamS_le (θ := 0.14917) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.0143 ≤ 0.0773478) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.0143, 29.0183]`. -/
theorem shapeSaving_S34_cell_227 : ∀ c ∈ Icc (29.0143 : ℝ) 29.0183,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (36.98163 : ℝ) ≤ basePrunedS 12 29.0143)
    (GamS_le (θ := 0.149167) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.0183 ≤ 0.0773579) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.0183, 29.0224]`. -/
theorem shapeSaving_S34_cell_228 : ∀ c ∈ Icc (29.0183 : ℝ) 29.0224,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (36.98667 : ℝ) ≤ basePrunedS 12 29.0183)
    (GamS_le (θ := 0.149164) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.0224 ≤ 0.0773684) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.0224, 29.0268]`. -/
theorem shapeSaving_S34_cell_229 : ∀ c ∈ Icc (29.0224 : ℝ) 29.0268,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (36.99183 : ℝ) ≤ basePrunedS 12 29.0224)
    (GamS_le (θ := 0.14916) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.0268 ≤ 0.0773792) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.0268, 29.0315]`. -/
theorem shapeSaving_S34_cell_230 : ∀ c ∈ Icc (29.0268 : ℝ) 29.0315,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (36.99738 : ℝ) ≤ basePrunedS 12 29.0268)
    (GamS_le (θ := 0.149156) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.0315 ≤ 0.0773908) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.0315, 29.0364]`. -/
theorem shapeSaving_S34_cell_231 : ∀ c ∈ Icc (29.0315 : ℝ) 29.0364,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.0033 : ℝ) ≤ basePrunedS 12 29.0315)
    (GamS_le (θ := 0.149152) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.0364 ≤ 0.0774032) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.0364, 29.0416]`. -/
theorem shapeSaving_S34_cell_232 : ∀ c ∈ Icc (29.0364 : ℝ) 29.0416,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.00947 : ℝ) ≤ basePrunedS 12 29.0364)
    (GamS_le (θ := 0.149148) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.0416 ≤ 0.0774162) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.0416, 29.047]`. -/
theorem shapeSaving_S34_cell_233 : ∀ c ∈ Icc (29.0416 : ℝ) 29.047,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.01603 : ℝ) ≤ basePrunedS 12 29.0416)
    (GamS_le (θ := 0.149144) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.047 ≤ 0.0774299) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.047, 29.0527]`. -/
theorem shapeSaving_S34_cell_234 : ∀ c ∈ Icc (29.047 : ℝ) 29.0527,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.02283 : ℝ) ≤ basePrunedS 12 29.047)
    (GamS_le (θ := 0.149139) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.0527 ≤ 0.0774441) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.0527, 29.0586]`. -/
theorem shapeSaving_S34_cell_235 : ∀ c ∈ Icc (29.0527 : ℝ) 29.0586,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.03001 : ℝ) ≤ basePrunedS 12 29.0527)
    (GamS_le (θ := 0.149135) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.0586 ≤ 0.0774591) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.0586, 29.0648]`. -/
theorem shapeSaving_S34_cell_236 : ∀ c ∈ Icc (29.0586 : ℝ) 29.0648,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.03744 : ℝ) ≤ basePrunedS 12 29.0586)
    (GamS_le (θ := 0.14913) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.0648 ≤ 0.0774746) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.0648, 29.0713]`. -/
theorem shapeSaving_S34_cell_237 : ∀ c ∈ Icc (29.0648 : ℝ) 29.0713,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.04526 : ℝ) ≤ basePrunedS 12 29.0648)
    (GamS_le (θ := 0.149125) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.0713 ≤ 0.077491) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.0713, 29.0782]`. -/
theorem shapeSaving_S34_cell_238 : ∀ c ∈ Icc (29.0713 : ℝ) 29.0782,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.05345 : ℝ) ≤ basePrunedS 12 29.0713)
    (GamS_le (θ := 0.149119) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.0782 ≤ 0.077508) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.0782, 29.0855]`. -/
theorem shapeSaving_S34_cell_239 : ∀ c ∈ Icc (29.0782 : ℝ) 29.0855,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.06214 : ℝ) ≤ basePrunedS 12 29.0782)
    (GamS_le (θ := 0.149113) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.0855 ≤ 0.0775262) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.0855, 29.0932]`. -/
theorem shapeSaving_S34_cell_240 : ∀ c ∈ Icc (29.0855 : ℝ) 29.0932,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.07134 : ℝ) ≤ basePrunedS 12 29.0855)
    (GamS_le (θ := 0.149107) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.0932 ≤ 0.0775455) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.0932, 29.1012]`. -/
theorem shapeSaving_S34_cell_241 : ∀ c ∈ Icc (29.0932 : ℝ) 29.1012,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.08104 : ℝ) ≤ basePrunedS 12 29.0932)
    (GamS_le (θ := 0.149101) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.1012 ≤ 0.0775658) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.1012, 29.1097]`. -/
theorem shapeSaving_S34_cell_242 : ∀ c ∈ Icc (29.1012 : ℝ) 29.1097,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.09112 : ℝ) ≤ basePrunedS 12 29.1012)
    (GamS_le (θ := 0.149094) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.1097 ≤ 0.0775869) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.1097, 29.1186]`. -/
theorem shapeSaving_S34_cell_243 : ∀ c ∈ Icc (29.1097 : ℝ) 29.1186,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.10183 : ℝ) ≤ basePrunedS 12 29.1097)
    (GamS_le (θ := 0.149087) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.1186 ≤ 0.0776092) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.1186, 29.1281]`. -/
theorem shapeSaving_S34_cell_244 : ∀ c ∈ Icc (29.1186 : ℝ) 29.1281,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.11304 : ℝ) ≤ basePrunedS 12 29.1186)
    (GamS_le (θ := 0.149079) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.1281 ≤ 0.0776328) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.1281, 29.138]`. -/
theorem shapeSaving_S34_cell_245 : ∀ c ∈ Icc (29.1281 : ℝ) 29.138,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.12501 : ℝ) ≤ basePrunedS 12 29.1281)
    (GamS_le (θ := 0.149072) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.138 ≤ 0.0776579) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.138, 29.148]`. -/
theorem shapeSaving_S34_cell_246 : ∀ c ∈ Icc (29.138 : ℝ) 29.148,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.13748 : ℝ) ≤ basePrunedS 12 29.138)
    (GamS_le (θ := 0.149064) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.148 ≤ 0.0776828) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.148, 29.159]`. -/
theorem shapeSaving_S34_cell_247 : ∀ c ∈ Icc (29.148 : ℝ) 29.159,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.15008 : ℝ) ≤ basePrunedS 12 29.148)
    (GamS_le (θ := 0.149055) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.159 ≤ 0.0777101) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.159, 29.17]`. -/
theorem shapeSaving_S34_cell_248 : ∀ c ∈ Icc (29.159 : ℝ) 29.17,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.16394 : ℝ) ≤ basePrunedS 12 29.159)
    (GamS_le (θ := 0.149046) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.17 ≤ 0.0777374) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.17, 29.182]`. -/
theorem shapeSaving_S34_cell_249 : ∀ c ∈ Icc (29.17 : ℝ) 29.182,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.1778 : ℝ) ≤ basePrunedS 12 29.17)
    (GamS_le (θ := 0.149037) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.182 ≤ 0.0777676) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.182, 29.195]`. -/
theorem shapeSaving_S34_cell_250 : ∀ c ∈ Icc (29.182 : ℝ) 29.195,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.19292 : ℝ) ≤ basePrunedS 12 29.182)
    (GamS_le (θ := 0.149026) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.195 ≤ 0.0777996) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.195, 29.208]`. -/
theorem shapeSaving_S34_cell_251 : ∀ c ∈ Icc (29.195 : ℝ) 29.208,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.2093 : ℝ) ≤ basePrunedS 12 29.195)
    (GamS_le (θ := 0.149016) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.208 ≤ 0.0778321) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.208, 29.222]`. -/
theorem shapeSaving_S34_cell_252 : ∀ c ∈ Icc (29.208 : ℝ) 29.222,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.22568 : ℝ) ≤ basePrunedS 12 29.208)
    (GamS_le (θ := 0.149005) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.222 ≤ 0.077867) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.222, 29.237]`. -/
theorem shapeSaving_S34_cell_253 : ∀ c ∈ Icc (29.222 : ℝ) 29.237,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.24331 : ℝ) ≤ basePrunedS 12 29.222)
    (GamS_le (θ := 0.148993) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.237 ≤ 0.0779042) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.237, 29.253]`. -/
theorem shapeSaving_S34_cell_254 : ∀ c ∈ Icc (29.237 : ℝ) 29.253,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.26221 : ℝ) ≤ basePrunedS 12 29.237)
    (GamS_le (θ := 0.14898) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.253 ≤ 0.0779442) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.253, 29.27]`. -/
theorem shapeSaving_S34_cell_255 : ∀ c ∈ Icc (29.253 : ℝ) 29.27,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.28237 : ℝ) ≤ basePrunedS 12 29.253)
    (GamS_le (θ := 0.148967) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.27 ≤ 0.0779863) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.27, 29.288]`. -/
theorem shapeSaving_S34_cell_256 : ∀ c ∈ Icc (29.27 : ℝ) 29.288,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.30379 : ℝ) ≤ basePrunedS 12 29.27)
    (GamS_le (θ := 0.148953) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.288 ≤ 0.078031) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.288, 29.307]`. -/
theorem shapeSaving_S34_cell_257 : ∀ c ∈ Icc (29.288 : ℝ) 29.307,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.32646 : ℝ) ≤ basePrunedS 12 29.288)
    (GamS_le (θ := 0.148938) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.307 ≤ 0.0780781) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.307, 29.327]`. -/
theorem shapeSaving_S34_cell_258 : ∀ c ∈ Icc (29.307 : ℝ) 29.327,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.3504 : ℝ) ≤ basePrunedS 12 29.307)
    (GamS_le (θ := 0.148922) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.327 ≤ 0.0781275) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.327, 29.348]`. -/
theorem shapeSaving_S34_cell_259 : ∀ c ∈ Icc (29.327 : ℝ) 29.348,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.3756 : ℝ) ≤ basePrunedS 12 29.327)
    (GamS_le (θ := 0.148906) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.348 ≤ 0.0781798) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c ∈ [29.348, 29.371]`. -/
theorem shapeSaving_S34_cell_260 : ∀ c ∈ Icc (29.348 : ℝ) 29.371,
    shapeSaving 12 6 c < 0.001867 := fun _ hc =>
  shapeSaving_lt_of_mem_Icc 3
    (le_basePrunedS 5 4 : (37.40205 : ℝ) ≤ basePrunedS 12 29.348)
    (GamS_le (θ := 0.148888) (gammaXS_le 5 4 3)
      (gammaQS_le (-3) 4 3) : GamS 12 6 29.371 ≤ 0.0782367) hc

/-- `shapeSaving 12 6 c < 0.001867` for `c` in `[29, 29.371]`: cells 223 to 260. -/
theorem shapeSaving_S34_block_6 : ∀ c ∈ Icc (29 : ℝ) 29.371,
    shapeSaving 12 6 c < 0.001867 := by
  have h := shapeSaving_S34_cell_223
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_224
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_225
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_226
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_227
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_228
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_229
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_230
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_231
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_232
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_233
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_234
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_235
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_236
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_237
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_238
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_239
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_240
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_241
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_242
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_243
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_244
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_245
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_246
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_247
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_248
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_249
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_250
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_251
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_252
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_253
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_254
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_255
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_256
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_257
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_258
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_259
  replace h := forall_mem_Icc_of_forall_mem_Icc h shapeSaving_S34_cell_260
  exact h

end ImprovedExponents
