module

public import ImprovedExponents.Optimum.GlobalLemmas

@[expose] public section

/-!
# The saving with pruned encodings on `(10, 21]`: cells 1 to 35

This file is generated by `python3 -m search.certs`; do not edit it. Each lemma bounds
`F(A(c), Γ(c))` on one cell `[c₁, c₂]` by `F(A(c₁), Γ(c₂))`, with certified rational bounds
on `A(c₁)` and `Γ(c₂)`; the last lemma joins the cells.
-/

namespace ImprovedExponents

open Set

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ (10, 13.3]`. -/
theorem savingF_pruned_cell_1 : ∀ c ∈ Ioc (10 : ℝ) 13.3,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Ioc basePruned_monotoneOn
    (le_basePruned 3 : (11.51292 : ℝ) ≤ basePruned 10)
    (Gam_le (θ := 0.126305) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 13.3 ≤ 0.0349393) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [13.3, 15.1]`. -/
theorem savingF_pruned_cell_2 : ∀ c ∈ Icc (13.3 : ℝ) 15.1,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (15.28752 : ℝ) ≤ basePruned 13.3)
    (Gam_le (θ := 0.123498) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 15.1 ≤ 0.0461262) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [15.1, 16.3]`. -/
theorem savingF_pruned_cell_3 : ∀ c ∈ Icc (15.1 : ℝ) 16.3,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (17.33084 : ℝ) ≤ basePruned 15.1)
    (Gam_le (θ := 0.121884) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 16.3 ≤ 0.0525926) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [16.3, 17.13]`. -/
theorem savingF_pruned_cell_4 : ∀ c ∈ Icc (16.3 : ℝ) 17.13,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (18.68868 : ℝ) ≤ basePruned 16.3)
    (Gam_le (θ := 0.120864) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 17.13 ≤ 0.0566894) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [17.13, 17.74]`. -/
theorem savingF_pruned_cell_5 : ∀ c ∈ Icc (17.13 : ℝ) 17.74,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (19.62614 : ℝ) ≤ basePruned 17.13)
    (Gam_le (θ := 0.120158) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 17.74 ≤ 0.0595289) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [17.74, 18.21]`. -/
theorem savingF_pruned_cell_6 : ∀ c ∈ Icc (17.74 : ℝ) 18.21,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (20.31431 : ℝ) ≤ basePruned 17.74)
    (Gam_le (θ := 0.119638) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 18.21 ≤ 0.0616266) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [18.21, 18.58]`. -/
theorem savingF_pruned_cell_7 : ∀ c ∈ Icc (18.21 : ℝ) 18.58,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (20.84411 : ℝ) ≤ basePruned 18.21)
    (Gam_le (θ := 0.119242) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 18.58 ≤ 0.0632265) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [18.58, 18.88]`. -/
theorem savingF_pruned_cell_8 : ∀ c ∈ Icc (18.58 : ℝ) 18.88,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (21.26094 : ℝ) ≤ basePruned 18.58)
    (Gam_le (θ := 0.118928) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 18.88 ≤ 0.0644914) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [18.88, 19.13]`. -/
theorem savingF_pruned_cell_9 : ∀ c ∈ Icc (18.88 : ℝ) 19.13,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (21.59875 : ℝ) ≤ basePruned 18.88)
    (Gam_le (θ := 0.118672) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 19.13 ≤ 0.0655248) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [19.13, 19.34]`. -/
theorem savingF_pruned_cell_10 : ∀ c ∈ Icc (19.13 : ℝ) 19.34,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (21.88016 : ℝ) ≤ basePruned 19.13)
    (Gam_le (θ := 0.118461) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 19.34 ≤ 0.0663789) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [19.34, 19.52]`. -/
theorem savingF_pruned_cell_11 : ∀ c ∈ Icc (19.34 : ℝ) 19.52,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (22.11648 : ℝ) ≤ basePruned 19.34)
    (Gam_le (θ := 0.118283) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 19.52 ≤ 0.0671012) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [19.52, 19.68]`. -/
theorem savingF_pruned_cell_12 : ∀ c ∈ Icc (19.52 : ℝ) 19.68,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (22.31898 : ℝ) ≤ basePruned 19.52)
    (Gam_le (θ := 0.118126) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 19.68 ≤ 0.0677352) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [19.68, 19.82]`. -/
theorem savingF_pruned_cell_13 : ∀ c ∈ Icc (19.68 : ℝ) 19.82,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (22.49895 : ℝ) ≤ basePruned 19.68)
    (Gam_le (θ := 0.11799) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 19.82 ≤ 0.0682841) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [19.82, 19.94]`. -/
theorem savingF_pruned_cell_14 : ∀ c ∈ Icc (19.82 : ℝ) 19.94,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (22.65639 : ℝ) ≤ basePruned 19.82)
    (Gam_le (θ := 0.117875) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 19.94 ≤ 0.0687507) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [19.94, 20.05]`. -/
theorem savingF_pruned_cell_15 : ∀ c ∈ Icc (19.94 : ℝ) 20.05,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (22.79132 : ℝ) ≤ basePruned 19.94)
    (Gam_le (θ := 0.11777) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 20.05 ≤ 0.0691748) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [20.05, 20.148]`. -/
theorem savingF_pruned_cell_16 : ∀ c ∈ Icc (20.05 : ℝ) 20.148,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (22.91499 : ℝ) ≤ basePruned 20.05)
    (Gam_le (θ := 0.117678) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 20.148 ≤ 0.0695506) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [20.148, 20.235]`. -/
theorem savingF_pruned_cell_17 : ∀ c ∈ Icc (20.148 : ℝ) 20.235,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (23.02516 : ℝ) ≤ basePruned 20.148)
    (Gam_le (θ := 0.117596) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 20.235 ≤ 0.0698815) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [20.235, 20.314]`. -/
theorem savingF_pruned_cell_18 : ∀ c ∈ Icc (20.235 : ℝ) 20.314,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (23.12295 : ℝ) ≤ basePruned 20.235)
    (Gam_le (θ := 0.117522) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 20.314 ≤ 0.0701804) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [20.314, 20.385]`. -/
theorem savingF_pruned_cell_19 : ∀ c ∈ Icc (20.314 : ℝ) 20.385,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (23.21173 : ℝ) ≤ basePruned 20.314)
    (Gam_le (θ := 0.117456) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 20.385 ≤ 0.0704478) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [20.385, 20.45]`. -/
theorem savingF_pruned_cell_20 : ∀ c ∈ Icc (20.385 : ℝ) 20.45,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (23.29152 : ℝ) ≤ basePruned 20.385)
    (Gam_le (θ := 0.117396) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 20.45 ≤ 0.0706915) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [20.45, 20.509]`. -/
theorem savingF_pruned_cell_21 : ∀ c ∈ Icc (20.45 : ℝ) 20.509,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (23.36457 : ℝ) ≤ basePruned 20.45)
    (Gam_le (θ := 0.117342) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 20.509 ≤ 0.070912) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [20.509, 20.564]`. -/
theorem savingF_pruned_cell_22 : ∀ c ∈ Icc (20.509 : ℝ) 20.564,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (23.43086 : ℝ) ≤ basePruned 20.509)
    (Gam_le (θ := 0.117291) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 20.564 ≤ 0.0711162) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [20.564, 20.614]`. -/
theorem savingF_pruned_cell_23 : ∀ c ∈ Icc (20.564 : ℝ) 20.614,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (23.49266 : ℝ) ≤ basePruned 20.564)
    (Gam_le (θ := 0.117245) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 20.614 ≤ 0.0713018) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [20.614, 20.66]`. -/
theorem savingF_pruned_cell_24 : ∀ c ∈ Icc (20.614 : ℝ) 20.66,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (23.54883 : ℝ) ≤ basePruned 20.614)
    (Gam_le (θ := 0.117204) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 20.66 ≤ 0.0714719) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [20.66, 20.703]`. -/
theorem savingF_pruned_cell_25 : ∀ c ∈ Icc (20.66 : ℝ) 20.703,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (23.60051 : ℝ) ≤ basePruned 20.66)
    (Gam_le (θ := 0.117164) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 20.703 ≤ 0.0716303) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [20.703, 20.743]`. -/
theorem savingF_pruned_cell_26 : ∀ c ∈ Icc (20.703 : ℝ) 20.743,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (23.64882 : ℝ) ≤ basePruned 20.703)
    (Gam_le (θ := 0.117128) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 20.743 ≤ 0.0717768) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [20.743, 20.78]`. -/
theorem savingF_pruned_cell_27 : ∀ c ∈ Icc (20.743 : ℝ) 20.78,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (23.69375 : ℝ) ≤ basePruned 20.743)
    (Gam_le (θ := 0.117095) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 20.78 ≤ 0.0719127) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [20.78, 20.815]`. -/
theorem savingF_pruned_cell_28 : ∀ c ∈ Icc (20.78 : ℝ) 20.815,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (23.73531 : ℝ) ≤ basePruned 20.78)
    (Gam_le (θ := 0.117063) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 20.815 ≤ 0.0720403) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [20.815, 20.847]`. -/
theorem savingF_pruned_cell_29 : ∀ c ∈ Icc (20.815 : ℝ) 20.847,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (23.77463 : ℝ) ≤ basePruned 20.815)
    (Gam_le (θ := 0.117035) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 20.847 ≤ 0.0721576) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [20.847, 20.877]`. -/
theorem savingF_pruned_cell_30 : ∀ c ∈ Icc (20.847 : ℝ) 20.877,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (23.81057 : ℝ) ≤ basePruned 20.847)
    (Gam_le (θ := 0.117008) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 20.877 ≤ 0.0722668) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [20.877, 20.905]`. -/
theorem savingF_pruned_cell_31 : ∀ c ∈ Icc (20.877 : ℝ) 20.905,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (23.84426 : ℝ) ≤ basePruned 20.877)
    (Gam_le (θ := 0.116983) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 20.905 ≤ 0.0723686) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [20.905, 20.932]`. -/
theorem savingF_pruned_cell_32 : ∀ c ∈ Icc (20.905 : ℝ) 20.932,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (23.87571 : ℝ) ≤ basePruned 20.905)
    (Gam_le (θ := 0.116958) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 20.932 ≤ 0.072466) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [20.932, 20.957]`. -/
theorem savingF_pruned_cell_33 : ∀ c ∈ Icc (20.932 : ℝ) 20.957,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (23.90604 : ℝ) ≤ basePruned 20.932)
    (Gam_le (θ := 0.116936) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 20.957 ≤ 0.0725567) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [20.957, 20.981]`. -/
theorem savingF_pruned_cell_34 : ∀ c ∈ Icc (20.957 : ℝ) 20.981,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (23.93411 : ℝ) ≤ basePruned 20.957)
    (Gam_le (θ := 0.116915) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 20.981 ≤ 0.0726437) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c ∈ [20.981, 21]`. -/
theorem savingF_pruned_cell_35 : ∀ c ∈ Icc (20.981 : ℝ) 21,
    savingF (basePruned c) (Gam c) < 0.002095 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (23.96107 : ℝ) ≤ basePruned 20.981)
    (Gam_le (θ := 0.116898) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21 ≤ 0.0727122) hc

/-- `F(A(c), Γ(c)) < 0.002095` for `c` in `(10, 21]`: cells 1 to 35. -/
theorem savingF_pruned_block_1 : ∀ c ∈ Ioc (10 : ℝ) 21,
    savingF (basePruned c) (Gam c) < 0.002095 := by
  have h := savingF_pruned_cell_1
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_2
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_3
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_4
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_5
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_6
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_7
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_8
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_9
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_10
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_11
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_12
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_13
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_14
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_15
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_16
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_17
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_18
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_19
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_20
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_21
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_22
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_23
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_24
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_25
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_26
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_27
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_28
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_29
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_30
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_31
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_32
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_33
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_34
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_pruned_cell_35
  exact h

end ImprovedExponents
