module

public import ImprovedExponents.Optimum.GlobalFullCells1
public import ImprovedExponents.Optimum.GlobalFullCells2
public import ImprovedExponents.Optimum.GlobalFullCells3
public import ImprovedExponents.Optimum.GlobalFullCells4
public import ImprovedExponents.Optimum.GlobalFullCells5
public import ImprovedExponents.Optimum.GlobalFullCells6

@[expose] public section

/-!
# The saving with the paper's encodings on `(10, 200]`

This file is generated by `python3 -m search.certs`; do not edit it. It joins the
261 cells of the files `GlobalFullCells1.lean` to `GlobalFullCells6.lean` into three ranges:

* `savingF_full_lt_below`: `F(A(c), Γ(c)) < 0.002059` for `10 < c ≤ 20.8`;
* `savingF_full_lt_window`: `F(A(c), Γ(c)) < 0.002061` for `20.8 ≤ c ≤ 22`;
* `savingF_full_lt_above`: `F(A(c), Γ(c)) < 0.002059` for `22 ≤ c ≤ 200`.
-/

namespace ImprovedExponents

open Set

/-- `F(A(c), Γ(c)) < 0.002059` for `c` in `(10, 20.8]`. -/
theorem savingF_full_lt_below : ∀ c ∈ Ioc (10 : ℝ) 20.8,
    savingF (baseFull c) (Gam c) < 0.002059 := by
  have h := savingF_full_block_1
  replace h := forall_mem_Ioc_of_forall_mem_Icc h savingF_full_block_2
  exact h

/-- `F(A(c), Γ(c)) < 0.002061` for `c` in `[20.8, 22]`. -/
theorem savingF_full_lt_window : ∀ c ∈ Icc (20.8 : ℝ) 22,
    savingF (baseFull c) (Gam c) < 0.002061 := by
  have h := savingF_full_block_3
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_block_4
  exact h

/-- `F(A(c), Γ(c)) < 0.002059` for `c` in `[22, 200]`. -/
theorem savingF_full_lt_above : ∀ c ∈ Icc (22 : ℝ) 200,
    savingF (baseFull c) (Gam c) < 0.002059 := by
  have h := savingF_full_block_5
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_block_6
  exact h

end ImprovedExponents
