module

public import ImprovedExponents.Optimum.GlobalLemmas

@[expose] public section

/-!
# The saving with the paper's encodings on `[22.278, 200]`: cells 219 to 261

This file is generated by `python3 -m search.certs`; do not edit it. Each lemma bounds
`F(A(c), Γ(c))` on one cell `[c₁, c₂]` by `F(A(c₁), Γ(c₂))`, with certified rational bounds
on `A(c₁)` and `Γ(c₂)`; the last lemma joins the cells.
-/

namespace ImprovedExponents

open Set

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [22.278, 22.294]`. -/
theorem savingF_full_cell_219 : ∀ c ∈ Icc (22.278 : ℝ) 22.294,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 4 : (25.88031 : ℝ) ≤ baseFull 22.278)
    (Gam_le (θ := 0.115794) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 22.294 ≤ 0.0771953) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [22.294, 22.31]`. -/
theorem savingF_full_cell_220 : ∀ c ∈ Icc (22.294 : ℝ) 22.31,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 4 : (25.8992 : ℝ) ≤ baseFull 22.294)
    (Gam_le (θ := 0.115781) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 22.31 ≤ 0.0772485) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [22.31, 22.327]`. -/
theorem savingF_full_cell_221 : ∀ c ∈ Icc (22.31 : ℝ) 22.327,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 4 : (25.9181 : ℝ) ≤ baseFull 22.31)
    (Gam_le (θ := 0.115767) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 22.327 ≤ 0.0773052) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [22.327, 22.345]`. -/
theorem savingF_full_cell_222 : ∀ c ∈ Icc (22.327 : ℝ) 22.345,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 4 : (25.93818 : ℝ) ≤ baseFull 22.327)
    (Gam_le (θ := 0.115753) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 22.345 ≤ 0.0773651) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [22.345, 22.365]`. -/
theorem savingF_full_cell_223 : ∀ c ∈ Icc (22.345 : ℝ) 22.365,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 4 : (25.95944 : ℝ) ≤ baseFull 22.345)
    (Gam_le (θ := 0.115736) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 22.365 ≤ 0.0774313) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [22.365, 22.386]`. -/
theorem savingF_full_cell_224 : ∀ c ∈ Icc (22.365 : ℝ) 22.386,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 4 : (25.98306 : ℝ) ≤ baseFull 22.365)
    (Gam_le (θ := 0.115719) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 22.386 ≤ 0.0775006) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [22.386, 22.408]`. -/
theorem savingF_full_cell_225 : ∀ c ∈ Icc (22.386 : ℝ) 22.408,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 4 : (26.00786 : ℝ) ≤ baseFull 22.386)
    (Gam_le (θ := 0.115701) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 22.408 ≤ 0.0775738) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [22.408, 22.432]`. -/
theorem savingF_full_cell_226 : ∀ c ∈ Icc (22.408 : ℝ) 22.432,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 4 : (26.03385 : ℝ) ≤ baseFull 22.408)
    (Gam_le (θ := 0.115682) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 22.432 ≤ 0.0776528) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [22.432, 22.457]`. -/
theorem savingF_full_cell_227 : ∀ c ∈ Icc (22.432 : ℝ) 22.457,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 4 : (26.06219 : ℝ) ≤ baseFull 22.432)
    (Gam_le (θ := 0.115662) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 22.457 ≤ 0.0777355) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [22.457, 22.484]`. -/
theorem savingF_full_cell_228 : ∀ c ∈ Icc (22.457 : ℝ) 22.484,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 4 : (26.09172 : ℝ) ≤ baseFull 22.457)
    (Gam_le (θ := 0.11564) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 22.484 ≤ 0.0778243) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [22.484, 22.513]`. -/
theorem savingF_full_cell_229 : ∀ c ∈ Icc (22.484 : ℝ) 22.513,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 4 : (26.12362 : ℝ) ≤ baseFull 22.484)
    (Gam_le (θ := 0.115616) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 22.513 ≤ 0.0779197) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [22.513, 22.544]`. -/
theorem savingF_full_cell_230 : ∀ c ∈ Icc (22.513 : ℝ) 22.544,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 4 : (26.15787 : ℝ) ≤ baseFull 22.513)
    (Gam_le (θ := 0.115591) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 22.544 ≤ 0.0780214) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [22.544, 22.578]`. -/
theorem savingF_full_cell_231 : ∀ c ∈ Icc (22.544 : ℝ) 22.578,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 4 : (26.19449 : ℝ) ≤ baseFull 22.544)
    (Gam_le (θ := 0.115564) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 22.578 ≤ 0.0781325) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [22.578, 22.614]`. -/
theorem savingF_full_cell_232 : ∀ c ∈ Icc (22.578 : ℝ) 22.614,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 4 : (26.23466 : ℝ) ≤ baseFull 22.578)
    (Gam_le (θ := 0.115535) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 22.614 ≤ 0.0782501) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [22.614, 22.653]`. -/
theorem savingF_full_cell_233 : ∀ c ∈ Icc (22.614 : ℝ) 22.653,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 4 : (26.27718 : ℝ) ≤ baseFull 22.614)
    (Gam_le (θ := 0.115504) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 22.653 ≤ 0.0783775) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [22.653, 22.695]`. -/
theorem savingF_full_cell_234 : ∀ c ∈ Icc (22.653 : ℝ) 22.695,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (26.32326 : ℝ) ≤ baseFull 22.653)
    (Gam_le (θ := 0.11547) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 22.695 ≤ 0.078514) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [22.695, 22.741]`. -/
theorem savingF_full_cell_235 : ∀ c ∈ Icc (22.695 : ℝ) 22.741,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (26.37288 : ℝ) ≤ baseFull 22.695)
    (Gam_le (θ := 0.115434) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 22.741 ≤ 0.0786635) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [22.741, 22.791]`. -/
theorem savingF_full_cell_236 : ∀ c ∈ Icc (22.741 : ℝ) 22.791,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (26.42723 : ℝ) ≤ baseFull 22.741)
    (Gam_le (θ := 0.115394) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 22.791 ≤ 0.0788251) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [22.791, 22.846]`. -/
theorem savingF_full_cell_237 : ∀ c ∈ Icc (22.791 : ℝ) 22.846,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (26.4863 : ℝ) ≤ baseFull 22.791)
    (Gam_le (θ := 0.11535) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 22.846 ≤ 0.0790027) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [22.846, 22.906]`. -/
theorem savingF_full_cell_238 : ∀ c ∈ Icc (22.846 : ℝ) 22.906,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (26.55129 : ℝ) ≤ baseFull 22.846)
    (Gam_le (θ := 0.115303) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 22.906 ≤ 0.0791953) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [22.906, 22.972]`. -/
theorem savingF_full_cell_239 : ∀ c ∈ Icc (22.906 : ℝ) 22.972,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (26.62218 : ℝ) ≤ baseFull 22.906)
    (Gam_le (θ := 0.115251) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 22.972 ≤ 0.0794066) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [22.972, 23.045]`. -/
theorem savingF_full_cell_240 : ∀ c ∈ Icc (22.972 : ℝ) 23.045,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (26.70018 : ℝ) ≤ baseFull 22.972)
    (Gam_le (θ := 0.115194) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 23.045 ≤ 0.0796395) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [23.045, 23.126]`. -/
theorem savingF_full_cell_241 : ∀ c ∈ Icc (23.045 : ℝ) 23.126,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (26.78644 : ℝ) ≤ baseFull 23.045)
    (Gam_le (θ := 0.115131) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 23.126 ≤ 0.0798968) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [23.126, 23.216]`. -/
theorem savingF_full_cell_242 : ∀ c ∈ Icc (23.126 : ℝ) 23.216,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (26.88217 : ℝ) ≤ baseFull 23.126)
    (Gam_le (θ := 0.115061) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 23.216 ≤ 0.080181) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [23.216, 23.31]`. -/
theorem savingF_full_cell_243 : ∀ c ∈ Icc (23.216 : ℝ) 23.31,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (26.98855 : ℝ) ≤ baseFull 23.216)
    (Gam_le (θ := 0.114989) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 23.31 ≤ 0.0804768) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [23.31, 23.42]`. -/
theorem savingF_full_cell_244 : ∀ c ∈ Icc (23.31 : ℝ) 23.42,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (27.09965 : ℝ) ≤ baseFull 23.31)
    (Gam_le (θ := 0.114904) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 23.42 ≤ 0.08082) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [23.42, 23.54]`. -/
theorem savingF_full_cell_245 : ∀ c ∈ Icc (23.42 : ℝ) 23.54,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (27.22968 : ℝ) ≤ baseFull 23.42)
    (Gam_le (θ := 0.114813) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 23.54 ≤ 0.0811927) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [23.54, 23.68]`. -/
theorem savingF_full_cell_246 : ∀ c ∈ Icc (23.54 : ℝ) 23.68,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (27.37155 : ℝ) ≤ baseFull 23.54)
    (Gam_le (θ := 0.114707) (gammaX_le 5) (gammaQ_le (-3)) :
      Gam 23.68 ≤ 0.0816238) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [23.68, 23.84]`. -/
theorem savingF_full_cell_247 : ∀ c ∈ Icc (23.68 : ℝ) 23.84,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (27.53708 : ℝ) ≤ baseFull 23.68)
    (Gam_le (θ := 0.114587) (gammaX_le 5) (gammaQ_le (-3)) :
      Gam 23.84 ≤ 0.0821129) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [23.84, 24.03]`. -/
theorem savingF_full_cell_248 : ∀ c ∈ Icc (23.84 : ℝ) 24.03,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (27.72627 : ℝ) ≤ baseFull 23.84)
    (Gam_le (θ := 0.114447) (gammaX_le 5) (gammaQ_le (-3)) :
      Gam 24.03 ≤ 0.0826878) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [24.03, 24.25]`. -/
theorem savingF_full_cell_249 : ∀ c ∈ Icc (24.03 : ℝ) 24.25,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (27.95097 : ℝ) ≤ baseFull 24.03)
    (Gam_le (θ := 0.114285) (gammaX_le 5) (gammaQ_le (-3)) :
      Gam 24.25 ≤ 0.0833454) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [24.25, 24.52]`. -/
theorem savingF_full_cell_250 : ∀ c ∈ Icc (24.25 : ℝ) 24.52,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (28.21119 : ℝ) ≤ baseFull 24.25)
    (Gam_le (θ := 0.11409) (gammaX_le 5) (gammaQ_le (-3)) :
      Gam 24.52 ≤ 0.0841418) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [24.52, 24.85]`. -/
theorem savingF_full_cell_251 : ∀ c ∈ Icc (24.52 : ℝ) 24.85,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (28.53061 : ℝ) ≤ baseFull 24.52)
    (Gam_le (θ := 0.113856) (gammaX_le 5) (gammaQ_le (-3)) :
      Gam 24.85 ≤ 0.0850999) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [24.85, 25.25]`. -/
theorem savingF_full_cell_252 : ∀ c ∈ Icc (24.85 : ℝ) 25.25,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (28.9211 : ℝ) ≤ baseFull 24.85)
    (Gam_le (θ := 0.113577) (gammaX_le 5) (gammaQ_le (-3)) :
      Gam 25.25 ≤ 0.0862384) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [25.25, 25.76]`. -/
theorem savingF_full_cell_253 : ∀ c ∈ Icc (25.25 : ℝ) 25.76,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (29.39454 : ℝ) ≤ baseFull 25.25)
    (Gam_le (θ := 0.113231) (gammaX_le 5) (gammaQ_le (-3)) :
      Gam 25.76 ≤ 0.0876554) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [25.76, 26.43]`. -/
theorem savingF_full_cell_254 : ∀ c ∈ Icc (25.76 : ℝ) 26.43,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (29.99837 : ℝ) ≤ baseFull 25.76)
    (Gam_le (θ := 0.11279) (gammaX_le 5) (gammaQ_le (-3)) :
      Gam 26.43 ≤ 0.0894614) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [26.43, 27.35]`. -/
theorem savingF_full_cell_255 : ∀ c ∈ Icc (26.43 : ℝ) 27.35,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (30.79194 : ℝ) ≤ baseFull 26.43)
    (Gam_le (θ := 0.112209) (gammaX_le 5) (gammaQ_le (-3)) :
      Gam 27.35 ≤ 0.0918445) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [27.35, 28.6]`. -/
theorem savingF_full_cell_256 : ∀ c ∈ Icc (27.35 : ℝ) 28.6,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (31.88216 : ℝ) ≤ baseFull 27.35)
    (Gam_le (θ := 0.111461) (gammaX_le 5) (gammaQ_le (-3)) :
      Gam 28.6 ≤ 0.0949174) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [28.6, 30.6]`. -/
theorem savingF_full_cell_257 : ∀ c ∈ Icc (28.6 : ℝ) 30.6,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (33.36437 : ℝ) ≤ baseFull 28.6)
    (Gam_le (θ := 0.110351) (gammaX_le 5) (gammaQ_le (-3)) :
      Gam 30.6 ≤ 0.0994813) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [30.6, 34.1]`. -/
theorem savingF_full_cell_258 : ∀ c ∈ Icc (30.6 : ℝ) 34.1,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (35.73794 : ℝ) ≤ baseFull 30.6)
    (Gam_le (θ := 0.108629) (gammaX_le 5) (gammaQ_le (-3)) :
      Gam 34.1 ≤ 0.1065956) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [34.1, 41.5]`. -/
theorem savingF_full_cell_259 : ∀ c ∈ Icc (34.1 : ℝ) 41.5,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (39.89684 : ℝ) ≤ baseFull 34.1)
    (Gam_le (θ := 0.105662) (gammaX_le 5) (gammaQ_le (-3)) :
      Gam 41.5 ≤ 0.1189153) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [41.5, 65]`. -/
theorem savingF_full_cell_260 : ∀ c ∈ Icc (41.5 : ℝ) 65,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 5 : (48.7067 : ℝ) ≤ baseFull 41.5)
    (Gam_le (θ := 0.099542) (gammaX_le 6) (gammaQ_le (-3)) :
      Gam 65 ≤ 0.1446115) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c ∈ [65, 200]`. -/
theorem savingF_full_cell_261 : ∀ c ∈ Icc (65 : ℝ) 200,
    savingF (baseFull c) (Gam c) < 0.002059 := fun _ hc =>
  savingF_lt_of_mem_Icc baseFull_monotoneOn
    (le_baseFull 6 : (76.77351 : ℝ) ≤ baseFull 65)
    (Gam_le (θ := 0.087215) (gammaX_le 8) (gammaQ_le (-4)) :
      Gam 200 ≤ 0.1976223) hc

/-- `F(A(c), Γ(c)) < 0.002059` for `c` in `[22.278, 200]`: cells 219 to 261. -/
theorem savingF_full_block_6 : ∀ c ∈ Icc (22.278 : ℝ) 200,
    savingF (baseFull c) (Gam c) < 0.002059 := by
  have h := savingF_full_cell_219
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_220
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_221
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_222
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_223
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_224
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_225
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_226
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_227
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_228
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_229
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_230
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_231
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_232
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_233
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_234
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_235
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_236
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_237
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_238
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_239
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_240
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_241
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_242
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_243
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_244
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_245
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_246
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_247
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_248
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_249
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_250
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_251
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_252
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_253
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_254
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_255
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_256
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_257
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_258
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_259
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_260
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_full_cell_261
  exact h

end ImprovedExponents
