module

public import ImprovedExponents.Optimum.GlobalCells1
public import ImprovedExponents.Optimum.GlobalCells2
public import ImprovedExponents.Optimum.GlobalCells3
public import ImprovedExponents.Optimum.GlobalCells4
public import ImprovedExponents.Optimum.GlobalCells5

@[expose] public section

/-!
# The saving with pruned encodings on `(10, 200]`

This file is generated by `python3 -m search.certs`; do not edit it. It joins the
222 cells of the files `GlobalCells1.lean` to `GlobalCells5.lean` into three ranges:

* `savingF_pruned_lt_below`: `F(A(c), Γ(c)) < 0.002095` for `10 < c ≤ 21`;
* `savingF_pruned_lt_window`: `F(A(c), Γ(c)) < 0.002096` for `21 ≤ c ≤ 23`;
* `savingF_pruned_lt_above`: `F(A(c), Γ(c)) < 0.002095` for `23 ≤ c ≤ 200`.
-/

namespace ImprovedExponents

open Set

/-- `F(A(c), Γ(c)) < 0.002095` for `c` in `(10, 21]`. -/
theorem savingF_pruned_lt_below : ∀ c ∈ Ioc (10 : ℝ) 21,
    savingF (basePruned c) (Gam c) < 0.002095 :=
  savingF_pruned_block_1

/-- `F(A(c), Γ(c)) < 0.002096` for `c` in `[21, 23]`. -/
theorem savingF_pruned_lt_window : ∀ c ∈ Icc (21 : ℝ) 23,
    savingF (basePruned c) (Gam c) < 0.002096 := by
  have h := savingF_pruned_block_2
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_block_3
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_block_4
  exact h

/-- `F(A(c), Γ(c)) < 0.002095` for `c` in `[23, 200]`. -/
theorem savingF_pruned_lt_above : ∀ c ∈ Icc (23 : ℝ) 200,
    savingF (basePruned c) (Gam c) < 0.002095 :=
  savingF_pruned_block_5

end ImprovedExponents
