module

public import ImprovedExponents.Optimum.GlobalLemmas

@[expose] public section

/-!
# The saving with pruned encodings on `[21, 21.7331]`: cells 36 to 86

This file is generated by `python3 -m search.certs`; do not edit it. Each lemma bounds
`F(A(c), Γ(c))` on one cell `[c₁, c₂]` by `F(A(c₁), Γ(c₂))`, with certified rational bounds
on `A(c₁)` and `Γ(c₂)`; the last lemma joins the cells.
-/

namespace ImprovedExponents

open Set

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21, 21.031]`. -/
theorem savingF_pruned_cell_36 : ∀ c ∈ Icc (21 : ℝ) 21.031,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (23.9824 : ℝ) ≤ basePruned 21)
    (Gam_le (θ := 0.11687) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.031 ≤ 0.0728237) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.031, 21.06]`. -/
theorem savingF_pruned_cell_37 : ∀ c ∈ Icc (21.031 : ℝ) 21.06,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.01722 : ℝ) ≤ basePruned 21.031)
    (Gam_le (θ := 0.116845) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.06 ≤ 0.0729285) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.06, 21.088]`. -/
theorem savingF_pruned_cell_38 : ∀ c ∈ Icc (21.06 : ℝ) 21.088,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.04978 : ℝ) ≤ basePruned 21.06)
    (Gam_le (θ := 0.11682) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.088 ≤ 0.0730289) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.088, 21.114]`. -/
theorem savingF_pruned_cell_39 : ∀ c ∈ Icc (21.088 : ℝ) 21.114,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.08122 : ℝ) ≤ basePruned 21.088)
    (Gam_le (θ := 0.116797) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.114 ≤ 0.0731221) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.114, 21.139]`. -/
theorem savingF_pruned_cell_40 : ∀ c ∈ Icc (21.114 : ℝ) 21.139,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.11042 : ℝ) ≤ basePruned 21.114)
    (Gam_le (θ := 0.116775) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.139 ≤ 0.0732116) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.139, 21.163]`. -/
theorem savingF_pruned_cell_41 : ∀ c ∈ Icc (21.139 : ℝ) 21.163,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.13849 : ℝ) ≤ basePruned 21.139)
    (Gam_le (θ := 0.116754) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.163 ≤ 0.0732974) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.163, 21.186]`. -/
theorem savingF_pruned_cell_42 : ∀ c ∈ Icc (21.163 : ℝ) 21.186,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.16544 : ℝ) ≤ basePruned 21.163)
    (Gam_le (θ := 0.116733) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.186 ≤ 0.0733792) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.186, 21.208]`. -/
theorem savingF_pruned_cell_43 : ∀ c ∈ Icc (21.186 : ℝ) 21.208,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.19126 : ℝ) ≤ basePruned 21.186)
    (Gam_le (θ := 0.116714) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.208 ≤ 0.0734575) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.208, 21.229]`. -/
theorem savingF_pruned_cell_44 : ∀ c ∈ Icc (21.208 : ℝ) 21.229,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.21596 : ℝ) ≤ basePruned 21.208)
    (Gam_le (θ := 0.116696) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.229 ≤ 0.0735325) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.229, 21.249]`. -/
theorem savingF_pruned_cell_45 : ∀ c ∈ Icc (21.229 : ℝ) 21.249,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.23954 : ℝ) ≤ basePruned 21.229)
    (Gam_le (θ := 0.116678) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.249 ≤ 0.0736033) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.249, 21.268]`. -/
theorem savingF_pruned_cell_46 : ∀ c ∈ Icc (21.249 : ℝ) 21.268,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.262 : ℝ) ≤ basePruned 21.249)
    (Gam_le (θ := 0.116662) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.268 ≤ 0.0736711) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.268, 21.287]`. -/
theorem savingF_pruned_cell_47 : ∀ c ∈ Icc (21.268 : ℝ) 21.287,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.28333 : ℝ) ≤ basePruned 21.268)
    (Gam_le (θ := 0.116645) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.287 ≤ 0.0737382) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.287, 21.305]`. -/
theorem savingF_pruned_cell_48 : ∀ c ∈ Icc (21.287 : ℝ) 21.305,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.30466 : ℝ) ≤ basePruned 21.287)
    (Gam_le (θ := 0.116629) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.305 ≤ 0.0738017) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.305, 21.322]`. -/
theorem savingF_pruned_cell_49 : ∀ c ∈ Icc (21.305 : ℝ) 21.322,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.32487 : ℝ) ≤ basePruned 21.305)
    (Gam_le (θ := 0.116614) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.322 ≤ 0.0738623) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.322, 21.339]`. -/
theorem savingF_pruned_cell_50 : ∀ c ∈ Icc (21.322 : ℝ) 21.339,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.34395 : ℝ) ≤ basePruned 21.322)
    (Gam_le (θ := 0.1166) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.339 ≤ 0.0739223) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.339, 21.355]`. -/
theorem savingF_pruned_cell_51 : ∀ c ∈ Icc (21.339 : ℝ) 21.355,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.36304 : ℝ) ≤ basePruned 21.339)
    (Gam_le (θ := 0.116586) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.355 ≤ 0.0739787) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.355, 21.371]`. -/
theorem savingF_pruned_cell_52 : ∀ c ∈ Icc (21.355 : ℝ) 21.371,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.381 : ℝ) ≤ basePruned 21.355)
    (Gam_le (θ := 0.116572) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.371 ≤ 0.074035) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.371, 21.386]`. -/
theorem savingF_pruned_cell_53 : ∀ c ∈ Icc (21.371 : ℝ) 21.386,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.39896 : ℝ) ≤ basePruned 21.371)
    (Gam_le (θ := 0.116559) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.386 ≤ 0.0740878) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.386, 21.401]`. -/
theorem savingF_pruned_cell_54 : ∀ c ∈ Icc (21.386 : ℝ) 21.401,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.4158 : ℝ) ≤ basePruned 21.386)
    (Gam_le (θ := 0.116546) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.401 ≤ 0.0741406) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.401, 21.415]`. -/
theorem savingF_pruned_cell_55 : ∀ c ∈ Icc (21.401 : ℝ) 21.415,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.43263 : ℝ) ≤ basePruned 21.401)
    (Gam_le (θ := 0.116534) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.415 ≤ 0.0741899) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.415, 21.429]`. -/
theorem savingF_pruned_cell_56 : ∀ c ∈ Icc (21.415 : ℝ) 21.429,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.44835 : ℝ) ≤ basePruned 21.415)
    (Gam_le (θ := 0.116522) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.429 ≤ 0.0742392) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.429, 21.442]`. -/
theorem savingF_pruned_cell_57 : ∀ c ∈ Icc (21.429 : ℝ) 21.442,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.46407 : ℝ) ≤ basePruned 21.429)
    (Gam_le (θ := 0.11651) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.442 ≤ 0.0742847) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.442, 21.455]`. -/
theorem savingF_pruned_cell_58 : ∀ c ∈ Icc (21.442 : ℝ) 21.455,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.47866 : ℝ) ≤ basePruned 21.442)
    (Gam_le (θ := 0.116499) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.455 ≤ 0.07433) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.455, 21.468]`. -/
theorem savingF_pruned_cell_59 : ∀ c ∈ Icc (21.455 : ℝ) 21.468,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.49325 : ℝ) ≤ basePruned 21.455)
    (Gam_le (θ := 0.116488) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.468 ≤ 0.0743757) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.468, 21.48]`. -/
theorem savingF_pruned_cell_60 : ∀ c ∈ Icc (21.468 : ℝ) 21.48,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.50784 : ℝ) ≤ basePruned 21.468)
    (Gam_le (θ := 0.116478) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.48 ≤ 0.0744179) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.48, 21.492]`. -/
theorem savingF_pruned_cell_61 : ∀ c ∈ Icc (21.48 : ℝ) 21.492,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.52131 : ℝ) ≤ basePruned 21.48)
    (Gam_le (θ := 0.116467) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.492 ≤ 0.0744595) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.492, 21.504]`. -/
theorem savingF_pruned_cell_62 : ∀ c ∈ Icc (21.492 : ℝ) 21.504,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.53478 : ℝ) ≤ basePruned 21.492)
    (Gam_le (θ := 0.116457) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.504 ≤ 0.0745016) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.504, 21.515]`. -/
theorem savingF_pruned_cell_63 : ∀ c ∈ Icc (21.504 : ℝ) 21.515,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.54825 : ℝ) ≤ basePruned 21.504)
    (Gam_le (θ := 0.116448) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.515 ≤ 0.0745404) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.515, 21.526]`. -/
theorem savingF_pruned_cell_64 : ∀ c ∈ Icc (21.515 : ℝ) 21.526,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.5606 : ℝ) ≤ basePruned 21.515)
    (Gam_le (θ := 0.116438) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.526 ≤ 0.0745784) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.526, 21.537]`. -/
theorem savingF_pruned_cell_65 : ∀ c ∈ Icc (21.526 : ℝ) 21.537,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.57294 : ℝ) ≤ basePruned 21.526)
    (Gam_le (θ := 0.116429) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.537 ≤ 0.0746171) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.537, 21.548]`. -/
theorem savingF_pruned_cell_66 : ∀ c ∈ Icc (21.537 : ℝ) 21.548,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.58529 : ℝ) ≤ basePruned 21.537)
    (Gam_le (θ := 0.116419) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.548 ≤ 0.074655) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.548, 21.559]`. -/
theorem savingF_pruned_cell_67 : ∀ c ∈ Icc (21.548 : ℝ) 21.559,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.59764 : ℝ) ≤ basePruned 21.548)
    (Gam_le (θ := 0.11641) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.559 ≤ 0.0746936) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.559, 21.569]`. -/
theorem savingF_pruned_cell_68 : ∀ c ∈ Icc (21.559 : ℝ) 21.569,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.60998 : ℝ) ≤ basePruned 21.559)
    (Gam_le (θ := 0.116401) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.569 ≤ 0.0747281) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.569, 21.579]`. -/
theorem savingF_pruned_cell_69 : ∀ c ∈ Icc (21.569 : ℝ) 21.579,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.62121 : ℝ) ≤ basePruned 21.569)
    (Gam_le (θ := 0.116393) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.579 ≤ 0.0747633) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.579, 21.589]`. -/
theorem savingF_pruned_cell_70 : ∀ c ∈ Icc (21.579 : ℝ) 21.589,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.63243 : ℝ) ≤ basePruned 21.579)
    (Gam_le (θ := 0.116384) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.589 ≤ 0.0747978) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.589, 21.599]`. -/
theorem savingF_pruned_cell_71 : ∀ c ∈ Icc (21.589 : ℝ) 21.599,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.64365 : ℝ) ≤ basePruned 21.589)
    (Gam_le (θ := 0.116376) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.599 ≤ 0.0748329) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.599, 21.609]`. -/
theorem savingF_pruned_cell_72 : ∀ c ∈ Icc (21.599 : ℝ) 21.609,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.65488 : ℝ) ≤ basePruned 21.599)
    (Gam_le (θ := 0.116367) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.609 ≤ 0.0748673) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.609, 21.6187]`. -/
theorem savingF_pruned_cell_73 : ∀ c ∈ Icc (21.609 : ℝ) 21.6187,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.6661 : ℝ) ≤ basePruned 21.609)
    (Gam_le (θ := 0.116359) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.6187 ≤ 0.0749012) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.6187, 21.6282]`. -/
theorem savingF_pruned_cell_74 : ∀ c ∈ Icc (21.6187 : ℝ) 21.6282,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.67698 : ℝ) ≤ basePruned 21.6187)
    (Gam_le (θ := 0.116351) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.6282 ≤ 0.0749342) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.6282, 21.6376]`. -/
theorem savingF_pruned_cell_75 : ∀ c ∈ Icc (21.6282 : ℝ) 21.6376,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.68765 : ℝ) ≤ basePruned 21.6282)
    (Gam_le (θ := 0.116343) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.6376 ≤ 0.0749668) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.6376, 21.6469]`. -/
theorem savingF_pruned_cell_76 : ∀ c ∈ Icc (21.6376 : ℝ) 21.6469,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.6982 : ℝ) ≤ basePruned 21.6376)
    (Gam_le (θ := 0.116335) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.6469 ≤ 0.074999) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.6469, 21.656]`. -/
theorem savingF_pruned_cell_77 : ∀ c ∈ Icc (21.6469 : ℝ) 21.656,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.70863 : ℝ) ≤ basePruned 21.6469)
    (Gam_le (θ := 0.116327) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.656 ≤ 0.0750303) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.656, 21.6651]`. -/
theorem savingF_pruned_cell_78 : ∀ c ∈ Icc (21.656 : ℝ) 21.6651,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.71885 : ℝ) ≤ basePruned 21.656)
    (Gam_le (θ := 0.116319) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.6651 ≤ 0.0750616) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.6651, 21.6739]`. -/
theorem savingF_pruned_cell_79 : ∀ c ∈ Icc (21.6651 : ℝ) 21.6739,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.72906 : ℝ) ≤ basePruned 21.6651)
    (Gam_le (θ := 0.116312) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.6739 ≤ 0.0750924) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.6739, 21.6827]`. -/
theorem savingF_pruned_cell_80 : ∀ c ∈ Icc (21.6739 : ℝ) 21.6827,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.73893 : ℝ) ≤ basePruned 21.6739)
    (Gam_le (θ := 0.116304) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.6827 ≤ 0.0751224) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.6827, 21.6913]`. -/
theorem savingF_pruned_cell_81 : ∀ c ∈ Icc (21.6827 : ℝ) 21.6913,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.74881 : ℝ) ≤ basePruned 21.6827)
    (Gam_le (θ := 0.116297) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.6913 ≤ 0.0751524) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.6913, 21.6998]`. -/
theorem savingF_pruned_cell_82 : ∀ c ∈ Icc (21.6913 : ℝ) 21.6998,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.75846 : ℝ) ≤ basePruned 21.6913)
    (Gam_le (θ := 0.11629) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.6998 ≤ 0.0751819) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.6998, 21.7082]`. -/
theorem savingF_pruned_cell_83 : ∀ c ∈ Icc (21.6998 : ℝ) 21.7082,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.768 : ℝ) ≤ basePruned 21.6998)
    (Gam_le (θ := 0.116283) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.7082 ≤ 0.0752109) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.7082, 21.7166]`. -/
theorem savingF_pruned_cell_84 : ∀ c ∈ Icc (21.7082 : ℝ) 21.7166,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.77743 : ℝ) ≤ basePruned 21.7082)
    (Gam_le (θ := 0.116275) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.7166 ≤ 0.0752395) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.7166, 21.7249]`. -/
theorem savingF_pruned_cell_85 : ∀ c ∈ Icc (21.7166 : ℝ) 21.7249,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.78685 : ℝ) ≤ basePruned 21.7166)
    (Gam_le (θ := 0.116268) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.7249 ≤ 0.0752679) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c ∈ [21.7249, 21.7331]`. -/
theorem savingF_pruned_cell_86 : ∀ c ∈ Icc (21.7249 : ℝ) 21.7331,
    savingF (basePruned c) (Gam c) < 0.002096 := fun _ hc =>
  savingF_lt_of_mem_Icc basePruned_monotoneOn
    (le_basePruned 4 : (24.79617 : ℝ) ≤ basePruned 21.7249)
    (Gam_le (θ := 0.116261) (gammaX_le 4) (gammaQ_le (-3)) :
      Gam 21.7331 ≤ 0.0752964) hc

/-- `F(A(c), Γ(c)) < 0.002096` for `c` in `[21, 21.7331]`: cells 36 to 86. -/
theorem savingF_pruned_block_2 : ∀ c ∈ Icc (21 : ℝ) 21.7331,
    savingF (basePruned c) (Gam c) < 0.002096 := by
  have h := savingF_pruned_cell_36
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_37
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_38
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_39
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_40
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_41
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_42
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_43
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_44
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_45
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_46
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_47
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_48
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_49
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_50
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_51
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_52
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_53
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_54
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_55
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_56
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_57
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_58
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_59
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_60
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_61
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_62
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_63
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_64
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_65
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_66
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_67
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_68
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_69
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_70
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_71
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_72
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_73
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_74
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_75
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_76
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_77
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_78
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_79
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_80
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_81
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_82
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_83
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_84
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_85
  replace h := forall_mem_Icc_of_forall_mem_Icc h savingF_pruned_cell_86
  exact h

end ImprovedExponents
